import type { Bundle } from "./ko";

export const en: Bundle = {
  "common.close": "Close",
  "common.back": "Back",
  "common.on": "On",
  "common.off": "Off",
  "common.none": "Off",

  "settings.title": "Settings",
  "settings.sound": "Sound",
  "settings.music": "Music",
  "settings.effects": "Effects",
  "settings.controls": "Controls",
  "settings.sensitivity": "Mouse sensitivity",
  "settings.times": "{n}×",
  "settings.screen": "Screen",
  "settings.brightness": "Brightness",
  "settings.quality": "Graphics",
  "settings.quality.low": "Low",
  "settings.quality.mid": "Medium",
  "settings.quality.high": "High",
  "settings.quality.note": "Lower is lighter on your battery. It changes how far trees and grass are drawn in full, and the screen's resolution.",
  "settings.shown": "Shown",
  "settings.showNames": "Other players' names",
  "settings.damageNumbers": "Damage numbers",
  "settings.announcements": "Announcements",
  "announce.legendary": "[{server}] {name} got the legendary mount {mount}!",
  "announce.star5": "[{server}] {name}'s {mount} broke through to ★5!",
  "announce.enhance": "[{server}] {name} enhanced {item}!",
  "announce.guildBoss": "Guild <{guild}> slew the {boss}!",
  "settings.language": "Language",
  "settings.keysTab": "Shortcuts",
  "settings.defaults": "Defaults",
  "settings.exit": "Back to the menu",

  "keys.jump": "Jump",
  "keys.click": "Left / right click",
  "keys.attackGuard": "Attack / guard",
  "keys.skills": "Skills",
  "keys.potion": "Potion",
  "keys.talk": "Talk",
  "keys.auto": "Auto-battle",
  "keys.quest": "Go to / report quest",
  "keys.chat": "Chat",
  "keys.menu": "Open the menu",
  "keys.closeWindow": "Close the window",
  "keys.map": "Map",
  "keys.panels": "Ranking / quests / skills / forge / bag / mounts",
  "keys.powerSave": "Power saving",
  "keys.settings": "Settings",

  "list.join": ", ",
  "stat.power": "Attack +{n}%",
  "stat.hp": "Health +{n}",
  "stat.guard": "Damage taken -{n}%",
  "stat.heal": "Healing +{n}%",

  "class.warrior": "Warrior",
  "class.ranger": "Ranger",
  "class.wizard": "Wizard",
  "class.cleric": "Cleric",
  "class.rogue": "Rogue",
  "class.monk": "Monk",
  "class.warrior.blurb": "Longsword and armour. Stands its ground and cuts.",
  "class.ranger.blurb": "Shoots from afar. Weak once something closes in.",
  "class.wizard.blurb": "Throws bolts from a staff. Slow, but reaches far.",
  "class.cleric.blurb": "Heals itself and the people beside it.",
  "class.rogue.blurb": "Stabs very fast with a dagger.",
  "class.monk.blurb": "Bare fists in a flurry, and blows that stun.",

  "weapon.warrior": "Longsword",
  "weapon.ranger": "Bow",
  "weapon.wizard": "Magic staff",
  "weapon.cleric": "Holy staff",
  "weapon.rogue": "Dagger",
  "weapon.monk": "Fists",

  "skill.warrior.0": "Whirl",
  "skill.warrior.0.blurb": "Spins once, cutting every monster around you.",
  "skill.berserker.0": "Charging Cut",
  "skill.berserker.0.blurb": "A wide cut ahead that knocks them down for a moment.",
  "skill.berserker.1": "Earthbreaker",
  "skill.berserker.1.blurb": "Strikes the ground and stuns everything around you.",
  "skill.ranger.0": "Piercing Arrow",
  "skill.ranger.0.blurb": "Flies straight ahead and runs through everything in line.",
  "skill.sniper.0": "Aimed Shot",
  "skill.sniper.0.blurb": "Takes one target and hits it hard.",
  "skill.sniper.1": "Arrow Rain",
  "skill.sniper.1.blurb": "Pours arrows down all around you.",
  "skill.wizard.0": "Flame Burst",
  "skill.wizard.0.blurb": "Covers the ground around you in fire.",
  "skill.elementalist.0": "Ice Spear",
  "skill.elementalist.0.blurb": "Runs one through and freezes it in place.",
  "skill.elementalist.1": "Meteor",
  "skill.elementalist.1.blurb": "Drops a ball of fire from the sky and burns the ground around you.",
  "skill.cleric.0": "Healing Light",
  "skill.cleric.0.blurb": "Gives health back to you and the people near you.",
  "skill.paladin.0": "Holy Strike",
  "skill.paladin.0.blurb": "Light along the staff, striking ahead and stunning.",
  "skill.high_priest.1": "Blessing",
  "skill.high_priest.1.blurb": "Burns the monsters around you and heals everyone near you deeply.",
  "skill.rogue.0": "Shadow Strike",
  "skill.rogue.0.blurb": "One deep thrust into the monster ahead.",
  "skill.assassin.0": "Blade Fan",
  "skill.assassin.0.blurb": "Scatters daggers ahead of you.",
  "skill.assassin.1": "Shadow Flurry",
  "skill.assassin.1.blurb": "Whirls through everything around you.",
  "skill.monk.0": "Stunning Flurry",
  "skill.monk.0.blurb": "Pummels the monster ahead and stuns it for a while.",
  "skill.fist_master.0": "Whirlwind Kick",
  "skill.fist_master.0.blurb": "Spins and kicks everything around you.",
  "skill.fist_master.1": "White Fist",
  "skill.fist_master.1.blurb": "One fist into a single target, with everything behind it.",
  "skill.guardian.0": "Shield Bash",
  "skill.guardian.0.blurb": "Slams the monster ahead with your shield and stuns it for a long while.",
  "skill.guardian.1": "Rallying Cry",
  "skill.guardian.1.blurb": "A shout that strikes everything around you and gives health back to everyone near you.",
  "skill.tracker.0": "Snare Shot",
  "skill.tracker.0.blurb": "Hits one target and pins it where it stands.",
  "skill.tracker.1": "Fan of Arrows",
  "skill.tracker.1.blurb": "Pours arrows over a wide stretch ahead of you.",
  "skill.warder.0": "Ward Pulse",
  "skill.warder.0.blurb": "Spreads a ward that strikes everything around you and holds it for a moment.",
  "skill.warder.1": "Sanctuary",
  "skill.warder.1.blurb": "Gives much of their health back to you and the people near you.",
  "skill.high_priest.0": "Purifying Light",
  "skill.high_priest.0.blurb": "A beam that burns one target and gives a little health back to everyone near you.",
  "skill.paladin.1": "Hammer of Judgment",
  "skill.paladin.1.blurb": "Brings a hammer of light down and stuns everything around you.",
  "skill.scout.0": "Smoke Screen",
  "skill.scout.0.blurb": "Bursts a cloud of smoke that stops the monsters around you for a moment.",
  "skill.scout.1": "Knife Volley",
  "skill.scout.1.blurb": "Throws a fan of daggers a long way ahead.",
  "skill.iron_monk.0": "Iron Shoulder",
  "skill.iron_monk.0.blurb": "Rams ahead with your shoulder and stuns a wide stretch.",
  "skill.iron_monk.1": "Diamond Body",
  "skill.iron_monk.1.blurb": "Bursts with inner strength, striking all around and healing everyone near you.",
  "class.paths": "Advancing at Lv {n} · one of two",
  "skills.pathSlot": "Path skill {n}",
  "skills.afterAdvance": "Learned on advancing at Lv {n}",

  "job.berserker": "Berserker",
  "job.guardian": "Guardian",
  "job.sniper": "Sniper",
  "job.tracker": "Forest Tracker",
  "job.elementalist": "Elementalist",
  "job.warder": "Warder",
  "job.high_priest": "High Priest",
  "job.paladin": "Paladin",
  "job.assassin": "Assassin",
  "job.scout": "Scout",
  "job.fist_master": "Fist Master",
  "job.iron_monk": "Iron Monk",

  "item.heal": "Restores {n} health",
  "item.potion_small": "Small Potion",
  "item.potion_big": "Large Potion",
  "item.weapon_1": "Apprentice's Weapon",
  "item.weapon_2": "Forest Warden's Weapon",
  "item.weapon_3": "Mushroom King's Weapon",
  "item.weapon_4": "Steel Weapon",
  "item.weapon_5": "Stoneheart Weapon",
  "item.armor_1": "Leather Armour",
  "item.armor_2": "Forest Warden's Armour",
  "item.armor_3": "Mushroom King's Armour",
  "item.armor_4": "Steel Armour",
  "item.armor_5": "Stoneheart Armour",
  "item.stone": "Whetstone",
  "item.stone.blurb": "For enhancing gear. Every hunting field.",
  "item.jelly": "Slime Jelly",
  "item.jelly.blurb": "Crafting material. Forest Field 1.",
  "item.silk": "Spider Silk",
  "item.silk.blurb": "Crafting material. Forest Field 2.",
  "item.core": "Stoneheart Core",
  "item.core.blurb": "Crafting material. The Deep Forest.",
  "item.spore": "Mushroom King's Spore",
  "item.spore.blurb": "Crafting material. The Mushroom King.",

  "monster.green_blob": "Green Slime",
  "monster.mushnub": "Mushnub",
  "monster.rat": "Field Rat",
  "monster.frog": "Frog",
  "monster.spider": "Forest Spider",
  "monster.snake": "Viper",
  "monster.wasp": "Wasp",
  "monster.bat": "Bat",
  "monster.goleling": "Goleling",
  "monster.dire_spider": "Dire Spider",
  "monster.venom_snake": "Venom Viper",
  "monster.hornet": "Giant Hornet",
  "monster.vampire_bat": "Vampire Bat",
  "monster.stone_golem": "Stone Golem",
  "monster.mushnub_guard": "Mushnub Guard",
  "monster.mushroom_king": "Mushroom King",
  "monster.grove_guardian": "Grove Guardian",
  "monster.guild_dragon": "Ancient Dragon",
  "monster.guild_yeti": "Snowpeak Yeti",
  "monster.guild_glub": "Elder Glub",
  "monster.glub_brood": "Glub Spawn",

  "zone.village": "Grove Village",
  "zone.forest1": "Forest Field 1",
  "zone.forest2": "Forest Field 2",
  "zone.forest3": "Deep Forest",
  "zone.boss": "The Mushroom King's Clearing",
  "zone.arena": "Guild boss arena",

  "npc.merchant": "Hans the Merchant",
  "npc.merchant.role": "Shop",
  "npc.elder": "Elder Marta",
  "npc.elder.role": "Quests",
  "npc.smith": "Wolf the Smith",
  "npc.smith.role": "Forge & craft",

  "world.name": "Grove",

  "quest.0": "Slime Cull",
  "quest.0.goal": "15 Green Slimes in Forest Field 1",
  "quest.1": "Clearing the Mushnubs",
  "quest.1.goal": "20 Mushnubs in Forest Field 1",
  "quest.2": "Pests of the Meadow",
  "quest.2.goal": "40 Field Rats or Frogs",
  "quest.3": "Scouting the Deeper Wood",
  "quest.3.goal": "50 Forest Spiders or Vipers in Forest Field 2",
  "quest.4": "Hunting the Sky",
  "quest.4.goal": "60 Wasps or Bats",
  "quest.5": "Spirits of Stone",
  "quest.5.goal": "60 Golelings",
  "quest.6": "Felling the Mushroom King",
  "quest.6.goal": "The Mushroom King, in his clearing",
  "quest.7": "The Spider Den",
  "quest.7.goal": "60 Dire Spiders or Venom Vipers in the Deep Forest",
  "quest.8": "Wings Over the Wood",
  "quest.8.goal": "80 Giant Hornets or Vampire Bats",
  "quest.9": "The Forest's Wardstone",
  "quest.9.goal": "60 Stone Golems",
  "quest.10": "The Golem's Heart",
  "quest.10.goal": "100 Stone Golems",
  "quest.11": "The King Again",
  "quest.11.goal": "Fell the Mushroom King three times",
  "quest.12": "Master of the Deep Forest",
  "quest.12.goal": "200 monsters in the Deep Forest",
  "daily.forest1": "Patrol: Forest Field 1",
  "daily.forest1.goal": "30 monsters in Forest Field 1",
  "daily.forest2": "Patrol: Forest Field 2",
  "daily.forest2.goal": "40 monsters in Forest Field 2",
  "daily.forest3": "Patrol: the Deep Forest",
  "daily.forest3.goal": "50 monsters in the Deep Forest",

  "common.loading": "Loading…",
  "common.gold": "{n} gold",
  "common.nothing": "None",
  "problem.unavailable": "That cannot be done right now",
  "problem.max_plus": "It cannot be enhanced any further",
  "problem.not_near": "Stand by the smith to do that",
  "problem.not_enough_gold": "Not enough gold",
  "problem.not_in_village": "The shop is in the village",
  "problem.no_item": "It is not in your bag",
  "problem.bag_full": "Your bag can't hold more (99 per stack)",
  "problem.too_low_advance": "Advancement opens at Lv {n}",

  "slot.weapon": "Weapon",
  "slot.armor": "Armour",

  "bag.title": "Bag",
  "bag.power": "Power {n}",
  "bag.job": "Path",
  "bag.advanceAt": "You may advance at Lv {at} (you are Lv {level})",
  "bag.pickPath": "Choose a path. Once chosen it cannot be changed.",
  "bag.confirmPath": "Advance as {name}? It can't be changed later.",
  "bag.advanceGo": "Advance",
  "bag.unequip": "Take off",
  "bag.empty": "Your bag is empty",
  "bag.pickHint": "Pick an item to see what it is and what to do with it.",
  "bag.drink": "Drink",
  "bag.equip": "Wear",
  "bag.sell": "Sell ({n})",
  "bag.keys": "Q: drink a potion · I: bag",
  "item.trade": "Tradable",
  "item.bound": "Not tradable",
  "forge.tradeChance": "Gear made here is tradable {pct} of the time.",

  "shop.title": "Village Shop",
  "shop.buy": "Buy",
  "shop.buyTen": "Ten",
  "shop.note": "Monsters drop gold and gear. Selling is done from your bag.",

  "forge.title": "Forge",
  "forge.stones": "{n} whetstones",
  "forge.enhance": "Enhance",
  "forge.craft": "Craft",
  "forge.noGear": "You are wearing nothing to enhance",
  "forge.chance": "+{to}, {pct} to succeed",
  "forge.breakRisk": "{pct} to break on failure",
  "forge.maxed": "Fully enhanced (+{n})",
  "forge.note": "From +{n} a failure can break the gear. Whetstones drop from monsters in every hunting field.",
  "forge.success": "Enhanced!",
  "forge.fail": "It failed… the gear is unharmed",
  "forge.broken": "It failed… the gear broke",
  "forge.working": "Enhancing…",
  "forge.crafted": "{name} made!",

  "common.retry": "Try again",
  "common.toMenu": "To the menu",
  "common.menu": "Menu",
  "common.off2": "Off",

  "problem.not_owned": "This field opens with the full game",
  "problem.zone_full": "Every channel is full. Try again in a moment",
  "problem.not_near_portal": "Stand by the portal",
  "problem.too_low": "Your level is too low",
  "problem.cannotTravel": "You cannot go there right now",
  "problem.enter": "You could not get into the world",
  "problem.enterWith": "You could not get into the world ({error})",
  "problem.connect": "Could not reach the game server. Check your network and try again.",
  "problem.tooFast": "Say it a little slower",
  "problem.cannotSend": "That could not be sent",

  "world.entering": "Entering the world…",
  "world.loading": "Loading the forest… {n}%",
  "world.travelling": "Travelling…",
  "world.channel": "Channel {n}",
  "world.talk": "{name} — {role} · talk (E)",
  "world.portalLocked": "{zone} — opens with the full game {how}",
  "world.portalLocked.tap": "· tap to see",
  "world.portalLevel": "{zone} — open from Lv {n}",
  "world.portalTo": "The way to {zone}",
  "world.blocking": "Guarding",

  "menu.map": "Map",
  "menu.upgrade": "Full game",
  "menu.ranking": "Ranking",
  "menu.quests": "Quests",
  "menu.skills": "Skills",
  "menu.forge": "Forge",
  "menu.bag": "Bag",
  "menu.sleep": "Power save",
  "menu.news": "News",
  "news.title": "Update news",
  "menu.mail": "Mail",
  "mail.title": "Mailbox",
  "mail.empty": "No mail",
  "mail.failed": "Could not open the mailbox",
  "mail.claim": "Take",
  "mail.claimAll": "Take all",
  "mail.daysLeft": "{n} days left",
  "mail.gift": "Gift",
  "mail.gold": "{n} gold",
  "problem.no_mail": "That letter was already taken or is gone",
  "menu.market": "Market",
  "market.title": "Market",
  "market.buy": "Buy",
  "market.sell": "Sell",
  "market.mine": "My listings",
  "market.weapon": "Weapons",
  "market.armor": "Armour",
  "market.material": "Materials",
  "market.all": "All",
  "market.minPlus": "+{n} or more",
  "market.empty": "Nothing listed",
  "market.failed": "Could not open the market",
  "market.left": "{h}h {m}m left",
  "market.leftMin": "{m}m left",
  "market.buyGo": "Buy",
  "market.mineTag": "Yours",
  "market.confirm": "Buy {name} for {price} gems? It will arrive by mail.",
  "market.bought": "Bought! Take it from your mailbox.",
  "market.page": "{n} / {of}",
  "market.perOne": "{n} each",
  "market.nothingToSell": "Nothing tradable. Materials monsters drop are tradable, and so is some gear from drops and the forge.",
  "market.pick": "Pick something to sell",
  "market.price": "Price (gems)",
  "market.count": "Count",
  "market.fee": "Fee {fee} · you get {gets}",
  "market.list": "List",
  "market.listed": "Listed",
  "market.limit": "Listed {n}/{max}",
  "market.cancel": "Take down",
  "market.canceled": "Taken down. It will come back by mail.",
  "market.minPrice": "At least {n} gems",
  "market.none": "You have nothing listed",
  "market.ended": "Time is up (coming back by mail)",
  "market.note": "What sells is paid in gems by mail, less a 5% fee. Listings come down after 48 hours and return by mail.",
  "problem.listing_gone": "That listing was already sold or taken down",
  "problem.listing_limit": "You can list up to {n} at once",
  "problem.bad_price": "Check the price again",
  "problem.not_tradable": "That cannot be traded",
  "problem.own_listing": "You cannot buy your own listing",
  "menu.guild": "Guild",
  "guild.title": "Guild",
  "guild.find": "Find a guild",
  "guild.search": "Guild name",
  "guild.searchGo": "Search",
  "guild.none": "No guilds",
  "guild.count": "{n}/{max}",
  "guild.apply": "Apply",
  "guild.applied": "Applied",
  "guild.myApplications": "My applications",
  "guild.withdraw": "Withdraw",
  "guild.create": "Found a guild",
  "guild.createCost": "{n} gold",
  "guild.createGo": "Found",
  "guild.wait": "You can join or found a guild from {time}",
  "guild.notice": "Notice",
  "guild.noNotice": "No notice",
  "guild.editNotice": "Edit",
  "guild.saveNotice": "Save",
  "guild.members": "Members {n}/{max}",
  "guild.role.master": "Master",
  "guild.role.vice": "Vice",
  "guild.role.member": "Member",
  "guild.offline": "Offline",
  "guild.applicants": "Applications",
  "guild.accept": "Accept",
  "guild.decline": "Decline",
  "guild.kick": "Kick",
  "guild.makeVice": "Make vice",
  "guild.makeMember": "Make member",
  "guild.pass": "Hand over",
  "guild.confirmKick": "Kick {name}?",
  "guild.confirmPass": "Hand the guild to {name}? You become a member.",
  "guild.leave": "Leave",
  "guild.confirmLeave": "Leave the guild? You cannot join another for 24 hours.",
  "guild.disband": "Disband",
  "guild.confirmDisband": "Disband the guild? This cannot be undone.",
  "guild.yes": "Yes",
  "guild.failed": "Could not load the guild",
  "guild.rules": "Guilds are shared by every server. Each character can be in one guild.",
  "chat.channel": "Channel",
  "chat.guild": "Guild",
  "problem.guild_name_invalid": "Guild names are 2–12 letters, numbers or _",
  "problem.guild_name_taken": "That guild name is taken",
  "problem.in_guild": "You are already in a guild",
  "problem.no_guild": "No guild",
  "problem.guild_full": "The guild is full",
  "problem.guild_wait": "24 hours must pass after leaving a guild",
  "problem.applied_limit": "You can apply to 3 guilds at a time",
  "problem.applicants_full": "That guild cannot take more applications",
  "problem.no_applicant": "That application was already handled, or they joined another guild",
  "problem.not_allowed": "You are not allowed to do that",
  "problem.vice_limit": "A guild has at most 3 vices",
  "problem.master_must_pass": "The master must hand the guild over first",
  "problem.guild_not_empty": "A guild with members cannot be disbanded",
  "guild.tab.members": "Guild",
  "guild.tab.boss": "Boss",
  "boss.guild_dragon": "Ancient Dragon",
  "boss.guild_yeti": "Snowpeak Yeti",
  "boss.guild_glub": "Elder Glub",
  "boss.week": "This week's boss",
  "boss.left": "{n}% health left",
  "boss.down": "Slain! Wait for next week's boss",
  "boss.endsAt": "Until {time}",
  "boss.today": "Done for today (you can go in again tomorrow)",
  "boss.ready": "You can fight today · 3 min · Lv10+",
  "boss.room": "Room {n}",
  "boss.seats": "{n}/{max}",
  "boss.enter": "Enter",
  "boss.ranking": "Damage",
  "boss.mine": "Your damage this week {n}",
  "boss.noRanking": "No one has fought it yet",
  "boss.stages": "At 25, 50 and 75% and when it falls, everyone who fought this week gets mail. It drops tradable gear when slain (the best for the top 3).",
  "boss.hint": "When red marks appear on the ground, step out!",
  "boss.leave": "Leave",
  "boss.timeUp": "Your 3 minutes are up",
  "boss.fallen": "You fell",
  "boss.endNote": "Your damage counts toward the guild boss. Try again tomorrow!",
  "boss.slain": "The boss is slain!",
  "mail.guildBoss": "Guild boss stage {stage} reward",
  "mail.guildBossBody": "{boss} is down {pct}%. Thanks for fighting together!",
  "mail.guildBossSlain": "{boss} is slain! Here is the reward.",
  "problem.boss_down": "This week's boss is already slain",
  "problem.entered_today": "You already fought today",
  "problem.room_full": "That room is full",
  "problem.arena_over": "Your time is up",
  "mail.marketSold": "Sold: {item}",
  "mail.marketSoldBody": "Sold for {price} gems. Here are the gems, less a {fee}-gem fee.",
  "mail.marketBought": "Bought: {item}",
  "mail.marketBoughtBody": "Bought for {price} gems.",
  "mail.marketReturned": "Returned: {item}",
  "mail.marketReturnedBody": "It did not sell, or you took it down.",
  "menu.settings": "Settings",

  "death.fallen": "You fell",
  "death.lostXp": "You lost {n} XP",
  "death.lostNone": "No experience lost",
  "death.lossNote": "Falling costs {n}% of this level's XP (you never lose a level)",
  "death.here": "Get up here · {gold}",
  "death.hereNote": "You stand with {n}% health, and monsters leave you be for a moment",
  "death.short": " · not enough gold",
  "death.village": "Wake in the village · free",

  "sleep.title": "Power saving",
  "sleep.elapsed": "Time",
  "sleep.xp": "XP earned",
  "sleep.gold": "Gold earned",
  "sleep.potions": "Potions left",
  "sleep.potionCount": "{n}",
  "sleep.auto": "Auto-battle",
  "sleep.hunting": "Hunting",
  "sleep.dead": "You fell — tap twice to see",
  "sleep.hint": "Tap the screen twice to go back",

  "chat.placeholder": "Say something to the channel",
  "chat.open": "Chat",
  "chat.enterHint": "to chat",
  "lobby.deleteCharacter": "Delete {name}",
  "delete.title": "Delete character",
  "delete.warning": "Everything '{name}' has earned (levels, gear, quests) goes for good. Type the name to delete it.",
  "delete.confirm": "Delete for good",
  "problem.name_mismatch": "That is not the name",

  "quest.allDone": "Every quest done",
  "quest.reportHere": "Tap to report to the elder",
  "quest.reportInVillage": "Tap to head to the village elder",
  "quest.seeking": "On the way…",
  "quest.goFind": "Tap to go there",

  "pad.attack": "Attack",
  "pad.block": "Guard",
  "pad.jump": "Jump",
  "pad.auto": "Auto",
  "pad.autoOn": "Auto on",
  "pad.leftClick": "Left click",
  "pad.rightClick": "Right click",

  "map.tapToWalk": "Tap to walk there",
  "map.portals": "Ways out",
  "map.villagers": "Villagers",
  "map.you": "You",
  "map.close": "Close (N)",

  "bar.potion": "Potion",
  "bar.emptySlot": "Empty",
  "bar.autoPotion": "Auto potion",
  "bar.autoPotionTitle": "Auto potion settings",
  "bar.autoPotionAt": "Drinks a potion at {n}% health or less",
  "bar.autoPotionOff": " (off right now)",
  "bar.autoPotionTurnOn": "Turn auto potion on",
  "bar.autoPotionTurnOff": "Turn auto potion off",

  "skills.title": "Skills",
  "skills.dragNote": "Drag a skill you have learned into a slot below.",
  "skills.learnAt": "Learned at Lv {n}",
  "skills.fromElder": "Learn from the elder",
  "skills.inSlot": "Slot {n}",
  "skills.dragIn": "Drag into a slot",
  "skills.cooldown": "{n}s cooldown",
  "skills.remove": "Take out",

  "common.next": "Next",
  "common.accept": "Accept",
  "common.decline": "Decline",

  "lobby.newCharacter": "New character",
  "lobby.needServer": "The game needs a connection to Verse8 before it can start.",
  "lobby.accountFailed": "Your account could not be read. Please refresh.",
  "lobby.accountLoading": "Reading your account…",
  "lobby.loading": "Loading the village… {n}%",
  "lobby.tapToStart": "Tap the screen to start",
  "lobby.friends": "Friends",
  "lobby.characters": "{world} · {n}/{max} characters",
  "lobby.createCharacter": "+ New character",
  "lobby.start": "Play",
  "lobby.changeServer": "Change server",
  "lobby.noCharacter": "Make a character and begin.",
  "lobby.freeNote": "The village and Forest Field 1 are free to play.",
  "lobby.guestNote": "You are not signed in. A character made now cannot be loaded next time. Sign in to Verse8 before you start.",

  "buy.buy": "Buy the full game ({price} VX)",
  "buy.confirming": "Confirming the purchase…",
  "buy.late": "The purchase is taking a while to confirm. Please refresh in a moment.",
  "buy.title": "The full game",
  "buy.short": "Buy the full game",
  "buy.checking": "Confirming…",
  "buy.noServer": "It cannot be bought right now. Try again once you are connected.",
  "buy.reason.portal": "The way to {zone} opens with the full game.",
  "buy.reason.level": "Lv {n}! This is as far as the free fields go.",
  "buy.reason.menu": "The village and Forest Field 1 are free, up to Lv {n}.",
  "buy.fields": "{n} new hunting fields",
  "buy.noCap": "No level cap",
  "buy.noCapNote": "Past Lv {n}, on to both of your path's skills (Lv {third})",
  "buy.bossNote": "A boss that slams and calls its brood, and the gear it drops",
  "buy.classes": "{n} classes",
  "buy.off": "{n}% off",

  "class.pick": "Choose a class",
  "class.weapon": "Weapon",
  "class.ranged": "ranged",
  "class.melee": "melee",
  "class.damage": "Damage",
  "class.speed": "Attack speed",
  "class.perSecond": "{n}/s",
  "class.reach": "Reach",
  "class.block": "Guard",
  "class.skillLine": "Skill {n} · {name}",
  "class.lockedNote": "A full-game class. Free play offers the warrior and the ranger.",
  "class.confirm": "Take this class",
  "class.onceNote": "A class is chosen once, when the character is made.",
  "class.pickHint": "Tap a hero to look them over.",

  "look.title": "How they look",
  "look.spin": "Drag to turn them round",
  "look.shape": "Look",
  "look.random": "Surprise me",
  "look.making": "Making…",
  "look.create": "Make the character",
  "look.onceNote": "How they look cannot be changed once they are made.",
  "look.previous": "{part}, previous",
  "look.next": "{part}, next",

  "part.gear": "Trim",
  "part.clothColor": "Cloth",
  "part.skin": "Skin",
  "part.weaponColor": "Weapon",
  "look.default": "Plain",
  "look.on": "Worn",
  "look.off": "None",
  "look.grey": "Grey",
  "look.dye": "Dye {n}",
  "look.skinLight": "Fair",
  "look.skinTan": "Tan",
  "look.skinDark": "Deep",
  "look.mine": "My own look",
  "look.preset.light": "Travelling light",
  "look.preset.shadow": "Shadow",

  "name.title": "Their name",
  "name.note": "Other players and your friends will see you by this name. Two to twelve letters, digits or _ — and no two characters may share one.",
  "name.placeholder": "Name",
  "name.checking": "Checking…",

  "server.pick": "Choose a server",
  "server.note": "You meet the players who chose the same one. Pick the server your friends are on.",
  "server.entering": "Entering…",
  "server.recent": "Last played",
  "server.failed": "The server could not be chosen. Try again in a moment",

  "common.add": "Add",
  "common.cancel": "Cancel",
  "common.remove": "Remove",
  "common.removeSure": "Really remove",
  "common.noName": "(no name)",
  "common.reward": "Reward: {what}",
  "common.xp": "{n} XP",

  "friends.title": "Friends",
  "friends.needCharacter": "Make a character before adding friends.",
  "friends.search": "Add a friend by name",
  "friends.needServer": "Friends open once you are connected to Verse8.",
  "friends.loading": "Reading your friends…",
  "friends.sent": "Your request was sent",
  "friends.bothWays": "You both asked, so you are friends already",
  "friends.nowFriends": "You and {name} are friends now",
  "friends.incoming": "Requests received {n}",
  "friends.list": "Friends",
  "friends.online": "· {on}/{all} online",
  "friends.none": "No friends yet. Add one by name.",
  "friends.isOnline": "online",
  "friends.isOffline": "offline",
  "friends.outgoing": "Requests sent",
  "friends.waiting": "waiting",

  "problem.friend_not_found": "No one goes by that name",
  "problem.friend_self": "You cannot add yourself",
  "problem.already_friends": "You are friends already",
  "problem.friend_limit": "You may keep {n} friends",
  "problem.request_limit": "They have too many requests waiting",
  "problem.no_request": "That request has already been answered",
  "problem.nickname_taken": "That name is taken",
  "problem.nickname_invalid": "Two to twelve letters, digits or _",
  "problem.character_limit": "You cannot make another character on this server",
  "problem.retryLater": "That cannot be done right now. Try again in a moment",
  "problem.saveFailed": "It could not be saved. Try again in a moment",
  "problem.not_near_elder": "Stand by the elder to speak with her",
  "problem.quest_unfinished": "It is not finished yet",
  "problem.cannotClaim": "It cannot be claimed right now",

  "rank.title": "Ranking",
  "rank.needServer": "It opens once you are connected to Verse8.",
  "rank.failed": "The ranking could not be read. Try opening it again in a moment.",
  "rank.none": "No adventurer has earned any experience yet.",
  "rank.unranked": "unranked",
  "rank.place": "#{n}",
  "rank.nickname": "Name",
  "rank.class": "Class",
  "rank.level": "Level",
  "rank.rank": "Place",
  "rank.server": "Server",
  "rank.xp": "Experience",
  "rank.power": "Power",
  "rank.detailFailed": "That could not be read.",
  "rank.toList": "Back to the list",

  "quests.title": "Quests",
  "quests.daily": "Daily quests · they begin again at midnight",
  "quests.claim": "Claim",
  "quests.claimedToday": "Claimed today",
  "quests.goReport": "Go and report to the elder",
  "quests.reportHint": "Report to the elder in the village to be paid",
  "quests.goFind": "Go there",
  "quests.allDone": "Every quest is done.",
  "quests.past": "Quests done",
  "quests.more": "{n} more quests to come.",
  "quests.complete": "Quest complete!",
  "quests.reportHere": "Report to the elder to be paid",
  "quests.reportInVillage": "Report to the elder in the village to be paid",
  "npc.merchant.hello": "\"Welcome! Potions, gear, all you need.\"",
  "npc.smith.hello": "\"Strike while the iron's hot. Enhancing or crafting, leave it to me.\"",
  "dialogue.shop": "Browse the shop",
  "dialogue.forge": "Open the forge",
  "npc.elder.done": "\"Nothing in this forest is a match for you now. Thank you, hunter.\"",
  "npc.elder.tutorial": "\"There you are. Take this skill, and these potions. Open the skill panel to see it: on a slot below, it is ready to use.\"",
  "npc.elder.claim": "\"{quest} — well done! Here is what I promised.\"",
  "npc.elder.ask": "\"{goal}, if you would.\"",

  "note.notHere": "None of those are in this field",
  "note.questPaid": "{zone}: open in the full game",
  "note.questLevel": "{zone}: open from Lv {n}",
  "note.cannotWalk": "You cannot go there",
  "note.gotGold": "+{n} gold",
  "note.gotItem": "{name} picked up",
  "portal.needsFull": " (full game)",
  "portal.needsLevel": " (Lv {n})",

  "error.startFailed": "The game could not start.",
  "error.reload": "Load it again",
  "rotate.hint": "Turn your screen sideways for a better view",
  "channel.title": "Channels",
  "channel.note": "On the same channel you can always meet, in any zone. Moving keeps you where you stand.",
  "channel.here": "You are here",
  "channel.full": "Full",
  "channel.friends": "Friends: {names}",
  "keys.channel": "Change channel",
  "problem.channel_full": "That channel is full. Pick another one",
  "friends.where": "{server} · {channel} · {zone}",
  "common.prevPage": "Previous page",
  "common.nextPage": "Next page",
  "friends.noIncoming": "No requests waiting.",
  "friends.noOutgoing": "No requests sent.",
  "quests.tabNow": "Current",
  "quests.tabDaily": "Daily",
  "quests.tabPast": "Done",
  "quests.noPast": "No quests done yet.",

  "tutorial.title": "First Steps",
  "tutorial.step0": "Talk to the elder",
  "tutorial.step1": "Open the skill panel and drag your new skill onto slot 1",
  "tutorial.step1Placed": "Open the skill panel to see your new skill. It's already in slot 1",
  "tutorial.step2": "Drag the skill slot and the potion slot down to let them auto-use",
  "tutorial.step3": "Press the auto-battle button",
  "tutorial.doneTitle": "All set!",
  "tutorial.doneHint": "See the elder's first request",

  "menu.grove": "Grove",
  "grove.title": "Grove Purification",
  "grove.kills": "This week {n} / {goal}",
  "grove.daysLeft": "{n} days left",
  "grove.stage.1": "30% Flowers bloom, 200 gold",
  "grove.stage.2": "60% Clear skies, a site opens",
  "grove.stage.3": "100% The Guardian (ch. 1), 500 gold",
  "grove.hazeHint": "Hunting purifies the grove.\nAt 60% the haze lifts (this week {n}%)",
  "grove.village": "Village Rebuilding",
  "grove.building.herbalist": "Herbalist",
  "grove.building.training": "Training Ground",
  "grove.building.inn": "Inn",
  "grove.building.watchtower": "Watchtower",
  "grove.perk.herbalist": "Potions 20% off",
  "grove.perk.training": "Hunting XP +5%",
  "grove.perk.inn": "Half the XP lost on falling",
  "grove.perk.watchtower": "Bosses on the minimap",
  "grove.closed": "Not open",
  "grove.building": "Building {n}%",
  "grove.done": "Built",
  "grove.failed": "Could not load",
  "dialogue.donate": "Donate",
  "donate.title": "Build the {building}",
  "donate.have": "You have {n}",
  "donate.gold": "Gold",
  "donate.done": "Thank you! Your name will be remembered.",
  "problem.nothing": "Choose something to give",
  "problem.no_building": "Nothing is being built",
  "keys.ride": "Mount up / get off",
  "menu.mounts": "Mounts",
  "pad.ride": "Ride",
  "pad.dismount": "Get off",
  "problem.not_enough_gems": "Not enough gems",
  "problem.no_mount": "You do not have that mount",
  "mount.none": "No mount to ride. The full game comes with a deer; hatch eggs for more.",
  "mount.rideHint": "T or the ride button gets you on and off. Attacking or being hit takes you off.",
  "mount.stats": "Attack +{p}% · Health +{h}",
  "mount.statsNote": "Your picked mount raises your attack and health, ridden or not.",
  "mount.speed": "Speed ×{n}",
  "mount.riding": "Riding",
  "mount.pick": "Ride this",
  "mount.fullGame": "With the full game",
  "mount.notOwned": "Not owned",
  "mount.baseNote": "The full game comes with a {name} to ride.",
  "mount.new": "New mount! {tier} {name}",
  "mount.newBadge": "New mount!",
  "mount.repeatBadge": "Already yours",
  "mount.nextStar": "Next ★{n}: power +{p}% · health +{h}",
  "mount.star": "{name} broke through to ★{n}! Its bonus grew",
  "mount.starBadge": "Breakthrough!",
  "mount.repeat": "Already had the {name} · {n} gems back",
  "mount.odds": "Draw odds",
  "mount.repeatNote": "A mount you already own breaks through: a star more and a bigger bonus (up to ★{max}, which doubles it). Past ★{max} it comes back as {n} gems.",
  "mount.pack": "{n} gems",
  "mount.gemsComing": "Confirming the purchase…",
  "mount.stable": "Stable",
  "mount.tab.stable": "My mounts",
  "mount.tab.hatch": "Hatch an egg",
  "mount.tab.shop": "Gem shop",
  "mount.gemsTitle": "Your gems",
  "mount.hatchLede": "One egg, one mount. Higher tiers run faster.",
  "mount.hatch": "Hatch",
  "mount.needGems": "Not enough gems · to the gem shop",
  "mount.shopLede": "Gems hatch eggs. They belong to your account, shared by every character.",
  "mount.bonus": "+{n}% bonus",
  "mount.shopNote": "Paid in VX. The gems arrive shortly after payment.",
  "mount.tier.base": "Basic",
  "mount.tier.common": "Common",
  "mount.tier.rare": "Rare",
  "mount.tier.epic": "Epic",
  "mount.tier.legendary": "Legendary",
  "mount.name.deer": "Deer",
  "mount.name.pig": "Pig",
  "mount.name.chicken": "Chicken",
  "mount.name.penguin": "Penguin",
  "mount.name.panda": "Panda",
  "mount.name.crab": "Crab",
  "mount.name.yeti": "Yeti",
  "mount.name.drake": "Drake",
  "mount.name.cat": "Cat",
  "mount.name.dog": "Dog",
  "mount.name.pigeon": "Pigeon",
  "mount.name.armabee": "Armabee",
  "mount.name.glub": "Glub",
  "mount.name.squidle": "Squidle",
  "mount.name.hywirl": "Hywirl",
  "mount.name.alpaking": "Alpaking",
  "mount.name.queen_armabee": "Queen Armabee",
  "mount.name.elder_glub": "Elder Glub",
  "mount.name.alpaking_emperor": "Alpaking Emperor",
  "mount.name.dragon": "Dragon",
};
