import type { Bundle } from "./ko";

export const en: Bundle = {
  "common.close": "Close",
  "common.back": "Back",
  "common.on": "On",
  "common.off": "Off",
  "common.none": "Off",

  "settings.title": "Settings",
  "settings.sound": "Sound",
  "settings.music": "Music",
  "settings.effects": "Effects",
  "settings.controls": "Controls",
  "settings.sensitivity": "Mouse sensitivity",
  "settings.times": "{n}×",
  "settings.screen": "Screen",
  "settings.brightness": "Brightness",
  "settings.quality": "Graphics",
  "settings.quality.low": "Low",
  "settings.quality.mid": "Medium",
  "settings.quality.high": "High",
  "settings.quality.note": "Lower is lighter on your battery. It changes how far trees and grass are drawn in full, and the screen's resolution.",
  "settings.shown": "Shown",
  "settings.showNames": "Other players' names",
  "settings.damageNumbers": "Damage numbers",
  "settings.language": "Language",
  "settings.keys.show": "Show shortcuts",
  "settings.keys.hide": "Hide shortcuts",
  "settings.defaults": "Defaults",
  "settings.exit": "Back to the menu",

  "keys.move": "Move",
  "keys.jump": "Jump",
  "keys.click": "Left / right click",
  "keys.attackGuard": "Attack / guard",
  "keys.skills": "Skills",
  "keys.potion": "Potion",
  "keys.talk": "Talk",
  "keys.auto": "Auto-battle",
  "keys.quest": "Go to / report quest",
  "keys.chat": "Chat",
  "keys.menu": "Open the menu",
  "keys.closeWindow": "Close the window",
  "keys.map": "Map",
  "keys.panels": "Ranking / quests / skills / forge / bag",
  "keys.powerSave": "Power saving",
  "keys.settings": "Settings",

  "list.join": ", ",
  "stat.power": "Attack +{n}%",
  "stat.hp": "Health +{n}",
  "stat.guard": "Damage taken -{n}%",
  "stat.heal": "Healing +{n}%",

  "class.warrior": "Warrior",
  "class.ranger": "Ranger",
  "class.wizard": "Wizard",
  "class.cleric": "Cleric",
  "class.rogue": "Rogue",
  "class.monk": "Monk",
  "class.warrior.blurb": "Longsword and armour. Stands its ground and cuts.",
  "class.ranger.blurb": "Shoots from afar. Weak once something closes in.",
  "class.wizard.blurb": "Throws bolts from a staff. Slow, but reaches far.",
  "class.cleric.blurb": "Heals itself and the people beside it.",
  "class.rogue.blurb": "Stabs very fast with a dagger.",
  "class.monk.blurb": "Bare fists in a flurry, and blows that stun.",

  "weapon.warrior": "Longsword",
  "weapon.ranger": "Bow",
  "weapon.wizard": "Magic staff",
  "weapon.cleric": "Holy staff",
  "weapon.rogue": "Dagger",
  "weapon.monk": "Fists",

  "skill.warrior.0": "Whirl",
  "skill.warrior.0.blurb": "Spins once, cutting every monster around you.",
  "skill.warrior.1": "Charging Cut",
  "skill.warrior.1.blurb": "A wide cut ahead that knocks them down for a moment.",
  "skill.warrior.2": "Earthbreaker",
  "skill.warrior.2.blurb": "Strikes the ground and stuns everything around you.",
  "skill.ranger.0": "Piercing Arrow",
  "skill.ranger.0.blurb": "Flies straight ahead and runs through everything in line.",
  "skill.ranger.1": "Aimed Shot",
  "skill.ranger.1.blurb": "Takes one target and hits it hard.",
  "skill.ranger.2": "Arrow Rain",
  "skill.ranger.2.blurb": "Pours arrows down all around you.",
  "skill.wizard.0": "Flame Burst",
  "skill.wizard.0.blurb": "Covers the ground around you in fire.",
  "skill.wizard.1": "Ice Spear",
  "skill.wizard.1.blurb": "Runs one through and freezes it in place.",
  "skill.wizard.2": "Meteor",
  "skill.wizard.2.blurb": "Drops a ball of fire from the sky and burns the ground around you.",
  "skill.cleric.0": "Healing Light",
  "skill.cleric.0.blurb": "Gives health back to you and the people near you.",
  "skill.cleric.1": "Holy Strike",
  "skill.cleric.1.blurb": "Light along the staff, striking ahead and stunning.",
  "skill.cleric.2": "Blessing",
  "skill.cleric.2.blurb": "Burns the monsters around you and heals your party deeply.",
  "skill.rogue.0": "Shadow Strike",
  "skill.rogue.0.blurb": "One deep thrust into the monster ahead.",
  "skill.rogue.1": "Blade Fan",
  "skill.rogue.1.blurb": "Scatters daggers ahead of you.",
  "skill.rogue.2": "Shadow Flurry",
  "skill.rogue.2.blurb": "Whirls through everything around you.",
  "skill.monk.0": "Stunning Flurry",
  "skill.monk.0.blurb": "Pummels the monster ahead and stuns it for a while.",
  "skill.monk.1": "Whirlwind Kick",
  "skill.monk.1.blurb": "Spins and kicks everything around you.",
  "skill.monk.2": "White Fist",
  "skill.monk.2.blurb": "One fist into a single target, with everything behind it.",

  "job.berserker": "Berserker",
  "job.guardian": "Guardian",
  "job.sniper": "Sniper",
  "job.tracker": "Forest Tracker",
  "job.elementalist": "Elementalist",
  "job.warder": "Warder",
  "job.high_priest": "High Priest",
  "job.paladin": "Paladin",
  "job.assassin": "Assassin",
  "job.scout": "Scout",
  "job.fist_master": "Fist Master",
  "job.iron_monk": "Iron Monk",

  "item.heal": "Restores {n} health",
  "item.potion_small": "Small Potion",
  "item.potion_big": "Large Potion",
  "item.weapon_1": "Apprentice's Weapon",
  "item.weapon_2": "Forest Warden's Weapon",
  "item.weapon_3": "Mushroom King's Weapon",
  "item.weapon_4": "Steel Weapon",
  "item.weapon_5": "Stoneheart Weapon",
  "item.armor_1": "Leather Armour",
  "item.armor_2": "Forest Warden's Armour",
  "item.armor_3": "Mushroom King's Armour",
  "item.armor_4": "Steel Armour",
  "item.armor_5": "Stoneheart Armour",
  "item.stone": "Whetstone",
  "item.stone.blurb": "For enhancing gear. Every hunting field.",
  "item.jelly": "Slime Jelly",
  "item.jelly.blurb": "Crafting material. Forest Field 1.",
  "item.silk": "Spider Silk",
  "item.silk.blurb": "Crafting material. Forest Field 2.",
  "item.core": "Stoneheart Core",
  "item.core.blurb": "Crafting material. The Deep Forest.",
  "item.spore": "Mushroom King's Spore",
  "item.spore.blurb": "Crafting material. The Mushroom King.",

  "monster.green_blob": "Green Slime",
  "monster.mushnub": "Mushnub",
  "monster.rat": "Field Rat",
  "monster.frog": "Frog",
  "monster.spider": "Forest Spider",
  "monster.snake": "Viper",
  "monster.wasp": "Wasp",
  "monster.bat": "Bat",
  "monster.goleling": "Goleling",
  "monster.dire_spider": "Dire Spider",
  "monster.venom_snake": "Venom Viper",
  "monster.hornet": "Giant Hornet",
  "monster.vampire_bat": "Vampire Bat",
  "monster.stone_golem": "Stone Golem",
  "monster.mushnub_guard": "Mushnub Guard",
  "monster.mushroom_king": "Mushroom King",

  "zone.village": "Grove Village",
  "zone.forest1": "Forest Field 1",
  "zone.forest2": "Forest Field 2",
  "zone.forest3": "Deep Forest",
  "zone.boss": "The Mushroom King's Clearing",

  "npc.merchant": "Hans the Merchant",
  "npc.merchant.role": "Shop",
  "npc.elder": "Elder Marta",
  "npc.elder.role": "Quests",
  "npc.smith": "Wolf the Smith",
  "npc.smith.role": "Forge & craft",

  "world.name": "Grove",
};
