import type { Bundle } from "./ko";

export const en: Bundle = {
  "common.close": "Close",
  "common.back": "Back",
  "common.on": "On",
  "common.off": "Off",
  "common.none": "Off",

  "settings.title": "Settings",
  "settings.sound": "Sound",
  "settings.music": "Music",
  "settings.effects": "Effects",
  "settings.controls": "Controls",
  "settings.sensitivity": "Mouse sensitivity",
  "settings.times": "{n}×",
  "settings.screen": "Screen",
  "settings.brightness": "Brightness",
  "settings.quality": "Graphics",
  "settings.quality.low": "Low",
  "settings.quality.mid": "Medium",
  "settings.quality.high": "High",
  "settings.quality.note": "Lower is lighter on your battery. It changes how far trees and grass are drawn in full, and the screen's resolution.",
  "settings.shown": "Shown",
  "settings.showNames": "Other players' names",
  "settings.damageNumbers": "Damage numbers",
  "settings.language": "Language",
  "settings.keys.show": "Show shortcuts",
  "settings.keys.hide": "Hide shortcuts",
  "settings.defaults": "Defaults",
  "settings.exit": "Back to the menu",

  "keys.move": "Move",
  "keys.jump": "Jump",
  "keys.click": "Left / right click",
  "keys.attackGuard": "Attack / guard",
  "keys.skills": "Skills",
  "keys.potion": "Potion",
  "keys.talk": "Talk",
  "keys.auto": "Auto-battle",
  "keys.quest": "Go to / report quest",
  "keys.chat": "Chat",
  "keys.menu": "Open the menu",
  "keys.closeWindow": "Close the window",
  "keys.map": "Map",
  "keys.panels": "Ranking / quests / skills / forge / bag",
  "keys.powerSave": "Power saving",
  "keys.settings": "Settings",
};
