import type { Bundle } from "./ko";

export const ja: Bundle = {
  "common.close": "閉じる",
  "common.back": "戻る",
  "common.on": "オン",
  "common.off": "オフ",
  "common.none": "なし",

  "settings.title": "設定",
  "settings.sound": "サウンド",
  "settings.music": "BGM",
  "settings.effects": "効果音",
  "settings.controls": "操作",
  "settings.sensitivity": "マウス感度",
  "settings.times": "{n}倍",
  "settings.screen": "画面",
  "settings.brightness": "明るさ",
  "settings.quality": "グラフィック品質",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "低いほど軽く、バッテリーの消費も抑えられます。木や草を描く距離と画面の解像度が変わります。",
  "settings.shown": "表示",
  "settings.showNames": "他のプレイヤーの名前",
  "settings.damageNumbers": "ダメージ数値",
  "settings.language": "言語",
  "settings.keys.show": "ショートカットを見る",
  "settings.keys.hide": "ショートカットを閉じる",
  "settings.defaults": "初期設定",
  "settings.exit": "メニューに戻る",

  "keys.move": "移動",
  "keys.jump": "ジャンプ",
  "keys.click": "左クリック / 右クリック",
  "keys.attackGuard": "攻撃 / ガード",
  "keys.skills": "スキル",
  "keys.potion": "ポーション",
  "keys.talk": "会話",
  "keys.auto": "オート戦闘",
  "keys.quest": "クエストへ向かう・報告",
  "keys.chat": "チャット",
  "keys.menu": "メニューを開く",
  "keys.closeWindow": "ウィンドウを閉じる",
  "keys.map": "マップ",
  "keys.panels": "ランキング / クエスト / スキル / 鍛冶屋 / カバン",
  "keys.powerSave": "省電力モード",
  "keys.settings": "設定",
};
