import type { Bundle } from "./ko";

export const ja: Bundle = {
  "common.close": "閉じる",
  "common.back": "戻る",
  "common.on": "オン",
  "common.off": "オフ",
  "common.none": "なし",

  "settings.title": "設定",
  "settings.sound": "サウンド",
  "settings.music": "BGM",
  "settings.effects": "効果音",
  "settings.controls": "操作",
  "settings.sensitivity": "マウス感度",
  "settings.times": "{n}倍",
  "settings.screen": "画面",
  "settings.brightness": "明るさ",
  "settings.quality": "グラフィック品質",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "低いほど軽く、バッテリーの消費も抑えられます。木や草を描く距離と画面の解像度が変わります。",
  "settings.shown": "表示",
  "settings.showNames": "他のプレイヤーの名前",
  "settings.damageNumbers": "ダメージ数値",
  "settings.language": "言語",
  "settings.keysTab": "ショートカット",
  "settings.defaults": "初期設定",
  "settings.exit": "メニューに戻る",

  "keys.move": "移動",
  "keys.jump": "ジャンプ",
  "keys.click": "左クリック / 右クリック",
  "keys.attackGuard": "攻撃 / ガード",
  "keys.skills": "スキル",
  "keys.potion": "ポーション",
  "keys.talk": "会話",
  "keys.auto": "オート戦闘",
  "keys.quest": "クエストへ向かう・報告",
  "keys.chat": "チャット",
  "keys.menu": "メニューを開く",
  "keys.closeWindow": "ウィンドウを閉じる",
  "keys.map": "マップ",
  "keys.panels": "ランキング / クエスト / スキル / 鍛冶屋 / カバン",
  "keys.powerSave": "省電力モード",
  "keys.settings": "設定",

  "list.join": "、",
  "stat.power": "攻撃力 +{n}%",
  "stat.hp": "体力 +{n}",
  "stat.guard": "受けるダメージ -{n}%",
  "stat.heal": "回復量 +{n}%",

  "class.warrior": "戦士",
  "class.ranger": "アーチャー",
  "class.wizard": "魔法使い",
  "class.cleric": "プリースト",
  "class.rogue": "盗賊",
  "class.monk": "格闘家",
  "class.warrior.blurb": "長剣と鎧。前に立って斬り続ける。",
  "class.ranger.blurb": "遠くから弓で射る。近づかれると弱い。",
  "class.wizard.blurb": "杖から魔法弾を放つ。遅いが遠くまで届く。",
  "class.cleric.blurb": "仲間と自分を回復する。",
  "class.rogue.blurb": "短剣でとても速く突く。",
  "class.monk.blurb": "素手の連打と、気絶させる技。",

  "weapon.warrior": "長剣",
  "weapon.ranger": "弓",
  "weapon.wizard": "魔法の杖",
  "weapon.cleric": "聖職者の杖",
  "weapon.rogue": "短剣",
  "weapon.monk": "拳",

  "skill.warrior.0": "回転斬り",
  "skill.warrior.0.blurb": "一回転して周りのモンスターをまとめて斬る。",
  "skill.berserker.0": "突進斬り",
  "skill.berserker.0.blurb": "前方を大きく斬り、少しの間倒れさせる。",
  "skill.berserker.1": "大地強打",
  "skill.berserker.1.blurb": "地面を叩きつけ、周りをすべて気絶させる。",
  "skill.ranger.0": "貫通の矢",
  "skill.ranger.0.blurb": "まっすぐ飛び、並んだモンスターをすべて貫く。",
  "skill.sniper.0": "狙撃",
  "skill.sniper.0.blurb": "一体を狙って大きく当てる。",
  "skill.sniper.1": "矢の雨",
  "skill.sniper.1.blurb": "周りに矢を降らせる。",
  "skill.wizard.0": "火炎爆発",
  "skill.wizard.0.blurb": "周りを炎で覆い、モンスターを焼く。",
  "skill.elementalist.0": "氷の槍",
  "skill.elementalist.0.blurb": "一体を貫いて凍らせ、動けなくする。",
  "skill.elementalist.1": "隕石落下",
  "skill.elementalist.1.blurb": "空から火の玉を落として周りを焼く。",
  "skill.cleric.0": "癒しの光",
  "skill.cleric.0.blurb": "自分と近くの仲間の体力を回復する。",
  "skill.paladin.0": "神聖な一撃",
  "skill.paladin.0.blurb": "杖に光を乗せて前方を打ち、気絶させる。",
  "skill.high_priest.1": "祝福",
  "skill.high_priest.1.blurb": "周りのモンスターを焼き、仲間を大きく回復する。",
  "skill.rogue.0": "影の一撃",
  "skill.rogue.0.blurb": "前方のモンスター一体を深く突く。",
  "skill.assassin.0": "刃の扇",
  "skill.assassin.0.blurb": "前方に短剣をばらまく。",
  "skill.assassin.1": "影乱舞",
  "skill.assassin.1.blurb": "周りをかき回してすべて斬る。",
  "skill.monk.0": "気絶連打",
  "skill.monk.0.blurb": "前方のモンスターを叩き、しばらく気絶させる。",
  "skill.fist_master.0": "旋風脚",
  "skill.fist_master.0.blurb": "回し蹴りで周りをすべて打つ。",
  "skill.fist_master.1": "白熱拳",
  "skill.fist_master.1.blurb": "一体に全力の拳を叩き込む。",
  "skill.guardian.0": "シールドバッシュ",
  "skill.guardian.0.blurb": "前方の一体を盾で打ち、長く気絶させる。",
  "skill.guardian.1": "守護の雄叫び",
  "skill.guardian.1.blurb": "雄叫びで周りを打ち、自分と仲間の体力を回復する。",
  "skill.tracker.0": "罠の矢",
  "skill.tracker.0.blurb": "一体に当てて足を止める。",
  "skill.tracker.1": "扇射ち",
  "skill.tracker.1.blurb": "前方の広い範囲に矢を浴びせる。",
  "skill.warder.0": "結界波動",
  "skill.warder.0.blurb": "結界を広げて周りを打ち、しばらく動きを止める。",
  "skill.warder.1": "守護結界",
  "skill.warder.1.blurb": "自分と近くの仲間の体力を大きく回復する。",
  "skill.high_priest.0": "浄化の光",
  "skill.high_priest.0.blurb": "光の筋で一体を焼き、自分と仲間を少し回復する。",
  "skill.paladin.1": "裁きの鉄槌",
  "skill.paladin.1.blurb": "光の鉄槌を振り下ろし、周りをすべて気絶させる。",
  "skill.scout.0": "煙幕",
  "skill.scout.0.blurb": "煙幕を張り、周りのモンスターをしばらく止める。",
  "skill.scout.1": "投げナイフ",
  "skill.scout.1.blurb": "遠くまで短剣を扇状に投げる。",
  "skill.iron_monk.0": "鉄山靠",
  "skill.iron_monk.0.blurb": "肩で体当たりし、前方を広く気絶させる。",
  "skill.iron_monk.1": "金剛不壊",
  "skill.iron_monk.1.blurb": "気を放って周りを打ち、自分と仲間の体力を回復する。",
  "class.paths": "Lv{n}で転職・二つから一つ",
  "skills.pathSlot": "転職スキル {n}",
  "skills.afterAdvance": "Lv{n}で転職すると習得",

  "job.berserker": "バーサーカー",
  "job.guardian": "守護騎士",
  "job.sniper": "スナイパー",
  "job.tracker": "森の追跡者",
  "job.elementalist": "元素術士",
  "job.warder": "結界術士",
  "job.high_priest": "大司祭",
  "job.paladin": "聖騎士",
  "job.assassin": "アサシン",
  "job.scout": "斥候",
  "job.fist_master": "拳聖",
  "job.iron_monk": "鉄壁の修道士",

  "item.heal": "体力を{n}回復",
  "item.potion_small": "小さなポーション",
  "item.potion_big": "大きなポーション",
  "item.weapon_1": "見習いの武器",
  "item.weapon_2": "森守りの武器",
  "item.weapon_3": "キノコ王の武器",
  "item.weapon_4": "鋼の武器",
  "item.weapon_5": "岩心の武器",
  "item.armor_1": "革の鎧",
  "item.armor_2": "森守りの鎧",
  "item.armor_3": "キノコ王の鎧",
  "item.armor_4": "鋼の鎧",
  "item.armor_5": "岩心の鎧",
  "item.stone": "強化石",
  "item.stone.blurb": "装備強化の素材。すべての狩場。",
  "item.jelly": "スライムゼリー",
  "item.jelly.blurb": "製作素材。森フィールド1。",
  "item.silk": "蜘蛛の絹",
  "item.silk.blurb": "製作素材。森フィールド2。",
  "item.core": "岩の心臓石",
  "item.core.blurb": "製作素材。深い森。",
  "item.spore": "キノコ王の胞子",
  "item.spore.blurb": "製作素材。キノコ王。",

  "monster.green_blob": "緑スライム",
  "monster.mushnub": "キノコ坊や",
  "monster.rat": "野ネズミ",
  "monster.frog": "カエル",
  "monster.spider": "森グモ",
  "monster.snake": "毒ヘビ",
  "monster.wasp": "スズメバチ",
  "monster.bat": "コウモリ",
  "monster.goleling": "ゴーレムリング",
  "monster.dire_spider": "巨大毒グモ",
  "monster.venom_snake": "猛毒ヘビ",
  "monster.hornet": "オオスズメバチ",
  "monster.vampire_bat": "吸血コウモリ",
  "monster.stone_golem": "岩のゴーレム",
  "monster.mushnub_guard": "キノコ護衛兵",
  "monster.mushroom_king": "キノコ王",
  "monster.grove_guardian": "浄化の守護者",

  "zone.village": "みどり森の村",
  "zone.forest1": "森フィールド1",
  "zone.forest2": "森フィールド2",
  "zone.forest3": "深い森",
  "zone.boss": "キノコ王の広場",

  "npc.merchant": "商人ハンス",
  "npc.merchant.role": "ショップ",
  "npc.elder": "村長マルタ",
  "npc.elder.role": "クエスト",
  "npc.smith": "鍛冶屋ヴォルフ",
  "npc.smith.role": "強化・製作",

  "world.name": "みどり森",

  "quest.0": "スライム退治",
  "quest.0.goal": "森フィールド1の緑スライム15体",
  "quest.1": "キノコ坊や掃討",
  "quest.1.goal": "森フィールド1のキノコ坊や20体",
  "quest.2": "野原の厄介者",
  "quest.2.goal": "野ネズミかカエル40体",
  "quest.3": "深い森の偵察",
  "quest.3.goal": "森フィールド2の森グモか毒ヘビ50体",
  "quest.4": "空の狩り",
  "quest.4.goal": "スズメバチかコウモリ60体",
  "quest.5": "石の精霊",
  "quest.5.goal": "ゴーレムリング60体",
  "quest.6": "キノコ王討伐",
  "quest.6.goal": "キノコ王の広場のキノコ王",
  "quest.7": "深い森の蜘蛛の巣",
  "quest.7.goal": "深い森の巨大毒グモか猛毒ヘビ60体",
  "quest.8": "空を覆う翼",
  "quest.8.goal": "オオスズメバチか吸血コウモリ80体",
  "quest.9": "森の守護石",
  "quest.9.goal": "岩のゴーレム60体",
  "quest.10": "ゴーレムの心臓",
  "quest.10.goal": "岩のゴーレム100体",
  "quest.11": "キノコ王再討伐",
  "quest.11.goal": "キノコ王を3回倒す",
  "quest.12": "深い森の主",
  "quest.12.goal": "深い森のモンスター200体",
  "daily.forest1": "森フィールド1の巡回",
  "daily.forest1.goal": "森フィールド1のモンスター30体",
  "daily.forest2": "森フィールド2の巡回",
  "daily.forest2.goal": "森フィールド2のモンスター40体",
  "daily.forest3": "深い森の巡回",
  "daily.forest3.goal": "深い森のモンスター50体",

  "common.loading": "読み込み中…",
  "common.gold": "{n} ゴールド",
  "common.nothing": "なし",
  "problem.unavailable": "今はできません",
  "problem.max_plus": "これ以上は強化できません",
  "problem.not_near": "鍛冶屋のそばでできます",
  "problem.not_enough_gold": "ゴールドが足りません",
  "problem.not_in_village": "ショップは村にあります",
  "problem.no_item": "カバンにありません",
  "problem.too_low_advance": "Lv{n}から転職できます",

  "slot.weapon": "武器",
  "slot.armor": "鎧",

  "bag.title": "カバン",
  "bag.power": "戦闘力 {n}",
  "bag.job": "転職",
  "bag.advanceAt": "Lv{at}になると転職できます（現在 Lv{level}）",
  "bag.pickPath": "転職する道を選んでください。一度選ぶと変えられません。",
  "bag.unequip": "外す",
  "bag.empty": "カバンは空です",
  "bag.pickHint": "アイテムを押すと、ここに説明と使い方が出ます。",
  "bag.drink": "飲む",
  "bag.equip": "装備",
  "bag.sell": "売る（{n}）",
  "bag.keys": "Q: ポーションを飲む · I: カバン",

  "shop.title": "村のショップ",
  "shop.buy": "買う",
  "shop.buyTen": "10個",
  "shop.note": "モンスターがゴールドや装備を落とします。売るのはカバンから。",

  "forge.title": "鍛冶屋",
  "forge.stones": "強化石 {n}個",
  "forge.enhance": "強化",
  "forge.craft": "製作",
  "forge.noGear": "装備しているものがありません",
  "forge.chance": "+{to} 成功 {pct}",
  "forge.breakRisk": "失敗時に破壊 {pct}",
  "forge.maxed": "最大強化（+{n}）",
  "forge.note": "+{n}からは失敗すると装備が壊れることがあります。強化石はすべての狩場のモンスターが落とします。",
  "forge.success": "強化成功！",
  "forge.fail": "強化失敗… 装備はそのままです",
  "forge.broken": "強化失敗… 装備が壊れました",
  "forge.crafted": "{name} 製作完了！",

  "common.retry": "もう一度",
  "common.toMenu": "メニューへ",
  "common.menu": "メニュー",
  "common.off2": "オフ",

  "problem.not_owned": "製品版で入れるフィールドです",
  "problem.zone_full": "すべてのチャンネルが満員です。少し待って試してください",
  "problem.not_near_portal": "ポータルのそばに立ってください",
  "problem.too_low": "レベルが足りません",
  "problem.cannotTravel": "今は行けません",
  "problem.enter": "ワールドに入れませんでした",
  "problem.enterWith": "ワールドに入れませんでした（{error}）",
  "problem.connect": "ゲームサーバーに接続できませんでした。ネットワークを確認してもう一度お試しください。",
  "problem.tooFast": "もう少しゆっくり話してください",
  "problem.cannotSend": "送れませんでした",

  "world.entering": "ワールドに入っています…",
  "world.loading": "森を読み込み中… {n}%",
  "world.travelling": "移動中…",
  "world.channel": "チャンネル {n}",
  "world.talk": "{name} — {role} · 会話 (E)",
  "world.portalLocked": "{zone} — 製品版で開きます {how}",
  "world.portalLocked.tap": "· 押して見る",
  "world.portalLevel": "{zone} — Lv{n}から行けます",
  "world.portalTo": "{zone}へ続く道",
  "world.blocking": "ガード中",

  "menu.map": "マップ",
  "menu.upgrade": "製品版",
  "menu.ranking": "ランキング",
  "menu.quests": "クエスト",
  "menu.skills": "スキル",
  "menu.forge": "鍛冶屋",
  "menu.bag": "カバン",
  "menu.sleep": "省電力",
  "menu.settings": "設定",

  "death.fallen": "倒れました",
  "death.lostXp": "経験値を{n}失いました",
  "death.lostNone": "失った経験値はありません",
  "death.lossNote": "倒れるとこのレベルの経験値の{n}%を失います（レベルは下がりません）",
  "death.here": "その場で復活 · {gold}",
  "death.hereNote": "体力{n}%で起き上がり、しばらくモンスターが攻撃しません",
  "death.short": " · ゴールドが足りません",
  "death.village": "村で復活 · 無料",

  "sleep.title": "省電力モード",
  "sleep.elapsed": "経過時間",
  "sleep.xp": "得た経験値",
  "sleep.gold": "得たゴールド",
  "sleep.potions": "残りポーション",
  "sleep.potionCount": "{n}個",
  "sleep.auto": "オート戦闘",
  "sleep.hunting": "狩り中",
  "sleep.dead": "倒れました — 2回押して確認してください",
  "sleep.hint": "画面を2回押すと戻ります",

  "chat.placeholder": "チャンネルに話す",
  "chat.open": "チャット",
  "chat.enterHint": "でチャット",
  "lobby.deleteCharacter": "{name}を削除",
  "delete.title": "キャラクター削除",
  "delete.warning": "「{name}」のレベル・装備・クエストはすべて消え、元に戻せません。削除するには名前をそのまま入力してください。",
  "delete.confirm": "完全に削除",
  "problem.name_mismatch": "名前が違います",

  "quest.allDone": "すべてのクエスト完了",
  "quest.reportHere": "押して村長に報告",
  "quest.reportInVillage": "タップで村の村長のもとへ",
  "quest.seeking": "向かっています…",
  "quest.goFind": "押して向かう",

  "pad.attack": "攻撃",
  "pad.block": "ガード",
  "pad.jump": "ジャンプ",
  "pad.auto": "オート",
  "pad.autoOn": "オート中",
  "pad.leftClick": "左クリック",
  "pad.rightClick": "右クリック",

  "map.tapToWalk": "押すとそこへ歩いていきます",
  "map.portals": "エリアの出入口",
  "map.villagers": "村人",
  "map.you": "自分",
  "map.close": "閉じる (N)",

  "bar.potion": "ポーション",
  "bar.emptySlot": "空き",
  "bar.autoPotion": "オートポーション",
  "bar.autoPotionTitle": "オートポーション設定",
  "bar.autoPotionAt": "HPが{n}%以下になるとポーションを飲みます",
  "bar.autoPotionOff": "（今はオフです）",
  "bar.autoPotionTurnOn": "オートポーションをオン",
  "bar.autoPotionTurnOff": "オートポーションをオフ",

  "skills.title": "スキル",
  "skills.dragNote": "覚えたスキルを下の枠にドラッグしてください。",
  "skills.learnAt": "Lv{n}で習得",
  "skills.fromElder": "村長から習う",
  "skills.inSlot": "{n}番の枠",
  "skills.dragIn": "ドラッグして枠に入れる",
  "skills.cooldown": "再使用 {n}秒",
  "skills.remove": "外す",

  "common.next": "次へ",
  "common.accept": "承諾",
  "common.decline": "辞退",

  "lobby.newCharacter": "新しいキャラクター",
  "lobby.needServer": "Verse8サーバーに接続しないとゲームを始められません。",
  "lobby.accountFailed": "アカウント情報を読み込めませんでした。再読み込みしてください。",
  "lobby.accountLoading": "アカウント情報を読み込み中…",
  "lobby.loading": "村を読み込み中… {n}%",
  "lobby.tapToStart": "画面を押して開始",
  "lobby.friends": "フレンド",
  "lobby.characters": "{world} · キャラクター {n}/{max}",
  "lobby.createCharacter": "+ キャラクター作成",
  "lobby.start": "ゲーム開始",
  "lobby.changeServer": "サーバー変更",
  "lobby.noCharacter": "キャラクターを作って冒険を始めましょう。",
  "lobby.freeNote": "村と森フィールド1は無料で遊べます。",
  "lobby.guestNote": "ログインしていません。このまま作ったキャラクターは次回読み込めません。Verse8にログインしてから始めてください。",

  "buy.buy": "製品版を購入（{price} VX）",
  "buy.confirming": "決済を確認中…",
  "buy.late": "決済の確認に時間がかかっています。少し待って再読み込みしてください。",
  "buy.title": "製品版",
  "buy.short": "製品版を購入",
  "buy.checking": "決済確認中…",
  "buy.noServer": "今は購入できません。接続してからもう一度お試しください。",
  "buy.reason.portal": "{zone}へ続く道は製品版からです。",
  "buy.reason.level": "Lv {n} 達成！無料で行けるのはここまでです。",
  "buy.reason.menu": "無料では村と森フィールド1をLv {n}まで遊べます。",
  "buy.fields": "新しい狩場 {n}か所",
  "buy.noCap": "レベル制限の解除",
  "buy.noCapNote": "Lv {n}で止まらず、転職スキル2つ（Lv {third}）まで",
  "buy.bossNote": "叩きつけと手下を呼ぶボス、その専用装備",
  "buy.classes": "職業 {n}種",
  "buy.off": "{n}% 割引",

  "class.pick": "職業選択",
  "class.weapon": "武器",
  "class.ranged": "遠距離",
  "class.melee": "近接",
  "class.damage": "攻撃力",
  "class.speed": "攻撃速度",
  "class.perSecond": "{n}回/秒",
  "class.reach": "射程",
  "class.block": "ガード",
  "class.skillLine": "スキル {n} · {name}",
  "class.lockedNote": "製品版の職業です。無料では戦士とアーチャーを選べます。",
  "class.confirm": "この職業にする",
  "class.onceNote": "職業はキャラクターを作るときに一度だけ決めます。",
  "class.pickHint": "キャラクターを押して職業を見てみましょう。",

  "look.title": "キャラクターの外見",
  "look.spin": "ドラッグして回す",
  "look.shape": "見た目",
  "look.random": "ランダム",
  "look.making": "作成中…",
  "look.create": "キャラクターを作る",
  "look.onceNote": "外見はキャラクターを作ったあとは変えられません。",
  "look.previous": "{part} 前へ",
  "look.next": "{part} 次へ",

  "part.gear": "飾り",
  "part.clothColor": "服の色",
  "part.skin": "肌",
  "part.weaponColor": "武器の色",
  "look.default": "標準",
  "look.on": "着ける",
  "look.off": "外す",
  "look.grey": "無彩色",
  "look.dye": "染色 {n}",
  "look.skinLight": "明るい",
  "look.skinTan": "小麦色",
  "look.skinDark": "濃い",
  "look.mine": "自分だけの姿",
  "look.preset.light": "軽装",
  "look.preset.shadow": "影",

  "name.title": "キャラクター名",
  "name.note": "他のプレイヤーやフレンドはこの名前であなたを見ます。文字・数字・_ で2〜12文字、他のキャラクターと重複できません。",
  "name.placeholder": "名前",
  "name.checking": "確認中…",

  "server.pick": "サーバー選択",
  "server.note": "同じサーバーを選んだプレイヤー同士で出会います。フレンドと同じサーバーを選びましょう。",
  "server.entering": "入っています…",
  "server.recent": "最近プレイ",
  "server.failed": "サーバーを選べませんでした。少し待ってもう一度お試しください",

  "common.add": "追加",
  "common.cancel": "取消",
  "common.remove": "削除",
  "common.removeSure": "本当に削除",
  "common.noName": "（名前なし）",
  "common.reward": "報酬: {what}",
  "common.xp": "{n} XP",

  "friends.title": "フレンド",
  "friends.needCharacter": "フレンドを追加するにはまずキャラクターを作ってください。",
  "friends.search": "名前でフレンド追加",
  "friends.needServer": "フレンドはVerse8に接続してから使えます。",
  "friends.loading": "フレンド一覧を読み込み中…",
  "friends.sent": "フレンド申請を送りました",
  "friends.bothWays": "お互いに申請したので、すぐフレンドになりました",
  "friends.nowFriends": "{name}さんとフレンドになりました",
  "friends.incoming": "受けた申請 {n}",
  "friends.list": "フレンド一覧",
  "friends.online": "· オンライン {on}/{all}",
  "friends.none": "まだフレンドがいません。名前で追加してみましょう。",
  "friends.isOnline": "オンライン",
  "friends.isOffline": "オフライン",
  "friends.outgoing": "送った申請",
  "friends.waiting": "待機中",

  "problem.friend_not_found": "その名前は見つかりませんでした",
  "problem.friend_self": "自分は追加できません",
  "problem.already_friends": "すでにフレンドです",
  "problem.friend_limit": "フレンドは{n}人まで持てます",
  "problem.request_limit": "相手の受けた申請が多すぎます",
  "problem.no_request": "すでに処理された申請です",
  "problem.nickname_taken": "すでに使われている名前です",
  "problem.nickname_invalid": "文字・数字・_ で2〜12文字まで使えます",
  "problem.character_limit": "このサーバーではこれ以上キャラクターを作れません",
  "problem.retryLater": "今はできません。少し待ってもう一度お試しください",
  "problem.saveFailed": "保存できませんでした。少し待ってもう一度お試しください",
  "problem.not_near_elder": "村長のそばで話してください",
  "problem.quest_unfinished": "まだ終わっていません",
  "problem.cannotClaim": "今は受け取れません",

  "rank.title": "ランキング",
  "rank.needServer": "Verse8に接続すると見られます。",
  "rank.failed": "ランキングを読み込めませんでした。少し待って開き直してください。",
  "rank.none": "まだ経験値を積んだ冒険者がいません。",
  "rank.unranked": "ランク外",
  "rank.place": "{n}位",
  "rank.nickname": "名前",
  "rank.class": "職業",
  "rank.level": "レベル",
  "rank.rank": "順位",
  "rank.server": "サーバー",
  "rank.xp": "経験値",
  "rank.power": "戦闘力",
  "rank.detailFailed": "情報を読み込めませんでした。",
  "rank.toList": "一覧に戻る",

  "quests.title": "クエスト",
  "quests.daily": "デイリークエスト · 毎日0時に更新",
  "quests.claim": "報酬を受け取る",
  "quests.claimedToday": "今日の報酬は受け取りました",
  "quests.goReport": "村長に報告しに行く",
  "quests.reportHint": "村の村長に報告すると報酬がもらえます",
  "quests.goFind": "向かう",
  "quests.allDone": "すべてのクエストを終えました。",
  "quests.past": "完了したクエスト",
  "quests.more": "あと{n}個のクエストがあります。",
  "quests.complete": "クエスト完了！",
  "quests.reportHere": "村長に報告して報酬を受け取りましょう",
  "quests.reportInVillage": "村の村長に報告して報酬を受け取りましょう",
  "npc.merchant.hello": "「いらっしゃい！薬も装備もそろってるよ。」",
  "npc.smith.hello": "「鉄は熱いうちに打て。強化でも製作でも任せな。」",
  "dialogue.shop": "店を見る",
  "dialogue.forge": "鍛冶場を開く",
  "npc.elder.done": "「もうこの森に君を負かすものはないよ。ありがとう、狩人さん。」",
  "npc.elder.tutorial": "「来たか。この技を覚えて、薬も持って行きなさい。スキル画面で技をスロットにドラッグすれば使えるぞ。」",
  "npc.elder.claim": "「{quest}、よくやった！約束の報酬だ。」",
  "npc.elder.ask": "「{goal}を頼むよ。」",

  "note.notHere": "このエリアにはいません",
  "note.questPaid": "{zone}：製品版で行けます",
  "note.questLevel": "{zone}：Lv{n}から行けます",
  "note.cannotWalk": "そこへは行けません",
  "note.gotGold": "+{n} ゴールド",
  "note.gotItem": "{name} 獲得",
  "portal.needsFull": "（製品版）",
  "portal.needsLevel": "（Lv{n}）",

  "error.startFailed": "ゲームを開始できませんでした。",
  "error.reload": "読み込み直す",
  "rotate.hint": "画面を横にするともっと遊びやすくなります",
  "channel.title": "チャンネル",
  "channel.note": "同じチャンネルならどのエリアでも会えます。移っても今いる場所のままです。",
  "channel.here": "現在地",
  "channel.full": "満員",
  "channel.friends": "フレンド: {names}",
  "keys.channel": "チャンネル変更",
  "problem.channel_full": "そのチャンネルは満員です。別のチャンネルを選んでください",
  "friends.where": "{server} · {channel} · {zone}",
  "common.prevPage": "前のページ",
  "common.nextPage": "次のページ",
  "friends.noIncoming": "受けた申請はありません。",
  "friends.noOutgoing": "送った申請はありません。",
  "quests.tabNow": "進行中",
  "quests.tabDaily": "デイリー",
  "quests.tabPast": "完了",
  "quests.noPast": "まだ完了したクエストはありません。",

  "tutorial.title": "はじめの一歩",
  "tutorial.step0": "村長に話しかけよう",
  "tutorial.step1": "スキル画面を開き、覚えた技をスロット1にドラッグしよう",
  "tutorial.step2": "スキルと薬のスロットを下にドラッグして自動使用をオンにしよう",
  "tutorial.step3": "自動戦闘ボタンを押してみよう",
  "tutorial.doneTitle": "準備完了！",
  "tutorial.doneHint": "村長の最初の頼みを確かめよう",
};
