// The game's words, in the language they were written in. Every other language is checked against
// this one: a bundle that is missing a line, or carries one this does not, will not compile.
//
// A line may hold {name}-style holes, which t() fills in. Keep the holes' names the same in every
// language; their order may change freely.
export const ko = {
  "common.close": "닫기",
  "common.back": "뒤로",
  "common.on": "켜짐",
  "common.off": "꺼짐",
  "common.none": "끔",

  "settings.title": "설정",
  "settings.sound": "소리",
  "settings.music": "배경음악",
  "settings.effects": "효과음",
  "settings.controls": "조작",
  "settings.sensitivity": "마우스 감도",
  "settings.times": "{n}배",
  "settings.screen": "화면",
  "settings.brightness": "밝기",
  "settings.quality": "그래픽 품질",
  "settings.quality.low": "낮음",
  "settings.quality.mid": "보통",
  "settings.quality.high": "높음",
  "settings.quality.note": "낮을수록 가볍고 배터리를 덜 써요. 가까운 나무와 풀을 그리는 거리와 화면 해상도가 바뀌어요.",
  "settings.shown": "표시",
  "settings.showNames": "다른 플레이어 이름",
  "settings.damageNumbers": "데미지 숫자",
  "settings.language": "언어",
  "settings.keysTab": "단축키",
  "settings.defaults": "기본값",
  "settings.exit": "메뉴로 나가기",

  "keys.move": "이동",
  "keys.jump": "점프",
  "keys.click": "좌클릭 / 우클릭",
  "keys.attackGuard": "공격 / 막기",
  "keys.skills": "스킬",
  "keys.potion": "물약",
  "keys.talk": "대화",
  "keys.auto": "자동 전투",
  "keys.quest": "퀘스트 찾아가기·보고",
  "keys.chat": "채팅",
  "keys.menu": "메뉴 펼치기",
  "keys.closeWindow": "창 닫기",
  "keys.map": "지도",
  "keys.panels": "랭킹 / 퀘스트 / 스킬 / 대장간 / 가방",
  "keys.powerSave": "절전 모드",
  "keys.settings": "설정",

  // What a path adds to a fight, built from its numbers rather than written out per path, so the
  // words cannot drift from what the game actually gives.
  // What separates the parts of a short list; CJK has its own comma for this.
  "list.join": ", ",
  "stat.power": "공격력 +{n}%",
  "stat.hp": "체력 +{n}",
  "stat.guard": "받는 피해 -{n}%",
  "stat.heal": "회복량 +{n}%",

  "class.warrior": "전사",
  "class.ranger": "궁수",
  "class.wizard": "마법사",
  "class.cleric": "성직자",
  "class.rogue": "도적",
  "class.monk": "무도가",
  "class.warrior.blurb": "장검과 갑옷. 튼튼하게 버티며 벤다",
  "class.ranger.blurb": "멀리서 활로 쏜다. 가까이 붙으면 약하다",
  "class.wizard.blurb": "지팡이로 마법 탄을 날린다. 느리지만 멀리 닿는다",
  "class.cleric.blurb": "동료와 자신을 치유한다",
  "class.rogue.blurb": "단검으로 아주 빠르게 찌른다",
  "class.monk.blurb": "맨손 연타와 기절 기술",

  "weapon.warrior": "장검",
  "weapon.ranger": "활",
  "weapon.wizard": "마법 지팡이",
  "weapon.cleric": "성직자 지팡이",
  "weapon.rogue": "단검",
  "weapon.monk": "주먹",

  "skill.warrior.0": "회전베기",
  "skill.warrior.0.blurb": "한 바퀴 돌며 주변 몬스터를 모두 벤다",
  "skill.berserker.0": "돌진 베기",
  "skill.berserker.0.blurb": "앞을 크게 베어 잠시 넘어뜨린다",
  "skill.berserker.1": "대지 강타",
  "skill.berserker.1.blurb": "땅을 내리쳐 주변을 모두 기절시킨다",
  "skill.ranger.0": "관통 화살",
  "skill.ranger.0.blurb": "앞으로 곧게 날아가 줄지어 선 몬스터를 모두 꿰뚫는다",
  "skill.sniper.0": "조준 사격",
  "skill.sniper.0.blurb": "하나를 노려 크게 맞힌다",
  "skill.sniper.1": "화살비",
  "skill.sniper.1.blurb": "주변에 화살을 쏟아붓는다",
  "skill.wizard.0": "화염 폭발",
  "skill.wizard.0.blurb": "주변을 불꽃으로 덮어 몬스터를 태운다",
  "skill.elementalist.0": "얼음 창",
  "skill.elementalist.0.blurb": "하나를 꿰뚫고 얼려 움직이지 못하게 한다",
  "skill.elementalist.1": "운석 낙하",
  "skill.elementalist.1.blurb": "하늘에서 불덩이를 떨어뜨려 주변을 태운다",
  "skill.cleric.0": "치유의 빛",
  "skill.cleric.0.blurb": "자신과 가까운 동료의 체력을 회복한다",
  "skill.paladin.0": "신성한 일격",
  "skill.paladin.0.blurb": "지팡이에 빛을 실어 앞을 치고 기절시킨다",
  "skill.high_priest.1": "축복",
  "skill.high_priest.1.blurb": "주변 몬스터를 태우고 동료를 크게 회복한다",
  "skill.rogue.0": "그림자 일격",
  "skill.rogue.0.blurb": "앞의 몬스터 하나를 크게 찌른다",
  "skill.assassin.0": "칼날 부채",
  "skill.assassin.0.blurb": "앞으로 단검을 흩뿌린다",
  "skill.assassin.1": "그림자 난무",
  "skill.assassin.1.blurb": "주변을 휘저으며 모두 벤다",
  "skill.monk.0": "기절 연타",
  "skill.monk.0.blurb": "앞의 몬스터를 두들겨 잠시 기절시킨다",
  "skill.fist_master.0": "회오리 발차기",
  "skill.fist_master.0.blurb": "돌며 차서 주변을 모두 때린다",
  "skill.fist_master.1": "백열권",
  "skill.fist_master.1.blurb": "하나에게 온 힘을 실은 주먹을 꽂는다",
  "skill.guardian.0": "방패 강타",
  "skill.guardian.0.blurb": "앞의 몬스터 하나를 방패로 쳐 오래 기절시킨다",
  "skill.guardian.1": "수호의 함성",
  "skill.guardian.1.blurb": "함성으로 주변을 치고 자신과 동료의 체력을 회복한다",
  "skill.tracker.0": "덫 화살",
  "skill.tracker.0.blurb": "하나를 맞혀 발을 묶는다",
  "skill.tracker.1": "부채꼴 사격",
  "skill.tracker.1.blurb": "앞쪽 넓게 화살을 퍼붓는다",
  "skill.warder.0": "결계 파동",
  "skill.warder.0.blurb": "결계를 펼쳐 주변을 치고 잠시 묶는다",
  "skill.warder.1": "수호 결계",
  "skill.warder.1.blurb": "자신과 가까운 동료의 체력을 크게 회복한다",
  "skill.high_priest.0": "정화의 빛",
  "skill.high_priest.0.blurb": "빛줄기로 하나를 태우며 자신과 동료를 조금 회복한다",
  "skill.paladin.1": "심판의 망치",
  "skill.paladin.1.blurb": "빛의 망치를 내리쳐 주변을 모두 기절시킨다",
  "skill.scout.0": "연막",
  "skill.scout.0.blurb": "연막을 터뜨려 주변 몬스터를 잠시 멈춰 세운다",
  "skill.scout.1": "투척 단검",
  "skill.scout.1.blurb": "멀리까지 단검을 부채꼴로 던진다",
  "skill.iron_monk.0": "철산고",
  "skill.iron_monk.0.blurb": "어깨로 들이받아 앞을 넓게 기절시킨다",
  "skill.iron_monk.1": "금강불괴",
  "skill.iron_monk.1.blurb": "기를 터뜨려 주변을 치고 자신과 동료의 체력을 회복한다",
  "class.paths": "Lv{n} 전직 · 둘 중 하나",
  "skills.pathSlot": "전직 스킬 {n}",
  "skills.afterAdvance": "Lv{n}에 전직하면 배움",

  "job.berserker": "버서커",
  "job.guardian": "수호기사",
  "job.sniper": "저격수",
  "job.tracker": "숲의 추적자",
  "job.elementalist": "원소술사",
  "job.warder": "결계술사",
  "job.high_priest": "대사제",
  "job.paladin": "성기사",
  "job.assassin": "암살자",
  "job.scout": "척후병",
  "job.fist_master": "권성",
  "job.iron_monk": "철벽 수도승",

  // A potion's line is built from what it gives back; gear's from stat.* above.
  "item.heal": "체력 {n} 회복",
  "item.potion_small": "작은 물약",
  "item.potion_big": "큰 물약",
  "item.weapon_1": "견습생의 무기",
  "item.weapon_2": "숲지기의 무기",
  "item.weapon_3": "버섯왕의 무기",
  "item.weapon_4": "강철 무기",
  "item.weapon_5": "바위심장 무기",
  "item.armor_1": "가죽 갑옷",
  "item.armor_2": "숲지기의 갑옷",
  "item.armor_3": "버섯왕의 갑옷",
  "item.armor_4": "강철 갑옷",
  "item.armor_5": "바위심장 갑옷",
  "item.stone": "강화석",
  "item.stone.blurb": "장비 강화 재료. 모든 사냥터",
  "item.jelly": "슬라임 젤리",
  "item.jelly.blurb": "제작 재료. 숲 필드 1",
  "item.silk": "거미 비단",
  "item.silk.blurb": "제작 재료. 숲 필드 2",
  "item.core": "바위 심장석",
  "item.core.blurb": "제작 재료. 깊은 숲",
  "item.spore": "버섯왕의 포자",
  "item.spore.blurb": "제작 재료. 버섯왕",

  "monster.green_blob": "초록 슬라임",
  "monster.mushnub": "버섯돌이",
  "monster.rat": "들쥐",
  "monster.frog": "개구리",
  "monster.spider": "숲거미",
  "monster.snake": "독사",
  "monster.wasp": "말벌",
  "monster.bat": "박쥐",
  "monster.goleling": "골렘링",
  "monster.dire_spider": "거대 독거미",
  "monster.venom_snake": "맹독사",
  "monster.hornet": "장수말벌",
  "monster.vampire_bat": "흡혈박쥐",
  "monster.stone_golem": "바위 골렘",
  "monster.mushnub_guard": "버섯 호위병",
  "monster.mushroom_king": "버섯왕",
  "monster.grove_guardian": "정화의 수호자",

  "zone.village": "초록숲 마을",
  "zone.forest1": "숲 필드 1",
  "zone.forest2": "숲 필드 2",
  "zone.forest3": "깊은 숲",
  "zone.boss": "버섯왕의 공터",

  "npc.merchant": "상인 한스",
  "npc.merchant.role": "상점",
  "npc.elder": "촌장 마르타",
  "npc.elder.role": "퀘스트",
  "npc.smith": "대장장이 볼프",
  "npc.smith.role": "강화·제작",

  // The servers are this name and a number.
  "world.name": "초록숲",

  // The village's quests, in the order they are taken, and the three that come back each day.
  "quest.0": "슬라임 퇴치",
  "quest.0.goal": "숲 필드 1의 초록 슬라임 15마리",
  "quest.1": "버섯돌이 소탕",
  "quest.1.goal": "숲 필드 1의 버섯돌이 20마리",
  "quest.2": "들판의 골칫거리",
  "quest.2.goal": "들쥐나 개구리 40마리",
  "quest.3": "깊은 숲 정찰",
  "quest.3.goal": "숲 필드 2의 숲거미나 독사 50마리",
  "quest.4": "하늘의 사냥",
  "quest.4.goal": "말벌이나 박쥐 60마리",
  "quest.5": "돌의 정령",
  "quest.5.goal": "골렘링 60마리",
  "quest.6": "버섯왕 토벌",
  "quest.6.goal": "버섯왕의 공터의 버섯왕",
  "quest.7": "깊은 숲의 거미굴",
  "quest.7.goal": "깊은 숲의 거대 독거미나 맹독사 60마리",
  "quest.8": "하늘을 덮은 날개",
  "quest.8.goal": "장수말벌이나 흡혈박쥐 80마리",
  "quest.9": "숲의 수호석",
  "quest.9.goal": "바위 골렘 60마리",
  "quest.10": "골렘의 심장",
  "quest.10.goal": "바위 골렘 100마리",
  "quest.11": "버섯왕 재토벌",
  "quest.11.goal": "버섯왕 3번 쓰러뜨리기",
  "quest.12": "깊은 숲의 주인",
  "quest.12.goal": "깊은 숲의 몬스터 200마리",
  "daily.forest1": "숲 필드 1 순찰",
  "daily.forest1.goal": "숲 필드 1의 몬스터 30마리",
  "daily.forest2": "숲 필드 2 순찰",
  "daily.forest2.goal": "숲 필드 2의 몬스터 40마리",
  "daily.forest3": "깊은 숲 순찰",
  "daily.forest3.goal": "깊은 숲의 몬스터 50마리",

  "common.loading": "불러오는 중…",
  "common.gold": "{n} 골드",
  "common.nothing": "없음",
  "problem.unavailable": "지금은 할 수 없어요",
  "problem.max_plus": "더 강화할 수 없어요",
  "problem.not_near": "대장장이 가까이에서 할 수 있어요",
  "problem.not_enough_gold": "골드가 모자라요",
  "problem.not_in_village": "상점은 마을에 있어요",
  "problem.no_item": "가방에 없어요",
  "problem.too_low_advance": "Lv{n}부터 전직할 수 있어요",

  "slot.weapon": "무기",
  "slot.armor": "갑옷",

  "bag.title": "가방",
  "bag.power": "전투력 {n}",
  "bag.job": "전직",
  "bag.advanceAt": "Lv{at}이 되면 전직할 수 있어요 (지금 Lv{level})",
  "bag.pickPath": "전직할 길을 고르세요. 한 번 고르면 바꿀 수 없어요.",
  "bag.unequip": "해제",
  "bag.empty": "가방이 비었어요",
  "bag.pickHint": "아이템을 누르면 여기에 설명과 쓰는 법이 나와요.",
  "bag.drink": "마시기",
  "bag.equip": "장착",
  "bag.sell": "팔기 ({n})",
  "bag.keys": "Q: 물약 마시기 · I: 가방",

  "shop.title": "마을 상점",
  "shop.buy": "사기",
  "shop.buyTen": "10개",
  "shop.note": "몬스터가 골드와 장비를 떨어뜨려요. 팔기는 가방에서.",

  "forge.title": "대장간",
  "forge.stones": "강화석 {n}개",
  "forge.enhance": "강화",
  "forge.craft": "제작",
  "forge.noGear": "장착한 장비가 없어요",
  "forge.chance": "+{to} 성공 {pct}",
  "forge.breakRisk": "실패 시 파괴 {pct}",
  "forge.maxed": "최대 강화 (+{n})",
  "forge.note": "+{n}부터는 실패하면 장비가 부서질 수 있어요. 강화석은 모든 사냥터의 몬스터가 떨어뜨려요.",
  "forge.success": "강화 성공!",
  "forge.fail": "강화 실패… 장비는 그대로예요",
  "forge.broken": "강화 실패… 장비가 부서졌어요",
  "forge.crafted": "{name} 제작 완료!",

  "common.retry": "다시 시도",
  "common.toMenu": "메뉴로",
  "common.menu": "메뉴",
  "common.off2": "꺼짐",

  "problem.not_owned": "정식판을 구매하면 들어갈 수 있는 구역이에요",
  "problem.zone_full": "모든 채널이 가득 찼어요. 잠시 뒤 다시 시도해 주세요",
  "problem.not_near_portal": "포털 가까이 서 주세요",
  "problem.too_low": "레벨이 모자라요",
  "problem.cannotTravel": "지금은 갈 수 없어요",
  "problem.enter": "월드에 들어가지 못했어요",
  "problem.enterWith": "월드에 들어가지 못했어요 ({error})",
  "problem.connect": "게임 서버에 연결하지 못했어요. 네트워크를 확인하고 다시 시도해 주세요.",
  "problem.tooFast": "조금 천천히 말해 주세요",
  "problem.cannotSend": "보낼 수 없어요",

  "world.entering": "월드에 들어가는 중…",
  "world.loading": "숲을 불러오는 중… {n}%",
  "world.travelling": "이동하는 중…",
  "world.channel": "채널 {n}",
  "world.talk": "{name} — {role} · 대화 (E)",
  "world.portalLocked": "{zone} — 정식판으로 열려요 {how}",
  "world.portalLocked.tap": "· 눌러서 보기",
  "world.portalLevel": "{zone} — Lv{n}부터 갈 수 있어요",
  "world.portalTo": "{zone}(으)로 가는 길",
  "world.blocking": "막는 중",

  "menu.map": "지도",
  "menu.upgrade": "정식판",
  "menu.ranking": "랭킹",
  "menu.quests": "퀘스트",
  "menu.skills": "스킬",
  "menu.forge": "대장간",
  "menu.bag": "가방",
  "menu.sleep": "절전",
  "menu.settings": "설정",

  "death.fallen": "쓰러졌어요",
  "death.lostXp": "경험치 {n}를 잃었어요",
  "death.lostNone": "잃은 경험치는 없어요",
  "death.lossNote": "쓰러지면 이번 레벨 경험치의 {n}%를 잃어요 (레벨은 내려가지 않아요)",
  "death.here": "이 자리에서 부활 · {gold}",
  "death.hereNote": "체력 {n}%로 일어나고, 잠깐 몬스터가 공격하지 않아요",
  "death.short": " · 골드가 모자라요",
  "death.village": "마을에서 부활 · 무료",

  "sleep.title": "절전 모드",
  "sleep.elapsed": "경과 시간",
  "sleep.xp": "얻은 경험치",
  "sleep.gold": "얻은 골드",
  "sleep.potions": "남은 물약",
  "sleep.potionCount": "{n}개",
  "sleep.auto": "자동 전투",
  "sleep.hunting": "사냥 중",
  "sleep.dead": "쓰러졌어요 — 두 번 눌러 확인하세요",
  "sleep.hint": "화면을 두 번 누르면 돌아가요",

  "chat.placeholder": "채널에 말하기",
  "chat.open": "채팅",
  "chat.enterHint": "눌러서 채팅",
  "lobby.deleteCharacter": "{name} 삭제",
  "delete.title": "캐릭터 삭제",
  "delete.warning": "‘{name}’의 레벨, 장비, 퀘스트가 모두 사라지고 되돌릴 수 없어요. 지우려면 이름을 그대로 입력하세요.",
  "delete.confirm": "영구 삭제",
  "problem.name_mismatch": "이름이 맞지 않아요",

  "quest.allDone": "모든 퀘스트 완료",
  "quest.reportHere": "눌러서 촌장에게 보고하기",
  "quest.reportInVillage": "눌러서 마을 촌장에게 가기",
  "quest.seeking": "찾아가는 중…",
  "quest.goFind": "눌러서 찾아가기",

  "pad.attack": "공격",
  "pad.block": "막기",
  "pad.jump": "점프",
  "pad.auto": "자동",
  "pad.autoOn": "자동 중",
  "pad.leftClick": "좌클릭",
  "pad.rightClick": "우클릭",

  "map.tapToWalk": "눌러서 그곳으로 걸어갑니다",
  "map.portals": "구역 출입구",
  "map.villagers": "마을 사람",
  "map.you": "나",
  "map.close": "닫기 (N)",

  "bar.potion": "물약",
  "bar.emptySlot": "빈 칸",
  "bar.autoPotion": "자동 물약",
  "bar.autoPotionTitle": "자동 물약 설정",
  "bar.autoPotionAt": "HP가 {n}% 이하가 되면 물약을 마셔요",
  "bar.autoPotionOff": " (지금은 꺼져 있어요)",
  "bar.autoPotionTurnOn": "자동 물약 켜기",
  "bar.autoPotionTurnOff": "자동 물약 끄기",

  "skills.title": "스킬",
  "skills.dragNote": "배운 스킬을 아래 칸으로 끌어다 놓으세요.",
  "skills.learnAt": "Lv{n}에 배움",
  "skills.fromElder": "촌장에게 배우기",
  "skills.inSlot": "{n}번 칸",
  "skills.dragIn": "끌어서 칸에 넣기",
  "skills.cooldown": "재사용 {n}초",
  "skills.remove": "빼기",

  "common.next": "다음",
  "common.accept": "수락",
  "common.decline": "거절",

  "lobby.newCharacter": "새 캐릭터",
  "lobby.needServer": "게임은 Verse8 서버에 연결되어야 시작할 수 있어요.",
  "lobby.accountFailed": "계정 정보를 불러오지 못했어요. 새로고침해 주세요.",
  "lobby.accountLoading": "계정 정보를 불러오는 중…",
  "lobby.loading": "마을을 불러오는 중… {n}%",
  "lobby.tapToStart": "화면을 눌러 시작",
  "lobby.friends": "친구",
  "lobby.characters": "{world} · 캐릭터 {n}/{max}",
  "lobby.createCharacter": "+ 캐릭터 생성",
  "lobby.start": "게임 시작",
  "lobby.changeServer": "서버 바꾸기",
  "lobby.noCharacter": "캐릭터를 만들어 모험을 시작하세요.",
  "lobby.freeNote": "무료로 마을과 숲 필드 1을 즐길 수 있어요.",
  "lobby.guestNote": "로그인하지 않은 상태예요. 이대로 만든 캐릭터는 다음에 접속하면 불러올 수 없어요. Verse8에 로그인한 뒤 시작해 주세요.",

  "buy.buy": "정식판 구매 ({price} VX)",
  "buy.confirming": "결제를 확인하는 중…",
  "buy.late": "결제 확인이 늦어지고 있어요. 잠시 뒤 새로고침해 주세요.",
  "buy.title": "정식판",
  "buy.short": "정식판 구매",
  "buy.checking": "결제 확인 중…",
  "buy.noServer": "지금은 구매할 수 없어요. 서버에 연결된 뒤 다시 시도해 주세요.",
  "buy.reason.portal": "{zone}(으)로 가는 길은 정식판부터예요.",
  "buy.reason.level": "Lv {n} 달성! 무료로 갈 수 있는 곳은 여기까지예요.",
  "buy.reason.menu": "무료로는 마을과 숲 필드 1을 Lv {n}까지 즐길 수 있어요.",
  "buy.fields": "새 사냥터 {n}곳",
  "buy.noCap": "레벨 제한 해제",
  "buy.noCapNote": "Lv {n}에서 멈추지 않고 전직 스킬 2개(Lv {third})까지",
  "buy.bossNote": "내려찍기와 부하를 부르는 보스, 그 전용 장비",
  "buy.classes": "직업 {n}개",
  "buy.off": "{n}% 할인",

  "class.pick": "직업 선택",
  "class.weapon": "무기",
  "class.ranged": "원거리",
  "class.melee": "근접",
  "class.damage": "공격력",
  "class.speed": "공격 속도",
  "class.perSecond": "{n}회/초",
  "class.reach": "사거리",
  "class.block": "막기",
  "class.skillLine": "스킬 {n} · {name}",
  "class.lockedNote": "정식판 직업이에요. 무료로는 전사와 궁수를 고를 수 있어요.",
  "class.confirm": "이 직업으로 정하기",
  "class.onceNote": "직업은 캐릭터를 만들 때 한 번 정해요.",
  "class.pickHint": "캐릭터를 눌러 직업을 살펴보세요.",

  "look.title": "캐릭터 외형 정하기",
  "look.spin": "드래그해서 돌려 보기",
  "look.shape": "모습",
  "look.random": "무작위",
  "look.making": "만드는 중…",
  "look.create": "캐릭터 만들기",
  "look.onceNote": "외형은 캐릭터를 만든 뒤에는 바꿀 수 없어요.",
  "look.previous": "{part} 이전",
  "look.next": "{part} 다음",

  "part.gear": "장식",
  "part.clothColor": "옷 색",
  "part.skin": "피부",
  "part.weaponColor": "무기 색",
  "look.default": "기본",
  "look.on": "착용",
  "look.off": "벗기",
  "look.grey": "무채색",
  "look.dye": "염색 {n}",
  "look.skinLight": "밝은",
  "look.skinTan": "구릿빛",
  "look.skinDark": "짙은",
  "look.mine": "나만의 모습",
  "look.preset.light": "가벼운 차림",
  "look.preset.shadow": "그림자",

  "name.title": "캐릭터 이름",
  "name.note": "다른 플레이어와 친구가 이 이름으로 당신을 봅니다. 한글·영문·숫자·_ 로 2~12자, 다른 캐릭터와 겹칠 수 없어요.",
  "name.placeholder": "이름",
  "name.checking": "확인 중…",

  "server.pick": "서버 선택",
  "server.note": "같은 서버를 고른 플레이어끼리 만나요. 친구와 같은 서버를 골라 보세요.",
  "server.entering": "들어가는 중…",
  "server.recent": "최근 접속",
  "server.failed": "서버를 고르지 못했어요. 잠시 뒤 다시 시도해 주세요",

  "common.add": "추가",
  "common.cancel": "취소",
  "common.remove": "삭제",
  "common.removeSure": "정말 삭제",
  "common.noName": "(이름 없음)",
  "common.reward": "보상: {what}",
  "common.xp": "{n} XP",

  "friends.title": "친구",
  "friends.needCharacter": "친구를 추가하려면 먼저 캐릭터를 만드세요.",
  "friends.search": "닉네임으로 친구 추가",
  "friends.needServer": "친구는 Verse8 서버를 연결한 뒤 열립니다.",
  "friends.loading": "친구 목록을 불러오는 중…",
  "friends.sent": "친구 요청을 보냈어요",
  "friends.bothWays": "서로 요청해서 바로 친구가 되었어요",
  "friends.nowFriends": "{name}님과 친구가 되었어요",
  "friends.incoming": "받은 요청 {n}",
  "friends.list": "친구 목록",
  "friends.online": "· 온라인 {on}/{all}",
  "friends.none": "아직 친구가 없습니다. 닉네임으로 추가해 보세요.",
  "friends.isOnline": "온라인",
  "friends.isOffline": "오프라인",
  "friends.outgoing": "보낸 요청",
  "friends.waiting": "대기 중",

  "problem.friend_not_found": "그런 닉네임을 찾지 못했어요",
  "problem.friend_self": "자기 자신은 추가할 수 없어요",
  "problem.already_friends": "이미 친구예요",
  "problem.friend_limit": "친구는 {n}명까지 둘 수 있어요",
  "problem.request_limit": "상대가 받은 요청이 너무 많아요",
  "problem.no_request": "이미 처리된 요청이에요",
  "problem.nickname_taken": "이미 쓰고 있는 이름이에요",
  "problem.nickname_invalid": "한글·영문·숫자·_ 로 2~12자까지 쓸 수 있어요",
  "problem.character_limit": "이 서버에는 캐릭터를 더 만들 수 없어요",
  "problem.retryLater": "지금은 할 수 없어요. 잠시 뒤 다시 시도해 주세요",
  "problem.saveFailed": "저장하지 못했어요. 잠시 뒤 다시 시도해 주세요",
  "problem.not_near_elder": "촌장 곁에 서서 이야기하세요",
  "problem.quest_unfinished": "아직 다 끝나지 않았어요",
  "problem.cannotClaim": "지금은 받을 수 없어요",

  "rank.title": "랭킹",
  "rank.needServer": "Verse8 서버에 연결되면 볼 수 있어요.",
  "rank.failed": "랭킹을 불러오지 못했어요. 잠시 뒤 다시 열어 주세요.",
  "rank.none": "아직 경험치를 쌓은 모험가가 없어요.",
  "rank.unranked": "랭킹 없음",
  "rank.place": "{n}위",
  "rank.nickname": "닉네임",
  "rank.class": "직업",
  "rank.level": "레벨",
  "rank.rank": "순위",
  "rank.server": "서버",
  "rank.xp": "경험치",
  "rank.power": "전투력",
  "rank.detailFailed": "정보를 불러오지 못했어요.",
  "rank.toList": "목록으로",

  "quests.title": "퀘스트",
  "quests.daily": "일일 퀘스트 · 매일 0시에 새로 시작",
  "quests.claim": "보상 받기",
  "quests.claimedToday": "오늘 보상을 받았어요",
  "quests.goReport": "촌장에게 보고하러 가기",
  "quests.reportHint": "마을의 촌장에게 보고하면 보상을 받아요",
  "quests.goFind": "찾아가기",
  "quests.allDone": "모든 퀘스트를 마쳤어요.",
  "quests.past": "완료한 퀘스트",
  "quests.more": "앞으로 {n}개의 퀘스트가 더 있어요.",
  "quests.complete": "퀘스트 완료!",
  "quests.reportHere": "촌장에게 보고하고 보상을 받으세요",
  "quests.reportInVillage": "마을의 촌장에게 보고하고 보상을 받으세요",
  "npc.merchant.hello": "\"어서 오게! 물약이며 장비며 다 갖춰 두었다네.\"",
  "npc.smith.hello": "\"쇠는 뜨거울 때 두드려야지. 강화든 제작이든 맡겨 두게.\"",
  "dialogue.shop": "상점 보기",
  "dialogue.forge": "대장간 열기",
  "npc.elder.done": "\"이제 이 숲에서 자네를 당해낼 것은 없네. 고맙네, 사냥꾼.\"",
  "npc.elder.tutorial": "\"왔구먼. 이 기술을 익히고 물약도 챙겨 가게. 스킬 창에서 기술을 칸에 끌어 두면 쓸 수 있다네.\"",
  "npc.elder.claim": "\"{quest}, 잘 해냈군! 약속한 보상일세.\"",
  "npc.elder.ask": "\"{goal}{p} 부탁하네.\"",

  "note.notHere": "이 구역에는 없어요",
  "note.questPaid": "{zone}: 정식판에서 갈 수 있어요",
  "note.questLevel": "{zone}: 레벨 {n}부터 갈 수 있어요",
  "note.cannotWalk": "그곳으로는 갈 수 없어요",
  "note.gotGold": "+{n} 골드",
  "note.gotItem": "{name} 획득",
  "portal.needsFull": " (정식판)",
  "portal.needsLevel": " (Lv{n})",

  "error.startFailed": "게임을 시작하지 못했습니다.",
  "error.reload": "다시 불러오기",
  "rotate.hint": "화면을 가로로 돌리면 더 편하게 즐길 수 있어요",
  "channel.title": "채널",
  "channel.note": "같은 채널이면 어느 구역에서든 만날 수 있어요. 옮겨도 지금 서 있는 자리 그대로예요.",
  "channel.here": "지금 여기",
  "channel.full": "가득 참",
  "channel.friends": "친구: {names}",
  "keys.channel": "채널 바꾸기",
  "problem.channel_full": "그 채널은 가득 찼어요. 다른 채널을 골라 주세요",
  "friends.where": "{server} · {channel} · {zone}",
  "common.prevPage": "이전 쪽",
  "common.nextPage": "다음 쪽",
  "friends.noIncoming": "받은 요청이 없어요.",
  "friends.noOutgoing": "보낸 요청이 없어요.",
  "quests.tabNow": "진행 중",
  "quests.tabDaily": "일일",
  "quests.tabPast": "완료",
  "quests.noPast": "아직 마친 퀘스트가 없어요.",

  "tutorial.title": "첫걸음",
  "tutorial.step0": "촌장에게 말을 거세요",
  "tutorial.step1": "스킬 창을 열어 받은 스킬을 1번 칸에 끌어 놓으세요",
  "tutorial.step2": "스킬 칸과 물약 칸을 아래로 끌어 자동 사용을 켜세요",
  "tutorial.step3": "자동 전투 버튼을 눌러 보세요",
  "tutorial.doneTitle": "준비 끝!",
  "tutorial.doneHint": "촌장의 첫 부탁을 확인하세요",

  "menu.grove": "숲",
  "grove.title": "숲 정화",
  "grove.kills": "이번 주 {n} / {goal}마리",
  "grove.daysLeft": "{n}일 남음",
  "grove.stage.1": "30% 꽃이 피고 골드 200",
  "grove.stage.2": "60% 하늘이 맑아지고 건물 터가 열림",
  "grove.stage.3": "100% 정화의 수호자, 골드 500",
  "grove.hazeHint": "몬스터를 잡으면 숲이 정화돼요.\n60%가 되면 안개가 걷혀요 (이번 주 {n}%)",
  "grove.village": "마을 복구",
  "grove.building.herbalist": "약초상",
  "grove.building.training": "훈련소",
  "grove.building.inn": "여관",
  "grove.building.watchtower": "망루",
  "grove.perk.herbalist": "물약 값 -20%",
  "grove.perk.training": "사냥 경험치 +5%",
  "grove.perk.inn": "쓰러질 때 잃는 경험치 절반",
  "grove.perk.watchtower": "미니맵에 보스 표시",
  "grove.closed": "닫힘",
  "grove.building": "짓는 중 {n}%",
  "grove.done": "완공",
  "grove.failed": "불러오지 못했어요",
  "dialogue.donate": "기부하기",
  "donate.title": "{building} 짓기",
  "donate.have": "가진 것 {n}",
  "donate.gold": "골드",
  "donate.done": "고맙네! 자네 이름을 새겨 두지.",
  "problem.nothing": "넣을 것을 골라 주세요",
  "problem.no_building": "지금 지을 건물이 없어요",
} as const;

export type Key = keyof typeof ko;
// Every other language must answer the same keys, no more and no fewer.
export type Bundle = Record<Key, string>;
