// The game's words, in the language they were written in. Every other language is checked against
// this one: a bundle that is missing a line, or carries one this does not, will not compile.
//
// A line may hold {name}-style holes, which t() fills in. Keep the holes' names the same in every
// language; their order may change freely.
export const ko = {
  "common.close": "닫기",
  "common.back": "뒤로",
  "common.on": "켜짐",
  "common.off": "꺼짐",
  "common.none": "끔",

  "settings.title": "설정",
  "settings.sound": "소리",
  "settings.music": "배경음악",
  "settings.effects": "효과음",
  "settings.controls": "조작",
  "settings.sensitivity": "마우스 감도",
  "settings.times": "{n}배",
  "settings.screen": "화면",
  "settings.brightness": "밝기",
  "settings.quality": "그래픽 품질",
  "settings.quality.low": "낮음",
  "settings.quality.mid": "보통",
  "settings.quality.high": "높음",
  "settings.quality.note": "낮을수록 가볍고 배터리를 덜 써요. 가까운 나무와 풀을 그리는 거리와 화면 해상도가 바뀌어요.",
  "settings.shown": "표시",
  "settings.showNames": "다른 플레이어 이름",
  "settings.damageNumbers": "데미지 숫자",
  "settings.language": "언어",
  "settings.keys.show": "단축키 보기",
  "settings.keys.hide": "단축키 닫기",
  "settings.defaults": "기본값",
  "settings.exit": "메뉴로 나가기",

  "keys.move": "이동",
  "keys.jump": "점프",
  "keys.click": "좌클릭 / 우클릭",
  "keys.attackGuard": "공격 / 막기",
  "keys.skills": "스킬",
  "keys.potion": "물약",
  "keys.talk": "대화",
  "keys.auto": "자동 전투",
  "keys.quest": "퀘스트 찾아가기·보고",
  "keys.chat": "채팅",
  "keys.menu": "메뉴 펼치기",
  "keys.closeWindow": "창 닫기",
  "keys.map": "지도",
  "keys.panels": "랭킹 / 퀘스트 / 스킬 / 대장간 / 가방",
  "keys.powerSave": "절전 모드",
  "keys.settings": "설정",

  // What a path adds to a fight, built from its numbers rather than written out per path, so the
  // words cannot drift from what the game actually gives.
  // What separates the parts of a short list; CJK has its own comma for this.
  "list.join": ", ",
  "stat.power": "공격력 +{n}%",
  "stat.hp": "체력 +{n}",
  "stat.guard": "받는 피해 -{n}%",
  "stat.heal": "회복량 +{n}%",

  "class.warrior": "전사",
  "class.ranger": "궁수",
  "class.wizard": "마법사",
  "class.cleric": "성직자",
  "class.rogue": "도적",
  "class.monk": "무도가",
  "class.warrior.blurb": "장검과 갑옷. 튼튼하게 버티며 벤다",
  "class.ranger.blurb": "멀리서 활로 쏜다. 가까이 붙으면 약하다",
  "class.wizard.blurb": "지팡이로 마법 탄을 날린다. 느리지만 멀리 닿는다",
  "class.cleric.blurb": "동료와 자신을 치유한다",
  "class.rogue.blurb": "단검으로 아주 빠르게 찌른다",
  "class.monk.blurb": "맨손 연타와 기절 기술",

  "weapon.warrior": "장검",
  "weapon.ranger": "활",
  "weapon.wizard": "마법 지팡이",
  "weapon.cleric": "성직자 지팡이",
  "weapon.rogue": "단검",
  "weapon.monk": "주먹",

  "skill.warrior.0": "회전베기",
  "skill.warrior.0.blurb": "한 바퀴 돌며 주변 몬스터를 모두 벤다",
  "skill.warrior.1": "돌진 베기",
  "skill.warrior.1.blurb": "앞을 크게 베어 잠시 넘어뜨린다",
  "skill.warrior.2": "대지 강타",
  "skill.warrior.2.blurb": "땅을 내리쳐 주변을 모두 기절시킨다",
  "skill.ranger.0": "관통 화살",
  "skill.ranger.0.blurb": "앞으로 곧게 날아가 줄지어 선 몬스터를 모두 꿰뚫는다",
  "skill.ranger.1": "조준 사격",
  "skill.ranger.1.blurb": "하나를 노려 크게 맞힌다",
  "skill.ranger.2": "화살비",
  "skill.ranger.2.blurb": "주변에 화살을 쏟아붓는다",
  "skill.wizard.0": "화염 폭발",
  "skill.wizard.0.blurb": "주변을 불꽃으로 덮어 몬스터를 태운다",
  "skill.wizard.1": "얼음 창",
  "skill.wizard.1.blurb": "하나를 꿰뚫고 얼려 움직이지 못하게 한다",
  "skill.wizard.2": "운석 낙하",
  "skill.wizard.2.blurb": "하늘에서 불덩이를 떨어뜨려 주변을 태운다",
  "skill.cleric.0": "치유의 빛",
  "skill.cleric.0.blurb": "자신과 가까운 동료의 체력을 회복한다",
  "skill.cleric.1": "신성한 일격",
  "skill.cleric.1.blurb": "지팡이에 빛을 실어 앞을 치고 기절시킨다",
  "skill.cleric.2": "축복",
  "skill.cleric.2.blurb": "주변 몬스터를 태우고 동료를 크게 회복한다",
  "skill.rogue.0": "그림자 일격",
  "skill.rogue.0.blurb": "앞의 몬스터 하나를 크게 찌른다",
  "skill.rogue.1": "칼날 부채",
  "skill.rogue.1.blurb": "앞으로 단검을 흩뿌린다",
  "skill.rogue.2": "그림자 난무",
  "skill.rogue.2.blurb": "주변을 휘저으며 모두 벤다",
  "skill.monk.0": "기절 연타",
  "skill.monk.0.blurb": "앞의 몬스터를 두들겨 잠시 기절시킨다",
  "skill.monk.1": "회오리 발차기",
  "skill.monk.1.blurb": "돌며 차서 주변을 모두 때린다",
  "skill.monk.2": "백열권",
  "skill.monk.2.blurb": "하나에게 온 힘을 실은 주먹을 꽂는다",

  "job.berserker": "버서커",
  "job.guardian": "수호기사",
  "job.sniper": "저격수",
  "job.tracker": "숲의 추적자",
  "job.elementalist": "원소술사",
  "job.warder": "결계술사",
  "job.high_priest": "대사제",
  "job.paladin": "성기사",
  "job.assassin": "암살자",
  "job.scout": "척후병",
  "job.fist_master": "권성",
  "job.iron_monk": "철벽 수도승",

  // A potion's line is built from what it gives back; gear's from stat.* above.
  "item.heal": "체력 {n} 회복",
  "item.potion_small": "작은 물약",
  "item.potion_big": "큰 물약",
  "item.weapon_1": "견습생의 무기",
  "item.weapon_2": "숲지기의 무기",
  "item.weapon_3": "버섯왕의 무기",
  "item.weapon_4": "강철 무기",
  "item.weapon_5": "바위심장 무기",
  "item.armor_1": "가죽 갑옷",
  "item.armor_2": "숲지기의 갑옷",
  "item.armor_3": "버섯왕의 갑옷",
  "item.armor_4": "강철 갑옷",
  "item.armor_5": "바위심장 갑옷",
  "item.stone": "강화석",
  "item.stone.blurb": "장비 강화 재료. 모든 사냥터",
  "item.jelly": "슬라임 젤리",
  "item.jelly.blurb": "제작 재료. 숲 필드 1",
  "item.silk": "거미 비단",
  "item.silk.blurb": "제작 재료. 숲 필드 2",
  "item.core": "바위 심장석",
  "item.core.blurb": "제작 재료. 깊은 숲",
  "item.spore": "버섯왕의 포자",
  "item.spore.blurb": "제작 재료. 버섯왕",

  "monster.green_blob": "초록 슬라임",
  "monster.mushnub": "버섯돌이",
  "monster.rat": "들쥐",
  "monster.frog": "개구리",
  "monster.spider": "숲거미",
  "monster.snake": "독사",
  "monster.wasp": "말벌",
  "monster.bat": "박쥐",
  "monster.goleling": "골렘링",
  "monster.dire_spider": "거대 독거미",
  "monster.venom_snake": "맹독사",
  "monster.hornet": "장수말벌",
  "monster.vampire_bat": "흡혈박쥐",
  "monster.stone_golem": "바위 골렘",
  "monster.mushnub_guard": "버섯 호위병",
  "monster.mushroom_king": "버섯왕",

  "zone.village": "초록숲 마을",
  "zone.forest1": "숲 필드 1",
  "zone.forest2": "숲 필드 2",
  "zone.forest3": "깊은 숲",
  "zone.boss": "버섯왕의 공터",

  "npc.merchant": "상인 한스",
  "npc.merchant.role": "상점",
  "npc.elder": "촌장 마르타",
  "npc.elder.role": "퀘스트",
  "npc.smith": "대장장이 볼프",
  "npc.smith.role": "강화·제작",

  // The servers are this name and a number.
  "world.name": "초록숲",

  // The village's quests, in the order they are taken, and the three that come back each day.
  "quest.0": "슬라임 퇴치",
  "quest.0.goal": "숲 필드 1의 초록 슬라임 15마리",
  "quest.1": "버섯돌이 소탕",
  "quest.1.goal": "숲 필드 1의 버섯돌이 20마리",
  "quest.2": "들판의 골칫거리",
  "quest.2.goal": "들쥐나 개구리 40마리",
  "quest.3": "깊은 숲 정찰",
  "quest.3.goal": "숲 필드 2의 숲거미나 독사 50마리",
  "quest.4": "하늘의 사냥",
  "quest.4.goal": "말벌이나 박쥐 60마리",
  "quest.5": "돌의 정령",
  "quest.5.goal": "골렘링 60마리",
  "quest.6": "버섯왕 토벌",
  "quest.6.goal": "버섯왕의 공터의 버섯왕",
  "quest.7": "깊은 숲의 거미굴",
  "quest.7.goal": "깊은 숲의 거대 독거미나 맹독사 60마리",
  "quest.8": "하늘을 덮은 날개",
  "quest.8.goal": "장수말벌이나 흡혈박쥐 80마리",
  "quest.9": "숲의 수호석",
  "quest.9.goal": "바위 골렘 60마리",
  "quest.10": "골렘의 심장",
  "quest.10.goal": "바위 골렘 100마리",
  "quest.11": "버섯왕 재토벌",
  "quest.11.goal": "버섯왕 3번 쓰러뜨리기",
  "quest.12": "깊은 숲의 주인",
  "quest.12.goal": "깊은 숲의 몬스터 200마리",
  "daily.forest1": "숲 필드 1 순찰",
  "daily.forest1.goal": "숲 필드 1의 몬스터 30마리",
  "daily.forest2": "숲 필드 2 순찰",
  "daily.forest2.goal": "숲 필드 2의 몬스터 40마리",
  "daily.forest3": "깊은 숲 순찰",
  "daily.forest3.goal": "깊은 숲의 몬스터 50마리",
} as const;

export type Key = keyof typeof ko;
// Every other language must answer the same keys, no more and no fewer.
export type Bundle = Record<Key, string>;
