import type { Bundle } from "./ko";

export const zhHant: Bundle = {
  "common.close": "關閉",
  "common.back": "返回",
  "common.on": "開啟",
  "common.off": "關閉",
  "common.none": "關",

  "settings.title": "設定",
  "settings.sound": "音效",
  "settings.music": "背景音樂",
  "settings.effects": "音效",
  "settings.controls": "操作",
  "settings.sensitivity": "滑鼠靈敏度",
  "settings.times": "{n}倍",
  "settings.screen": "畫面",
  "settings.brightness": "亮度",
  "settings.quality": "畫質",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "越低越省效能與電量。會改變樹木與草地的完整繪製距離，以及畫面解析度。",
  "settings.shown": "顯示",
  "settings.showNames": "其他玩家名稱",
  "settings.damageNumbers": "傷害數字",
  "settings.announcements": "全服公告",
  "announce.legendary": "[{server}] {name}獲得了傳說坐騎{mount}！",
  "announce.star5": "[{server}] {name}的{mount}達成★5突破！",
  "announce.enhance": "[{server}] {name}成功強化{item}！",
  "announce.guildBoss": "公會<{guild}>擊敗了{boss}！",
  "settings.language": "語言",
  "settings.keysTab": "快捷鍵",
  "settings.defaults": "預設值",
  "settings.exit": "回到選單",

  "keys.jump": "跳躍",
  "keys.click": "左鍵 / 右鍵",
  "keys.attackGuard": "攻擊 / 格擋",
  "keys.skills": "技能",
  "keys.potion": "藥水",
  "keys.talk": "對話",
  "keys.auto": "自動戰鬥",
  "keys.quest": "前往任務・回報",
  "keys.chat": "聊天",
  "keys.move": "移動（方向鍵也可）",
  "keys.menu": "展開選單",
  "keys.closeWindow": "關閉視窗",
  "keys.map": "地圖",
  "keys.panels": "排行 / 任務 / 技能 / 鐵匠鋪 / 背包 / 坐騎",
  "keys.powerSave": "省電模式",
  "keys.settings": "設定",

  "list.join": "、",
  "stat.power": "攻擊力 +{n}%",
  "stat.hp": "體力 +{n}",
  "stat.guard": "受到傷害 -{n}%",
  "stat.heal": "治療量 +{n}%",

  "class.warrior": "戰士",
  "class.ranger": "弓箭手",
  "class.wizard": "法師",
  "class.cleric": "牧師",
  "class.rogue": "盜賊",
  "class.monk": "武鬥家",
  "class.warrior.blurb": "長劍與盔甲。站穩腳步一路砍過去。",
  "class.ranger.blurb": "從遠處射箭。被貼近就弱了。",
  "class.wizard.blurb": "以法杖射出魔彈。慢，但打得遠。",
  "class.cleric.blurb": "治療自己與身邊的夥伴。",
  "class.rogue.blurb": "用短劍極快地刺擊。",
  "class.monk.blurb": "赤手連打，還有讓人暈眩的招式。",

  "weapon.warrior": "長劍",
  "weapon.ranger": "弓",
  "weapon.wizard": "魔法杖",
  "weapon.cleric": "聖職者之杖",
  "weapon.rogue": "短劍",
  "weapon.monk": "拳",

  "skill.warrior.0": "迴旋斬",
  "skill.warrior.0.blurb": "旋轉一圈，砍中周圍所有怪物。",
  "skill.berserker.0": "突進斬",
  "skill.berserker.0.blurb": "向前大力揮砍，短暫擊倒對手。",
  "skill.berserker.1": "大地強擊",
  "skill.berserker.1.blurb": "重擊地面，暈眩周圍所有怪物。",
  "skill.berserker.2": "大屠殺",
  "skill.berserker.2.blurb": "任由狂怒驅使，斬倒周圍所有敵人",
  "skill.ranger.0": "貫穿之箭",
  "skill.ranger.0.blurb": "筆直飛出，貫穿成列的怪物。",
  "skill.sniper.0": "瞄準射擊",
  "skill.sniper.0.blurb": "鎖定一個目標，造成大量傷害。",
  "skill.sniper.1": "箭雨",
  "skill.sniper.1.blurb": "向周圍傾瀉箭矢。",
  "skill.sniper.2": "穿天一擊",
  "skill.sniper.2.blurb": "從極遠處貫穿單一目標的必殺一箭",
  "skill.wizard.0": "烈焰爆發",
  "skill.wizard.0.blurb": "以火焰覆蓋周圍，燒灼怪物。",
  "skill.elementalist.0": "冰之槍",
  "skill.elementalist.0.blurb": "貫穿並凍結一個目標，使其無法移動。",
  "skill.elementalist.1": "隕石墜落",
  "skill.elementalist.1.blurb": "自天而降的火球，燒盡周圍。",
  "skill.elementalist.2": "冰河風暴",
  "skill.elementalist.2.blurb": "召喚冰暴，凍結並重創周圍敵人",
  "skill.cleric.0": "治癒之光",
  "skill.cleric.0.blurb": "回復自己與附近夥伴的體力。",
  "skill.paladin.0": "神聖一擊",
  "skill.paladin.0.blurb": "杖上凝光擊向前方，並使其暈眩。",
  "skill.high_priest.1": "祝福",
  "skill.high_priest.1.blurb": "燒灼周圍怪物，並大幅回復夥伴。",
  "skill.high_priest.2": "生命讚歌",
  "skill.high_priest.2.blurb": "大範圍散發光芒，大幅回復自己與隊友的體力",
  "skill.rogue.0": "暗影一擊",
  "skill.rogue.0.blurb": "深深刺向前方的一個怪物。",
  "skill.assassin.0": "刃之扇",
  "skill.assassin.0.blurb": "向前方撒出短劍。",
  "skill.assassin.1": "暗影亂舞",
  "skill.assassin.1.blurb": "攪動周圍，一併斬盡。",
  "skill.assassin.2": "暗殺",
  "skill.assassin.2.blurb": "對前方單一目標施以致命一擊",
  "skill.monk.0": "暈眩連打",
  "skill.monk.0.blurb": "痛擊前方怪物，使其暈眩一段時間。",
  "skill.fist_master.0": "旋風踢",
  "skill.fist_master.0.blurb": "旋身踢擊，打中周圍所有目標。",
  "skill.fist_master.1": "白熱拳",
  "skill.fist_master.1.blurb": "將全力的一拳灌入單一目標。",
  "skill.fist_master.2": "天崩拳",
  "skill.fist_master.2.blurb": "以天崩地裂之拳重擊周圍並擊暈",
  "skill.guardian.0": "盾擊",
  "skill.guardian.0.blurb": "以盾牌重擊前方的一個怪物，使其長時間暈眩。",
  "skill.guardian.1": "守護戰吼",
  "skill.guardian.1.blurb": "以戰吼衝擊周圍，並回復自己與夥伴的體力。",
  "skill.guardian.2": "不屈城牆",
  "skill.guardian.2.blurb": "重擊盾牌，長時間定住周圍並大量回復自己與隊友",
  "skill.tracker.0": "陷阱之箭",
  "skill.tracker.0.blurb": "射中一個目標，將其定在原地。",
  "skill.tracker.1": "扇形射擊",
  "skill.tracker.1.blurb": "向前方大範圍傾瀉箭矢。",
  "skill.tracker.2": "獵人之網",
  "skill.tracker.2.blurb": "向前方大範圍射出網箭，長時間定住敵人",
  "skill.warder.0": "結界波動",
  "skill.warder.0.blurb": "展開結界衝擊周圍，並短暫將其束縛。",
  "skill.warder.1": "守護結界",
  "skill.warder.1.blurb": "大幅回復自己與附近夥伴的體力。",
  "skill.warder.2": "絕對結界",
  "skill.warder.2.blurb": "展開大範圍結界，長時間定住周圍並回復自己與隊友",
  "skill.high_priest.0": "淨化之光",
  "skill.high_priest.0.blurb": "以光束燒灼一個目標，並稍微回復自己與夥伴。",
  "skill.paladin.1": "審判之錘",
  "skill.paladin.1.blurb": "揮下光之重錘，使周圍全數暈眩。",
  "skill.paladin.2": "天上審判",
  "skill.paladin.2.blurb": "降下天光，擊暈周圍敵人並回復隊友",
  "skill.scout.0": "煙幕",
  "skill.scout.0.blurb": "施放煙幕，使周圍怪物暫時停下。",
  "skill.scout.1": "飛刀連擲",
  "skill.scout.1.blurb": "將短劍呈扇形遠遠擲出。",
  "skill.scout.2": "刀刃風暴",
  "skill.scout.2.blurb": "向前方遠處傾瀉刀刃，使敵人短暫停頓",
  "skill.iron_monk.0": "鐵山靠",
  "skill.iron_monk.0.blurb": "以肩撞擊，使前方大範圍暈眩。",
  "skill.iron_monk.1": "金剛不壞",
  "skill.iron_monk.1.blurb": "爆發氣勁衝擊周圍，並回復自己與夥伴的體力。",
  "skill.iron_monk.2": "不動明王",
  "skill.iron_monk.2.blurb": "以不動之氣定住周圍，並大量回復自己與隊友",
  "class.paths": "Lv{n} 轉職・二選一",
  "skills.pathSlot": "轉職技能 {n}",
  "skills.afterAdvance": "Lv{n} 轉職後學會",

  "job.berserker": "狂戰士",
  "job.guardian": "守護騎士",
  "job.sniper": "狙擊手",
  "job.tracker": "森林追蹤者",
  "job.elementalist": "元素術士",
  "job.warder": "結界術士",
  "job.high_priest": "大祭司",
  "job.paladin": "聖騎士",
  "job.assassin": "刺客",
  "job.scout": "斥候",
  "job.fist_master": "拳聖",
  "job.iron_monk": "鐵壁修士",

  "item.heal": "回復體力 {n}",
  "item.potion_small": "小型藥水",
  "item.potion_big": "大型藥水",
  "item.weapon_1": "學徒的武器",
  "item.weapon_2": "林守的武器",
  "item.weapon_3": "蘑菇王的武器",
  "item.weapon_4": "鋼製武器",
  "item.weapon_5": "岩心武器",
  "item.armor_1": "皮甲",
  "item.armor_2": "林守的護甲",
  "item.armor_3": "蘑菇王的護甲",
  "item.armor_4": "鋼製護甲",
  "item.armor_5": "岩心護甲",
  "item.stone": "強化石",
  "item.stone.blurb": "強化裝備的材料。所有狩獵場。",
  "item.jelly": "史萊姆凝膠",
  "item.jelly.blurb": "製作材料。森林原野 1。",
  "item.silk": "蜘蛛絲",
  "item.silk.blurb": "製作材料。森林原野 2。",
  "item.core": "岩心石",
  "item.core.blurb": "製作材料。深邃森林。",
  "item.spore": "蘑菇王的孢子",
  "item.spore.blurb": "製作材料。蘑菇王。",

  "monster.green_blob": "綠史萊姆",
  "monster.mushnub": "小蘑菇",
  "monster.rat": "野鼠",
  "monster.frog": "青蛙",
  "monster.spider": "森林蜘蛛",
  "monster.snake": "毒蛇",
  "monster.wasp": "黃蜂",
  "monster.bat": "蝙蝠",
  "monster.goleling": "魔像幼體",
  "monster.dire_spider": "巨型毒蛛",
  "monster.venom_snake": "劇毒蛇",
  "monster.hornet": "大虎頭蜂",
  "monster.vampire_bat": "吸血蝙蝠",
  "monster.stone_golem": "岩石魔像",
  "monster.mushnub_guard": "蘑菇護衛",
  "monster.mushroom_king": "蘑菇王",
  "monster.grove_guardian": "淨化守護者",
  "monster.guild_dragon": "遠古巨龍",
  "monster.guild_yeti": "雪山雪怪",
  "monster.guild_glub": "長老咕嚕",
  "monster.glub_brood": "小咕嚕",

  "zone.village": "綠林村",
  "zone.forest1": "森林原野 1",
  "zone.forest2": "森林原野 2",
  "zone.forest3": "深邃森林",
  "zone.boss": "蘑菇王的空地",
  "zone.arena": "公會首領競技場",
  "zone.dungeon": "試煉地下城",
  "zone.outpost": "雪山前哨站",
  "zone.snow1": "雪山山麓",
  "zone.snow2": "冰之峽谷",
  "zone.snow3": "萬年雪峰",
  "zone.snowboss": "冰河祭壇",
  "npc.frost_merchant": "商人艾瑞克",
  "npc.frost_merchant.role": "商店",
  "npc.captain": "隊長布蘭",
  "npc.captain.role": "任務",
  "npc.frost_smith": "鐵匠英格",
  "npc.frost_smith.role": "強化·製作",
  "npc.frost_merchant.hello": "「這麼冷還來啦。藥水多帶一些。」",
  "npc.frost_smith.hello": "「雪山的鐵像冰一樣硬。帶霜之結晶來就行。」",
  "monster.frost_blob": "霜史萊姆",
  "monster.snow_hare": "雪兔",
  "monster.snow_wolf": "雪原狼",
  "monster.frost_spider": "霜蜘蛛",
  "monster.frost_bat": "霜蝙蝠",
  "monster.penguin_brute": "企鵝戰士",
  "monster.frost_snake": "冰結蛇",
  "monster.ice_golem": "冰魔像",
  "monster.peak_yeti": "峰頂雪怪",
  "monster.frost_drake": "霜飛龍",
  "monster.glacier_alpaking": "冰河羊駝王",
  "monster.frost_emperor": "冰河皇帝",
  "item.weapon_6": "霜牙武器",
  "item.armor_6": "霜牙鎧甲",
  "item.weapon_7": "冰河王武器",
  "item.armor_7": "冰河王鎧甲",
  "item.frost_shard": "霜之結晶",
  "item.frost_shard.blurb": "製作材料。雪山狩獵場",
  "item.snow_fur": "雪原毛皮",
  "item.snow_fur.blurb": "製作材料。雪山山麓、冰之峽谷",
  "item.ever_ice": "萬年冰",
  "item.ever_ice.blurb": "7級製作材料。萬年雪峰",

  "npc.merchant": "商人漢斯",
  "npc.merchant.role": "商店",
  "npc.elder": "村長瑪爾塔",
  "npc.elder.role": "任務",
  "npc.smith": "鐵匠沃爾夫",
  "npc.smith.role": "強化・製作",

  "world.name": "綠林",

  "quest.0": "史萊姆討伐",
  "quest.0.goal": "森林原野 1 的綠史萊姆 15 隻",
  "quest.1": "清剿小蘑菇",
  "quest.1.goal": "森林原野 1 的小蘑菇 20 隻",
  "quest.2": "原野的麻煩",
  "quest.2.goal": "野鼠或青蛙 40 隻",
  "quest.3": "深林偵察",
  "quest.3.goal": "森林原野 2 的森林蜘蛛或毒蛇 50 隻",
  "quest.4": "天空的狩獵",
  "quest.4.goal": "黃蜂或蝙蝠 60 隻",
  "quest.5": "石之精靈",
  "quest.5.goal": "魔像幼體 60 隻",
  "quest.6": "討伐蘑菇王",
  "quest.6.goal": "蘑菇王空地的蘑菇王",
  "quest.7": "深邃森林的蛛穴",
  "quest.7.goal": "深邃森林的巨型毒蛛或劇毒蛇 60 隻",
  "quest.8": "遮天之翼",
  "quest.8.goal": "大虎頭蜂或吸血蝙蝠 80 隻",
  "quest.9": "森林的守護石",
  "quest.9.goal": "岩石魔像 60 隻",
  "quest.10": "魔像之心",
  "quest.10.goal": "岩石魔像 100 隻",
  "quest.11": "再討蘑菇王",
  "quest.11.goal": "擊倒蘑菇王 3 次",
  "quest.12": "深邃森林之主",
  "quest.12.goal": "深邃森林的怪物 200 隻",
  "quest.13": "雪中的第一步",
  "quest.13.goal": "霜史萊姆・雪兔60隻",
  "quest.14": "雪原的獵手",
  "quest.14.goal": "雪原狼・霜蜘蛛80隻",
  "quest.15": "守住峽谷入口",
  "quest.15.goal": "霜蝙蝠・企鵝戰士80隻",
  "quest.16": "峽谷深處",
  "quest.16.goal": "冰結蛇・冰魔像90隻",
  "quest.17": "移動的冰牆",
  "quest.17.goal": "冰魔像100隻",
  "quest.18": "峰頂的巨人",
  "quest.18.goal": "峰頂雪怪80隻",
  "quest.19": "天空與冰之王",
  "quest.19.goal": "霜飛龍・冰河羊駝王100隻",
  "quest.20": "冰河皇帝",
  "quest.20.goal": "在冰河祭壇擊敗冰河皇帝",
  "daily.forest1": "巡邏：森林原野 1",
  "daily.forest1.goal": "森林原野 1 的怪物 30 隻",
  "daily.forest2": "巡邏：森林原野 2",
  "daily.forest2.goal": "森林原野 2 的怪物 40 隻",
  "daily.forest3": "巡邏：深邃森林",
  "daily.forest3.goal": "深邃森林的怪物 50 隻",
  "daily.snow1": "巡邏：雪山山麓",
  "daily.snow1.goal": "雪山山麓的怪物50隻",
  "daily.snow2": "巡邏：冰之峽谷",
  "daily.snow2.goal": "冰之峽谷的怪物60隻",
  "daily.snow3": "巡邏：萬年雪峰",
  "daily.snow3.goal": "萬年雪峰的怪物60隻",

  "common.loading": "載入中…",
  "common.gold": "{n} 金幣",
  "wallet.gold": "金幣（點擊開啟背包）",
  "wallet.gems": "寶石（點擊開啟坐騎・寶石商店）",
  "common.nothing": "無",
  "problem.unavailable": "現在無法進行",
  "problem.max_plus": "已無法再強化",
  "problem.not_near": "要靠近鐵匠才能進行",
  "problem.not_enough_gold": "金幣不足",
  "problem.not_in_village": "商店在村子裡",
  "problem.no_item": "背包裡沒有",
  "problem.bag_full": "背包放不下了（每格最多 99 個）",
  "problem.too_low_advance": "Lv{n} 起可以轉職",

  "slot.weapon": "武器",
  "slot.armor": "護甲",

  "bag.title": "背包",
  "bag.power": "戰鬥力 {n}",
  "bag.job": "轉職",
  "bag.advanceAt": "到 Lv{at} 就能轉職（目前 Lv{level}）",
  "bag.pickPath": "請選擇轉職的道路。一旦選定就不能更改。",
  "bag.confirmPath": "確定轉職為{name}嗎？之後無法更改。",
  "bag.advanceGo": "轉職",
  "bag.unequip": "卸下",
  "bag.empty": "背包是空的",
  "bag.pickHint": "點選物品，這裡會顯示說明與用法。",
  "bag.drink": "飲用",
  "bag.equip": "裝備",
  "bag.sell": "賣出（{n}）",
  "bag.keys": "Q：喝藥水 · I：背包",
  "item.trade": "可交易",
  "item.bound": "不可交易",
  "forge.tradeChance": "製作的裝備有{pct}機率可交易。",

  "shop.title": "村莊商店",
  "shop.buy": "購買",
  "shop.buyTen": "10 個",
  "shop.note": "怪物會掉落金幣與裝備。賣出請從背包。",

  "forge.title": "鐵匠鋪",
  "forge.stones": "強化石 {n} 個",
  "forge.enhance": "強化",
  "forge.craft": "製作",
  "forge.noGear": "沒有裝備任何東西",
  "forge.chance": "+{to} 成功 {pct}",
  "forge.breakRisk": "失敗時損毀 {pct}",
  "forge.maxed": "已達最高強化（+{n}）",
  "forge.note": "從 +{n} 起，失敗可能損毀裝備。強化石由所有狩獵場的怪物掉落。",
  "forge.success": "強化成功！",
  "forge.fail": "強化失敗… 裝備沒有損傷",
  "forge.broken": "強化失敗… 裝備損毀了",
  "forge.working": "強化中…",
  "forge.crafted": "{name} 製作完成！",

  "common.retry": "再試一次",
  "common.toMenu": "回到選單",
  "common.menu": "選單",
  "common.off2": "關閉",

  "problem.zone_full": "所有頻道都滿了。請稍後再試",
  "problem.not_near_portal": "請站到傳送門旁",
  "problem.too_low": "等級不足",
  "problem.cannotTravel": "現在無法前往",
  "problem.enter": "無法進入世界",
  "problem.enterWith": "無法進入世界（{error}）",
  "problem.connect": "無法連上遊戲伺服器。請檢查網路後再試一次。",
  "problem.tooFast": "請說慢一點",
  "problem.cannotSend": "無法送出",

  "world.entering": "正在進入世界…",
  "world.loading": "正在載入森林… {n}%",
  "world.travelling": "移動中…",
  "world.channel": "頻道 {n}",
  "world.talk": "{name} — {role} · 對話 (E)",
  "world.portalLevel": "{zone} — Lv{n} 起可前往",
  "world.portalTo": "通往{zone}的路",
  "world.blocking": "格擋中",

  "menu.map": "地圖",
  "menu.ranking": "排行",
  "menu.quests": "任務",
  "menu.skills": "技能",
  "menu.forge": "鐵匠鋪",
  "menu.bag": "背包",
  "menu.sleep": "省電",
  "menu.news": "公告",
  "news.title": "更新公告",
  "menu.mail": "郵件",
  "mail.title": "郵箱",
  "mail.empty": "沒有郵件",
  "mail.failed": "無法開啟郵箱",
  "mail.claim": "領取",
  "mail.claimAll": "全部領取",
  "mail.daysLeft": "剩餘{n}天",
  "mail.gift": "禮物",
  "mail.gold": "{n} 金幣",
  "problem.no_mail": "這封郵件已領取或已消失",
  "menu.market": "交易所",
  "market.title": "交易所",
  "market.buy": "購買",
  "market.sell": "出售",
  "market.mine": "我的上架",
  "market.weapon": "武器",
  "market.armor": "護甲",
  "market.material": "材料",
  "market.all": "全部",
  "market.minPlus": "+{n}以上",
  "market.empty": "沒有商品",
  "market.failed": "無法開啟交易所",
  "market.left": "剩餘{h}小時{m}分",
  "market.leftMin": "剩餘{m}分",
  "market.buyGo": "購買",
  "market.mineTag": "我的",
  "market.confirm": "要以{price}寶石購買{name}嗎？購買的物品會以郵件送達。",
  "market.bought": "購買成功！請到郵箱領取。",
  "market.page": "{n} / {of}",
  "market.each": "每個",
  "market.nothingToSell": "沒有可交易的裝備或材料。怪物掉落的材料，以及部分掉落、製作的裝備可交易。",
  "market.pick": "請選擇要出售的物品",
  "market.price": "價格（寶石）",
  "market.count": "數量",
  "market.fee": "手續費 {fee} · 可得 {gets}",
  "market.list": "上架",
  "market.listed": "已上架",
  "market.limit": "上架 {n}/{max}",
  "market.cancel": "下架",
  "market.canceled": "已下架，會以郵件退回。",
  "market.none": "沒有上架的商品",
  "market.ended": "已到期（即將以郵件退回）",
  "market.note": "售出所得會扣除5%手續費後以寶石郵寄。商品48小時後下架並以郵件退回。",
  "problem.listing_gone": "這件商品已售出或已下架",
  "problem.too_many": "剩下的沒那麼多，已被別人先買走。",
  "market.priceEach": "單價（寶石）",
  "market.total": "合計 {n}",
  "market.howMany": "要買幾個？（剩 {n} 個）",
  "market.max": "最多",
  "problem.listing_limit": "最多只能上架{n}件",
  "problem.bad_price": "請再確認價格",
  "problem.not_tradable": "這件物品不可交易",
  "problem.own_listing": "不能購買自己的商品",
  "menu.guild": "公會",
  "guild.title": "公會",
  "guild.find": "尋找公會",
  "guild.search": "公會名稱",
  "guild.searchGo": "搜尋",
  "guild.none": "沒有公會",
  "guild.count": "{n}/{max}人",
  "guild.apply": "申請加入",
  "guild.applied": "已申請",
  "guild.myApplications": "我的申請",
  "guild.withdraw": "取消",
  "guild.create": "建立公會",
  "guild.createCost": "{n} 金幣",
  "guild.createGo": "建立",
  "guild.wait": "{time}起可以加入或建立公會",
  "guild.notice": "公告",
  "guild.noNotice": "沒有公告",
  "guild.editNotice": "編輯",
  "guild.saveNotice": "儲存",
  "guild.members": "成員 {n}/{max}",
  "guild.role.master": "會長",
  "guild.role.vice": "副會長",
  "guild.role.member": "成員",
  "guild.offline": "離線",
  "guild.applicants": "加入申請",
  "guild.accept": "接受",
  "guild.decline": "拒絕",
  "guild.kick": "踢出",
  "guild.makeVice": "設為副會長",
  "guild.makeMember": "設為成員",
  "guild.pass": "移交會長",
  "guild.confirmKick": "要踢出{name}嗎？",
  "guild.confirmPass": "要把會長移交給{name}嗎？你將成為成員。",
  "guild.leave": "退出",
  "guild.confirmLeave": "要退出公會嗎？24小時內無法加入其他公會。",
  "guild.disband": "解散",
  "guild.confirmDisband": "要解散公會嗎？無法復原。",
  "guild.yes": "是",
  "guild.failed": "無法載入公會資訊",
  "guild.rules": "公會由所有伺服器共用。每個角色可以加入一個公會。",
  "chat.channel": "頻道",
  "chat.guild": "公會",
  "problem.guild_name_invalid": "公會名稱為2~12個字，可用韓文、英文、數字、_",
  "problem.guild_name_taken": "這個公會名稱已被使用",
  "problem.in_guild": "你已經在公會裡了",
  "problem.no_guild": "沒有公會",
  "problem.guild_full": "公會已滿",
  "problem.guild_wait": "離開公會後需經過24小時",
  "problem.applied_limit": "最多只能申請3個公會",
  "problem.applicants_full": "該公會無法再接受申請",
  "problem.no_applicant": "這個申請已處理，或對方已加入其他公會",
  "problem.not_allowed": "你沒有這個權限",
  "problem.vice_limit": "副會長最多3人",
  "problem.master_must_pass": "會長必須先移交會長",
  "problem.guild_not_empty": "公會還有成員時無法解散",
  "guild.tab.members": "公會",
  "guild.tab.boss": "首領",
  "boss.guild_dragon": "遠古巨龍",
  "boss.guild_yeti": "雪山雪怪",
  "boss.guild_glub": "長老咕嚕",
  "boss.week": "本週首領",
  "boss.left": "剩餘體力 {n}%",
  "boss.down": "已擊敗！等待下週的首領",
  "boss.endsAt": "至{time}",
  "boss.today": "今天已挑戰（明天可以再進入）",
  "boss.ready": "今天可以挑戰 · 3分鐘 · Lv10以上",
  "boss.room": "{n}號房",
  "boss.seats": "{n}/{max}人",
  "boss.enter": "進入",
  "boss.ranking": "貢獻度",
  "boss.mine": "我的累計傷害 {n}",
  "boss.noRanking": "還沒有人挑戰",
  "boss.stages": "達到25、50、75%與擊敗時，本週參與者全員以郵件獲得獎勵。擊敗時獲得可交易裝備（貢獻前3名為最高級）。",
  "boss.hint": "地面出現紅色標示時請往外閃避！",
  "boss.leave": "離開",
  "boss.timeUp": "3分鐘結束了",
  "boss.fallen": "你倒下了",
  "boss.endNote": "造成的傷害已累積到公會首領。明天再來挑戰吧！",
  "boss.slain": "擊敗首領了！",
  "mail.guildBoss": "公會首領第{stage}階段獎勵",
  "mail.guildBossBody": "{boss}已被削減{pct}%。感謝一起奮戰！",
  "mail.guildBossSlain": "擊敗了{boss}！送上擊敗獎勵。",
  "problem.boss_down": "本週首領已被擊敗",
  "problem.entered_today": "今天已經挑戰過了",
  "problem.room_full": "該房間已滿",
  "problem.arena_over": "挑戰時間已結束",
  "mail.marketSold": "售出：{item}",
  "mail.marketSoldBody": "以{price}寶石售出。已扣除手續費{fee}寶石寄出。",
  "mail.marketBought": "購買：{item}",
  "mail.marketBoughtBody": "以{price}寶石購買。",
  "mail.marketReturned": "退回：{item}",
  "mail.marketReturnedBody": "未售出或已下架的商品退回給您。",
  "menu.settings": "設定",

  "death.fallen": "你倒下了",
  "death.lostXp": "失去了 {n} 經驗值",
  "death.lostNone": "沒有失去經驗值",
  "death.lossNote": "倒下會失去本級經驗值的 {n}%（等級不會下降）",
  "death.here": "原地復活 · {gold}",
  "death.hereNote": "以 {n}% 體力起身，怪物會暫時不攻擊你",
  "death.short": " · 金幣不足",
  "death.village": "在村莊復活 · 免費",

  "sleep.title": "省電模式",
  "sleep.elapsed": "經過時間",
  "sleep.xp": "獲得經驗值",
  "sleep.gold": "獲得金幣",
  "sleep.potions": "剩餘藥水",
  "sleep.potionCount": "{n} 個",
  "sleep.auto": "自動戰鬥",
  "sleep.hunting": "狩獵中",
  "sleep.dead": "你倒下了 — 點兩下查看",
  "sleep.hint": "點兩下畫面即可返回",

  "chat.placeholder": "對頻道說話",
  "chat.send": "傳送",
  "chat.open": "聊天",
  "chat.enterHint": "開始聊天",
  "lobby.deleteCharacter": "刪除 {name}",
  "delete.title": "刪除角色",
  "delete.warning": "「{name}」的等級、裝備與任務將全部消失，無法復原。若要刪除，請照樣輸入名稱。",
  "delete.confirm": "永久刪除",
  "problem.name_mismatch": "名稱不符",

  "quest.allDone": "所有任務完成",
  "quest.reportHere": "點擊向村長回報",
  "quest.reportInVillage": "點一下前往村裡的村長",
  "quest.seeking": "前往中…",
  "quest.goFind": "點擊前往",

  "pad.attack": "攻擊",
  "pad.block": "格擋",
  "pad.jump": "跳躍",
  "pad.auto": "自動",
  "pad.autoOn": "自動中",
  "pad.leftClick": "左鍵",
  "pad.rightClick": "右鍵",

  "map.tapToWalk": "點擊即可走到那裡",
  "map.portals": "區域出入口",
  "map.villagers": "村民",
  "map.you": "你",
  "map.close": "關閉 (N)",

  "bar.potion": "藥水",
  "bar.emptySlot": "空格",
  "bar.autoPotion": "自動藥水",
  "bar.autoPotionTitle": "自動藥水設定",
  "bar.autoPotionAt": "生命低於 {n}% 時會喝藥水",
  "bar.autoPotionOff": "（目前已關閉）",
  "bar.autoPotionTurnOn": "開啟自動藥水",
  "bar.autoPotionTurnOff": "關閉自動藥水",

  "skills.title": "技能",
  "skills.dragNote": "把學會的技能拖到下方的格子。",
  "skills.learnAt": "Lv{n} 學會",
  "skills.fromElder": "向村長學習",
  "skills.inSlot": "第 {n} 格",
  "skills.dragIn": "拖曳放入格子",
  "skills.cooldown": "冷卻 {n} 秒",
  "skills.remove": "取出",

  "common.next": "下一步",
  "common.accept": "接受",
  "common.decline": "拒絕",

  "lobby.newCharacter": "新角色",
  "lobby.needServer": "需要連上 Verse8 伺服器才能開始遊戲。",
  "conn.trying": "正在連接伺服器…",
  "conn.retrying": "與伺服器的連線已中斷，正在重新連線…",
  "conn.failed": "無法連接伺服器，請重新啟動遊戲。",
  "conn.restart": "重新啟動",
  "conn.lost": "連線已中斷，已返回標題畫面。",
  "lobby.accountFailed": "無法讀取帳號資料。請重新整理。",
  "lobby.accountLoading": "正在讀取帳號資料…",
  "lobby.loading": "正在載入村莊… {n}%",
  "lobby.tapToStart": "點擊畫面開始",
  "lobby.friends": "好友",
  "lobby.characters": "{world} · 角色 {n}/{max}",
  "lobby.createCharacter": "+ 建立角色",
  "lobby.start": "開始遊戲",
  "lobby.changeServer": "更換伺服器",
  "lobby.noCharacter": "建立角色，開始冒險吧。",
  "lobby.guestNote": "你尚未登入。現在建立的角色下次無法讀取。請先登入 Verse8 再開始。",


  "class.pick": "選擇職業",
  "class.weapon": "武器",
  "class.ranged": "遠程",
  "class.melee": "近戰",
  "class.damage": "攻擊力",
  "class.speed": "攻擊速度",
  "class.perSecond": "{n} 次/秒",
  "class.reach": "射程",
  "class.block": "格擋",
  "class.skillLine": "技能 {n} · {name}",
  "class.confirm": "選定這個職業",
  "class.onceNote": "職業在建立角色時決定一次。",
  "class.pickHint": "點擊角色來查看職業。",

  "look.title": "決定角色外觀",
  "look.spin": "拖曳可旋轉",
  "look.shape": "外觀",
  "look.random": "隨機",
  "look.making": "建立中…",
  "look.create": "建立角色",
  "look.onceNote": "外觀在建立角色後就不能更改。",
  "look.previous": "{part} 上一個",
  "look.next": "{part} 下一個",

  "part.gear": "飾品",
  "part.clothColor": "衣服顏色",
  "part.skin": "膚色",
  "part.weaponColor": "武器顏色",
  "look.default": "預設",
  "look.on": "配戴",
  "look.off": "取下",
  "look.grey": "無彩色",
  "look.dye": "染色 {n}",
  "look.skinLight": "白皙",
  "look.skinTan": "小麥色",
  "look.skinDark": "深色",
  "look.mine": "自己的樣子",
  "look.preset.light": "輕裝",
  "look.preset.shadow": "暗影",

  "name.title": "角色名稱",
  "name.note": "其他玩家與好友會以這個名字看到你。文字、數字或 _ 共 2～12 字，且不能與其他角色重複。",
  "name.placeholder": "名稱",
  "name.checking": "確認中…",

  "server.pick": "選擇伺服器",
  "server.note": "選同一台伺服器的玩家才會相遇。和朋友選同一台吧。",
  "server.entering": "進入中…",
  "server.recent": "最近遊玩",
  "server.quiet": "空閒",
  "server.busy": "普通",
  "server.full": "擁擠",
  "server.about": "{n}人在線",
  "server.recommended": "推薦",
  "server.failed": "無法選擇伺服器。請稍後再試一次",

  "common.add": "新增",
  "common.cancel": "取消",
  "common.remove": "刪除",
  "common.removeSure": "確定刪除",
  "common.noName": "（沒有名字）",
  "common.reward": "報酬：{what}",
  "common.xp": "{n} XP",

  "friends.title": "好友",
  "friends.needCharacter": "要新增好友，請先建立角色。",
  "friends.search": "以名稱新增好友",
  "friends.needServer": "好友需連上 Verse8 後才能使用。",
  "friends.loading": "正在讀取好友名單…",
  "friends.sent": "已送出好友邀請",
  "friends.bothWays": "雙方都送出邀請，已成為好友",
  "friends.nowFriends": "你和 {name} 成為好友了",
  "friends.incoming": "收到的邀請 {n}",
  "friends.list": "好友名單",
  "friends.online": "· 上線 {on}/{all}",
  "friends.none": "還沒有好友。試著用名稱新增吧。",
  "friends.isOnline": "上線",
  "friends.isOffline": "離線",
  "friends.outgoing": "送出的邀請",
  "friends.waiting": "等待中",

  "problem.friend_not_found": "找不到這個名稱",
  "problem.friend_self": "不能新增自己",
  "problem.already_friends": "已經是好友",
  "problem.friend_limit": "好友最多 {n} 位",
  "problem.request_limit": "對方收到的邀請太多了",
  "problem.no_request": "這個邀請已經處理過了",
  "problem.nickname_taken": "這個名稱已被使用",
  "problem.nickname_invalid": "可用文字、數字或 _ 共 2～12 字",
  "problem.character_limit": "這台伺服器無法再建立角色",
  "problem.retryLater": "現在無法進行。請稍後再試一次",
  "problem.saveFailed": "無法儲存。請稍後再試一次",
  "problem.not_near_elder": "請站到村長旁邊說話",
  "problem.quest_unfinished": "還沒有完成",
  "problem.cannotClaim": "現在無法領取",

  "rank.title": "排行榜",
  "rank.needServer": "連上 Verse8 後即可查看。",
  "rank.failed": "無法讀取排行榜。請稍後再開啟。",
  "rank.none": "還沒有累積經驗值的冒險者。",
  "rank.unranked": "未上榜",
  "rank.place": "第 {n} 名",
  "rank.nickname": "名稱",
  "rank.class": "職業",
  "rank.level": "等級",
  "rank.rank": "名次",
  "rank.server": "伺服器",
  "rank.xp": "經驗值",
  "rank.power": "戰鬥力",
  "rank.detailFailed": "無法讀取資料。",
  "rank.toList": "回到名單",

  "quests.title": "任務",
  "quests.daily": "每日任務 · 每天 0 點重新開始",
  "quests.claim": "領取報酬",
  "quests.claimedToday": "今天的報酬已領取",
  "quests.goReport": "去向村長回報",
  "quests.reportHint": "向村裡的村長回報即可領取報酬",
  "quests.goFind": "前往",
  "quests.allDone": "所有任務都完成了。",
  "quests.past": "已完成的任務",
  "quests.more": "還有 {n} 個任務。",
  "quests.complete": "任務完成！",
  "quests.reportHere": "向村長回報並領取報酬",
  "quests.reportInVillage": "向村裡的村長回報並領取報酬",
  "npc.merchant.hello": "「歡迎光臨！藥水、裝備應有盡有。」",
  "npc.smith.hello": "「打鐵要趁熱。強化還是製作，都交給我。」",
  "dialogue.shop": "查看商店",
  "dialogue.forge": "打開鐵匠鋪",
  "npc.elder.done": "「這座森林裡已經沒有能難倒你的了。謝謝你，獵人。」",
  "npc.elder.tutorial": "「你來了。學會這個技能，把藥水也帶上。打開技能視窗看看學到的技能，放在下方欄位裡就能馬上使用。」",
  "npc.elder.claim": "「{quest}，做得好！這是說好的報酬。」",
  "npc.elder.ask": "「{goal}，就拜託你了。」",

  "note.notHere": "這個區域沒有",
  "note.questLevel": "{zone}：Lv{n} 起可前往",
  "note.cannotWalk": "那裡去不了",
  "note.gotGold": "+{n} 金幣",
  "note.gotItem": "獲得 {name}",
  "portal.needsLevel": "（Lv{n}）",

  "error.startFailed": "無法啟動遊戲。",
  "error.reload": "重新載入",
  "rotate.hint": "把畫面轉成橫向會更好玩",
  "channel.title": "頻道",
  "channel.note": "同一頻道就能在任何區域相遇。切換後仍在原地。",
  "channel.here": "目前所在",
  "channel.full": "已滿",
  "channel.friends": "好友：{names}",
  "keys.channel": "切換頻道",
  "problem.channel_full": "該頻道已滿。請選擇其他頻道",
  "friends.where": "{server} · {channel} · {zone}",
  "common.prevPage": "上一頁",
  "common.nextPage": "下一頁",
  "friends.noIncoming": "沒有收到的邀請。",
  "friends.noOutgoing": "沒有送出的邀請。",
  "quests.tabNow": "進行中",
  "quests.tabDaily": "每日",
  "quests.tabPast": "已完成",
  "quests.noPast": "還沒有完成的任務。",

  "tutorial.title": "第一步",
  "tutorial.step0": "與村長交談",
  "tutorial.step1": "打開技能視窗，把新技能拖到 1 號欄位",
  "tutorial.step1Placed": "打開技能視窗看看新技能，它已經在 1 號欄位了",
  "tutorial.step2": "把技能欄和藥水欄往下拖，開啟自動使用",
  "tutorial.step3": "按下自動戰鬥按鈕",
  "tutorial.doneTitle": "準備完成！",
  "tutorial.doneHint": "看看村長的第一個請託",

  "menu.grove": "森林",
  "grove.title": "森林淨化",
  "grove.kills": "本週 {n} / {goal} 隻",
  "grove.daysLeft": "剩 {n} 天",
  "grove.stage.1": "30% 花開，金幣 200",
  "grove.stage.2": "60% 天空放晴，開放建地",
  "grove.stage.3": "100% 淨化守護者（頻道 1），金幣 500",
  "grove.hazeHint": "擊敗怪物可淨化森林，\n達到60%時霧氣散去（本週 {n}%）",
  "grove.village": "村莊重建",
  "grove.building.herbalist": "藥草鋪",
  "grove.building.training": "訓練場",
  "grove.building.inn": "旅店",
  "grove.building.watchtower": "瞭望塔",
  "grove.perk.herbalist": "藥水 -20%",
  "grove.perk.training": "狩獵經驗 +5%",
  "grove.perk.inn": "倒下損失經驗減半",
  "grove.perk.watchtower": "小地圖顯示首領",
  "grove.closed": "未開放",
  "grove.building": "建造中 {n}%",
  "grove.done": "完工",
  "grove.failed": "無法載入",
  "dialogue.donate": "捐獻",
  "donate.title": "建造{building}",
  "donate.have": "持有 {n}",
  "donate.gold": "金幣",
  "donate.done": "謝謝！會記住你的名字。",
  "problem.nothing": "請選擇要捐的東西",
  "problem.no_building": "目前沒有建造中的建築",
  "keys.ride": "騎上 / 下坐騎",
  "menu.mounts": "坐騎",
  "pad.ride": "騎乘",
  "pad.dismount": "下坐騎",
  "problem.not_enough_gems": "寶石不足",
  "problem.no_mount": "沒有這個坐騎",
  "mount.none": "沒有可騎的坐騎。在馬廄孵蛋即可獲得。",
  "mount.rideHint": "按 T 或騎乘按鈕上下坐騎。攻擊或被攻擊時會下坐騎。",
  "mount.stats": "攻擊 +{p}% · 生命 +{h}",
  "mount.statsNote": "選中的坐騎即使不騎也會提升攻擊力和生命值。",
  "mount.speed": "速度 ×{n}",
  "mount.riding": "騎乘中",
  "mount.pick": "騎這個",
  "mount.notOwned": "未擁有",
  "mount.new": "新坐騎！{tier} {name}",
  "mount.newBadge": "新坐騎！",
  "mount.repeatBadge": "已擁有",
  "mount.nextStar": "下一顆★{n}：攻擊 +{p}% · 體力 +{h}",
  "mount.star": "{name}突破到★{n}！加成提升了",
  "mount.starBadge": "突破！",
  "mount.repeat": "已擁有{name} · 返還寶石 {n} 個",
  "mount.odds": "抽取機率",
  "mount.repeatNote": "抽到已擁有的坐騎會突破，星級(★)提升、加成變大（最高★{max}，★{max}為2倍）。★{max}之後退還{n}顆寶石。",
  "mount.pack": "寶石 {n} 個",
  "boss.board.mine": "我的公會",
  "boss.board.guilds": "全部公會",
  "boss.board.players": "全部個人",
  "boss.thisWeek": "本週 ▸ 上週",
  "boss.lastWeek": "上週 ▸ 本週",
  "boss.killed": "已擊殺",
  "boss.myGuildRank": "我的公會第 {n} 名",
  "boss.leagueNote": "每週結束時，公會前3名的成員（第1名 寶石{g1}）與個人前3名（第1名 寶石{p1}）可獲得寶石。越快擊殺、打得越多，排名越前。",
  "announce.guildWeek": "公會<{guild}>奪得上週公會首領第一名！",
  "mail.leagueGuild": "公會首領週排行第 {n} 名（公會）",
  "mail.leagueGuildBody": "公會<{guild}>上週獲得第 {n} 名，這是獎勵寶石。",
  "mail.leaguePlayer": "公會首領週排行 個人第 {n} 名",
  "mail.leaguePlayerBody": "你是上週公會首領傷害個人第 {n} 名，這是獎勵寶石。",
  "mount.vipPerk.mark": "名字旁顯示VIP",
  "mount.vipPerk.bag": "背包裝備格 +10",
  "mount.vipPerk.daily10": "每天寶石10個",
  "mount.vipPerk.revive": "原地復活免費",
  "mount.vipPerk.might": "攻擊力·最大體力 +10%，金色名字",
  "mount.vipPerk.daily30": "每天寶石30個",
  "mount.vipPerk.enhance5": "強化成功率 +5%p",
  "mount.vipPerk.noFee": "交易所手續費全免",
  "mount.vipPerk.daily50": "強化成功率 +10%p，每天寶石50個",
  "mount.vipPerk.mount": "專屬神話坐騎",
  "mail.vipDaily": "VIP {n} 今日寶石",
  "mail.vipDailyBody": "VIP福利：每天首次登入都會收到寶石。",
  "market.noFee": "VIP免手續費 · 可得寶石 {gets}",
  "mount.vipGift": "專屬神話坐騎 {name}",
  "mount.name.celestial_dragon": "天上之龍",
  "mount.vipOnly": "VIP {n} 專屬（抽不到）",
  "announce.mythic": "[{server}] {name} 獲得了神話坐騎 {mount}！！",
  "announce.powerTop": "[{server}] {name} 以戰鬥力 {n} 登上戰鬥力第一！",
  "mount.hatch10": "{n}連孵化",
  "mount.hatch10Note": "9折 · 保底稀有以上1個",
  "mount.pity": "傳說保底剩 {legendary} 次 · 神話保底剩 {mythic} 次",
  "mount.vipNeed": "所需寶石",
  "mount.vipPerks": "福利",
  "mount.vipAnnounced": "達成時全服公告",
  "mount.vipShow": "各級福利 ▾",
  "mount.vipHide": "收起 ▴",
  "rank.tabLevel": "等級",
  "rank.tabPower": "戰鬥力",
  "mount.tier.mythic": "神話",
  "mount.name.golden_dragon": "黃金龍",
  "mount.name.void_emperor": "深淵皇帝",
  "announce.vip": "[{server}] {name} 成為 VIP {n}！",
  "mail.pass": "月卡：今日寶石",
  "mail.passBody": "月卡期間內，每天首次登入都會收到寶石。",
  "forge.protect": "用寶石保護 +{n} 以上的強化不被破壞",
  "forge.protected": "防破壞 · 寶石 {n}",
  "mount.vipBonus": "狩獵經驗與金幣 +{n}%",
  "mount.vipNext": "{have} / {need}",
  "mount.first2x": "首購 2 倍",
  "mount.firstGets": "首購得 {n} 個",
  "mount.pass": "月卡",
  "mount.passWhat": "立得寶石 {now} · {days} 天每天 {daily} · 經驗 +{xp}%",
  "mount.passLeft": "剩 {n} 天（購買可延長）",
  "mount.gemsComing": "正在確認購買…",
  "mount.stable": "馬廄",
  "mount.tab.stable": "已有坐騎",
  "mount.tab.hatch": "孵蛋",
  "mount.tab.shop": "寶石商店",
  "mount.gemsTitle": "持有寶石",
  "mount.hatchLede": "一顆蛋孵出一隻坐騎。等級越高跑得越快。",
  "mount.hatch": "孵化",
  "mount.needGems": "寶石不足 · 前往寶石商店",
  "mount.bonus": "+{n}% 贈送",
  "mount.shopNote": "使用 VX 支付。支付完成後寶石很快到帳。",
  "mount.tier.base": "基礎",
  "mount.tier.common": "普通",
  "mount.tier.rare": "稀有",
  "mount.tier.epic": "史詩",
  "mount.tier.legendary": "傳說",
  "mount.name.deer": "鹿",
  "mount.name.pig": "豬",
  "mount.name.chicken": "雞",
  "mount.name.penguin": "企鵝",
  "mount.name.panda": "熊貓",
  "mount.name.crab": "螃蟹",
  "mount.name.yeti": "雪人",
  "mount.name.drake": "幼龍",
  "mount.name.cat": "貓",
  "mount.name.dog": "狗",
  "mount.name.pigeon": "鴿子",
  "mount.name.armabee": "鎧甲蜂",
  "mount.name.glub": "咕嚕",
  "mount.name.squidle": "翼烏賊",
  "mount.name.hywirl": "旋風",
  "mount.name.alpaking": "羊駝王",
  "mount.name.queen_armabee": "鎧甲蜂后",
  "mount.name.elder_glub": "遠古咕嚕",
  "mount.name.alpaking_emperor": "羊駝皇帝",
  "mount.name.dragon": "龍",

  "menu.rewards": "獎勵",
  "rewards.title": "簽到・成就",
  "rewards.tab.attendance": "簽到簿",
  "rewards.tab.achievements": "成就",
  "rewards.failed": "無法讀取",
  "rewards.gems": "寶石{n}個",
  "attend.today": "今天是第{n}天簽到！獎勵已透過郵件寄出。",
  "attend.notYet": "今天第一次進入世界時會蓋上印章。",
  "attend.day": "第{n}天",
  "attend.stamped": "已簽到",
  "attend.foot": "中間缺席也會接著蓋章。集滿28天後開始新的簽到簿。累計簽到{n}天",
  "mail.attendance": "簽到第{n}天獎勵",
  "mail.attendanceBody": "謝謝你今天也來了，明天見！",
  "ach.lead": "已領取成就 {n} / {of}",
  "ach.steps": "第{n}/{of}階段",
  "ach.done": "完成",
  "ach.claim": "領取",
  "ach.level": "成長",
  "ach.level.goal": "達到{n}級",
  "ach.quests": "村莊的委託",
  "ach.quests.goal": "完成{n}個主線任務",
  "ach.kills": "獵人",
  "ach.kills.goal": "擊敗{n}隻怪物",
  "ach.mushroom_king": "狩獵蘑菇王",
  "ach.grove_guardian": "與守護者相遇",
  "ach.frost_emperor": "冰河征服者",
  "ach.boss.goal": "擊敗{boss}{n}次",
  "ach.dailies": "勤勉的一天",
  "ach.dailies.goal": "領取每日任務獎勵{n}次",
  "ach.plus": "鐵匠的朋友",
  "ach.plus.goal": "裝備強化至+{n}",
  "ach.advanced": "新的道路",
  "ach.advanced.goal": "完成轉職",
  "ach.guild": "夥伴",
  "ach.guild.goal": "加入公會",
  "ach.mounts": "坐騎收藏家",
  "ach.mounts.goal": "擁有{n}種坐騎",
  "ach.star5": "突破極限",
  "ach.star5.goal": "★5坐騎{n}隻",
  "ach.attend": "全勤獎",
  "ach.attend.goal": "累計簽到{n}天",
  "mount.hatchTicket": "用召喚券孵化",
  "mount.tickets": "召喚券{n}張",
  "rewards.tickets": "坐騎召喚券{n}張",
  "attend.ticketDays": "坐騎召喚券在每週第4・7天發放（每張簽到簿{n}張，在馬廄無需寶石即可孵化）",
  "problem.no_ticket": "沒有召喚券",
  "mount.skip": "跳過動畫",
  "mount.skipHint": "點擊畫面即可立即查看結果",
  "ach.claimAll": "全部領取（{n}）",
  "menu.party": "隊伍",
  "party.title": "隊伍",
  "party.lead": "最多{n}人。同一區域的隊員共享經驗與金幣（人數越多加成越高），任務擊殺數也一起增加。",
  "party.away": "離線",
  "party.otherChannel": "其他頻道（{n}）",
  "party.leader": "隊長",
  "party.invited": "{name}邀請你加入隊伍",
  "party.accept": "接受",
  "party.decline": "拒絕",
  "party.members": "隊員 {n}/{of}",
  "party.you": "我",
  "party.here": "就在這裡",
  "party.pass": "轉讓隊長",
  "party.kick": "移出",
  "party.leave": "離開隊伍",
  "party.left": "你已離開隊伍",
  "party.none": "還沒有隊伍。在下方邀請同頻道的玩家吧。",
  "party.nearby": "頻道{n}中的玩家",
  "party.onlyLeader": "只有隊長可以邀請",
  "party.noOne": "沒有可邀請的人",
  "party.invite": "邀請",
  "party.invitedBadge": "已邀請",
  "party.inviteSent": "已向{name}發送邀請",
  "problem.party_full": "隊伍已滿",
  "problem.in_party": "已經在隊伍中",
  "problem.no_invite": "邀請已過期或已失效",
  "problem.no_party": "你不在隊伍中",
  "menu.dungeon": "地下城",
  "dungeon.title": "試煉地下城",
  "dungeon.lead": "從所有伺服器自動配對等級相近的最多4人，在5分鐘內擊敗{n}波怪物和首領。",
  "dungeon.tooLow": "{n}級起可進入",
  "dungeon.bracket.low": "初級（10~29級）",
  "dungeon.bracket.mid": "中級（30~49級）",
  "dungeon.bracket.high": "高級（50級~）",
  "dungeon.boss": "首領：{boss}",
  "dungeon.runsLeft": "今日剩餘次數 {n}/{of}",
  "dungeon.rewards": "通關獎勵",
  "dungeon.rewardLine": "{gold}金幣・強化石{stones}個・{pct}%機率獲得裝備",
  "dungeon.bonus": "{time}內通關金幣+50%，當天首次通關獲得寶石{n}個",
  "dungeon.queue": "開始配對",
  "dungeon.cancel": "取消",
  "dungeon.waiting": "配對中… {time}",
  "dungeon.waitingNote": "30秒內湊不齊4人時，就由已到的人出發，空位由[傭兵]AI補上。「單人進入」會立即與傭兵一同進入。",
  "merc.tag": "[傭兵]",
  "dungeon.solo": "單人進入",
  "dungeon.soloParty": "與隊伍進入",
  "dungeon.matched": "配對成功！{names}",
  "dungeon.enter": "進入",
  "dungeon.waitingOthers": "正在等待其他人… {n}秒",
  "dungeon.going": "正在進入…",
  "dungeon.wave": "第{n}/{of}波",
  "dungeon.bossWave": "首領",
  "dungeon.left": "剩餘怪物 {n}",
  "dungeon.leave": "離開",
  "dungeon.cleared": "通關！",
  "dungeon.clearNote": "通關時間 {time}。獎勵已透過郵件寄出。",
  "dungeon.failed": "失敗",
  "dungeon.failNote": "時間已到或全員倒下。",
  "mail.dungeon": "試煉地下城通關獎勵",
  "mail.dungeonBody": "你通關了地下城，辛苦了！",
  "problem.no_runs": "今日次數已用完",
  "problem.in_dungeon": "已在地下城配對中",
  "problem.no_match": "配對已結束或不存在",
  "problem.dungeon_over": "地下城已經結束",
};
