import type { Bundle } from "./ko";

export const zhHant: Bundle = {
  "common.close": "關閉",
  "common.back": "返回",
  "common.on": "開啟",
  "common.off": "關閉",
  "common.none": "關",

  "settings.title": "設定",
  "settings.sound": "音效",
  "settings.music": "背景音樂",
  "settings.effects": "音效",
  "settings.controls": "操作",
  "settings.sensitivity": "滑鼠靈敏度",
  "settings.times": "{n}倍",
  "settings.screen": "畫面",
  "settings.brightness": "亮度",
  "settings.quality": "畫質",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "越低越省效能與電量。會改變樹木與草地的完整繪製距離，以及畫面解析度。",
  "settings.shown": "顯示",
  "settings.showNames": "其他玩家名稱",
  "settings.damageNumbers": "傷害數字",
  "settings.language": "語言",
  "settings.keys.show": "顯示快捷鍵",
  "settings.keys.hide": "隱藏快捷鍵",
  "settings.defaults": "預設值",
  "settings.exit": "回到選單",

  "keys.move": "移動",
  "keys.jump": "跳躍",
  "keys.click": "左鍵 / 右鍵",
  "keys.attackGuard": "攻擊 / 格擋",
  "keys.skills": "技能",
  "keys.potion": "藥水",
  "keys.talk": "對話",
  "keys.auto": "自動戰鬥",
  "keys.quest": "前往任務・回報",
  "keys.chat": "聊天",
  "keys.menu": "展開選單",
  "keys.closeWindow": "關閉視窗",
  "keys.map": "地圖",
  "keys.panels": "排行 / 任務 / 技能 / 鐵匠鋪 / 背包",
  "keys.powerSave": "省電模式",
  "keys.settings": "設定",

  "list.join": "、",
  "stat.power": "攻擊力 +{n}%",
  "stat.hp": "體力 +{n}",
  "stat.guard": "受到傷害 -{n}%",
  "stat.heal": "治療量 +{n}%",

  "class.warrior": "戰士",
  "class.ranger": "弓箭手",
  "class.wizard": "法師",
  "class.cleric": "牧師",
  "class.rogue": "盜賊",
  "class.monk": "武鬥家",
  "class.warrior.blurb": "長劍與盔甲。站穩腳步一路砍過去。",
  "class.ranger.blurb": "從遠處射箭。被貼近就弱了。",
  "class.wizard.blurb": "以法杖射出魔彈。慢，但打得遠。",
  "class.cleric.blurb": "治療自己與身邊的夥伴。",
  "class.rogue.blurb": "用短劍極快地刺擊。",
  "class.monk.blurb": "赤手連打，還有讓人暈眩的招式。",

  "weapon.warrior": "長劍",
  "weapon.ranger": "弓",
  "weapon.wizard": "魔法杖",
  "weapon.cleric": "聖職者之杖",
  "weapon.rogue": "短劍",
  "weapon.monk": "拳",

  "skill.warrior.0": "迴旋斬",
  "skill.warrior.0.blurb": "旋轉一圈，砍中周圍所有怪物。",
  "skill.warrior.1": "突進斬",
  "skill.warrior.1.blurb": "向前大力揮砍，短暫擊倒對手。",
  "skill.warrior.2": "大地強擊",
  "skill.warrior.2.blurb": "重擊地面，暈眩周圍所有怪物。",
  "skill.ranger.0": "貫穿之箭",
  "skill.ranger.0.blurb": "筆直飛出，貫穿成列的怪物。",
  "skill.ranger.1": "瞄準射擊",
  "skill.ranger.1.blurb": "鎖定一個目標，造成大量傷害。",
  "skill.ranger.2": "箭雨",
  "skill.ranger.2.blurb": "向周圍傾瀉箭矢。",
  "skill.wizard.0": "烈焰爆發",
  "skill.wizard.0.blurb": "以火焰覆蓋周圍，燒灼怪物。",
  "skill.wizard.1": "冰之槍",
  "skill.wizard.1.blurb": "貫穿並凍結一個目標，使其無法移動。",
  "skill.wizard.2": "隕石墜落",
  "skill.wizard.2.blurb": "自天而降的火球，燒盡周圍。",
  "skill.cleric.0": "治癒之光",
  "skill.cleric.0.blurb": "回復自己與附近夥伴的體力。",
  "skill.cleric.1": "神聖一擊",
  "skill.cleric.1.blurb": "杖上凝光擊向前方，並使其暈眩。",
  "skill.cleric.2": "祝福",
  "skill.cleric.2.blurb": "燒灼周圍怪物，並大幅回復夥伴。",
  "skill.rogue.0": "暗影一擊",
  "skill.rogue.0.blurb": "深深刺向前方的一個怪物。",
  "skill.rogue.1": "刃之扇",
  "skill.rogue.1.blurb": "向前方撒出短劍。",
  "skill.rogue.2": "暗影亂舞",
  "skill.rogue.2.blurb": "攪動周圍，一併斬盡。",
  "skill.monk.0": "暈眩連打",
  "skill.monk.0.blurb": "痛擊前方怪物，使其暈眩一段時間。",
  "skill.monk.1": "旋風踢",
  "skill.monk.1.blurb": "旋身踢擊，打中周圍所有目標。",
  "skill.monk.2": "白熱拳",
  "skill.monk.2.blurb": "將全力的一拳灌入單一目標。",

  "job.berserker": "狂戰士",
  "job.guardian": "守護騎士",
  "job.sniper": "狙擊手",
  "job.tracker": "森林追蹤者",
  "job.elementalist": "元素術士",
  "job.warder": "結界術士",
  "job.high_priest": "大祭司",
  "job.paladin": "聖騎士",
  "job.assassin": "刺客",
  "job.scout": "斥候",
  "job.fist_master": "拳聖",
  "job.iron_monk": "鐵壁修士",
};
