import type { Bundle } from "./ko";

export const zhHans: Bundle = {
  "common.close": "关闭",
  "common.back": "返回",
  "common.on": "开启",
  "common.off": "关闭",
  "common.none": "关",

  "settings.title": "设置",
  "settings.sound": "声音",
  "settings.music": "背景音乐",
  "settings.effects": "音效",
  "settings.controls": "操作",
  "settings.sensitivity": "鼠标灵敏度",
  "settings.times": "{n}倍",
  "settings.screen": "画面",
  "settings.brightness": "亮度",
  "settings.quality": "画质",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "越低越省性能和电量。会改变树木与草地的完整绘制距离，以及画面分辨率。",
  "settings.shown": "显示",
  "settings.showNames": "其他玩家名称",
  "settings.damageNumbers": "伤害数字",
  "settings.announcements": "全服公告",
  "announce.legendary": "[{server}] {name}获得了传说坐骑{mount}！",
  "announce.star5": "[{server}] {name}的{mount}达成★5突破！",
  "announce.enhance": "[{server}] {name}成功强化{item}！",
  "announce.guildBoss": "公会<{guild}>击败了{boss}！",
  "settings.language": "语言",
  "settings.keysTab": "快捷键",
  "settings.defaults": "默认值",
  "settings.exit": "回到菜单",

  "keys.jump": "跳跃",
  "keys.click": "左键 / 右键",
  "keys.attackGuard": "攻击 / 格挡",
  "keys.skills": "技能",
  "keys.potion": "药水",
  "keys.talk": "对话",
  "keys.auto": "自动战斗",
  "keys.quest": "前往任务・汇报",
  "keys.chat": "聊天",
  "keys.move": "移动（方向键也可）",
  "keys.menu": "展开菜单",
  "keys.closeWindow": "关闭窗口",
  "keys.map": "地图",
  "keys.panels": "排行 / 任务 / 技能 / 铁匠铺 / 背包 / 坐骑",
  "keys.powerSave": "省电模式",
  "keys.settings": "设置",

  "list.join": "、",
  "stat.power": "攻击力 +{n}%",
  "stat.hp": "体力 +{n}",
  "stat.guard": "受到伤害 -{n}%",
  "stat.heal": "治疗量 +{n}%",

  "class.warrior": "战士",
  "class.ranger": "弓箭手",
  "class.wizard": "法师",
  "class.cleric": "牧师",
  "class.rogue": "盗贼",
  "class.monk": "武斗家",
  "class.warrior.blurb": "长剑与盔甲。站稳脚步一路砍过去。",
  "class.ranger.blurb": "从远处射箭。被贴近就弱了。",
  "class.wizard.blurb": "以法杖射出魔弹。慢，但打得远。",
  "class.cleric.blurb": "治疗自己与身边的伙伴。",
  "class.rogue.blurb": "用短剑极快地刺击。",
  "class.monk.blurb": "赤手连打，还有让人晕眩的招式。",

  "weapon.warrior": "长剑",
  "weapon.ranger": "弓",
  "weapon.wizard": "魔法杖",
  "weapon.cleric": "圣职者之杖",
  "weapon.rogue": "短剑",
  "weapon.monk": "拳",

  "skill.warrior.0": "回旋斩",
  "skill.warrior.0.blurb": "旋转一圈，砍中周围所有怪物。",
  "skill.berserker.0": "突进斩",
  "skill.berserker.0.blurb": "向前大力挥砍，短暂击倒对手。",
  "skill.berserker.1": "大地强击",
  "skill.berserker.1.blurb": "重击地面，晕眩周围所有怪物。",
  "skill.berserker.2": "大屠杀",
  "skill.berserker.2.blurb": "任由狂怒驱使，斩倒周围所有敌人",
  "skill.ranger.0": "贯穿之箭",
  "skill.ranger.0.blurb": "笔直飞出，贯穿成列的怪物。",
  "skill.sniper.0": "瞄准射击",
  "skill.sniper.0.blurb": "锁定一个目标，造成大量伤害。",
  "skill.sniper.1": "箭雨",
  "skill.sniper.1.blurb": "向周围倾泻箭矢。",
  "skill.sniper.2": "穿天一击",
  "skill.sniper.2.blurb": "从极远处贯穿单一目标的必杀一箭",
  "skill.wizard.0": "烈焰爆发",
  "skill.wizard.0.blurb": "以火焰覆盖周围，烧灼怪物。",
  "skill.elementalist.0": "冰之枪",
  "skill.elementalist.0.blurb": "贯穿并冻结一个目标，使其无法移动。",
  "skill.elementalist.1": "陨石坠落",
  "skill.elementalist.1.blurb": "自天而降的火球，烧尽周围。",
  "skill.elementalist.2": "冰河风暴",
  "skill.elementalist.2.blurb": "召唤冰暴，冻结并重创周围敌人",
  "skill.cleric.0": "治愈之光",
  "skill.cleric.0.blurb": "回复自己与附近伙伴的体力。",
  "skill.paladin.0": "神圣一击",
  "skill.paladin.0.blurb": "杖上凝光击向前方，并使其晕眩。",
  "skill.high_priest.1": "祝福",
  "skill.high_priest.1.blurb": "烧灼周围怪物，并大幅回复伙伴。",
  "skill.high_priest.2": "生命赞歌",
  "skill.high_priest.2.blurb": "大范围散发光芒，大幅回复自己与队友的体力",
  "skill.rogue.0": "暗影一击",
  "skill.rogue.0.blurb": "深深刺向前方的一个怪物。",
  "skill.assassin.0": "刃之扇",
  "skill.assassin.0.blurb": "向前方撒出短剑。",
  "skill.assassin.1": "暗影乱舞",
  "skill.assassin.1.blurb": "搅动周围，一并斩尽。",
  "skill.assassin.2": "暗杀",
  "skill.assassin.2.blurb": "对前方单一目标施以致命一击",
  "skill.monk.0": "晕眩连打",
  "skill.monk.0.blurb": "痛击前方怪物，使其晕眩一段时间。",
  "skill.fist_master.0": "旋风踢",
  "skill.fist_master.0.blurb": "旋身踢击，打中周围所有目标。",
  "skill.fist_master.1": "白热拳",
  "skill.fist_master.1.blurb": "将全力的一拳灌入单一目标。",
  "skill.fist_master.2": "天崩拳",
  "skill.fist_master.2.blurb": "以天崩地裂之拳重击周围并击晕",
  "skill.guardian.0": "盾击",
  "skill.guardian.0.blurb": "以盾牌重击前方的一个怪物，使其长时间晕眩。",
  "skill.guardian.1": "守护战吼",
  "skill.guardian.1.blurb": "以战吼冲击周围，并回复自己与伙伴的体力。",
  "skill.guardian.2": "不屈城墙",
  "skill.guardian.2.blurb": "重击盾牌，长时间定住周围并大量回复自己与队友",
  "skill.tracker.0": "陷阱之箭",
  "skill.tracker.0.blurb": "射中一个目标，将其定在原地。",
  "skill.tracker.1": "扇形射击",
  "skill.tracker.1.blurb": "向前方大范围倾泻箭矢。",
  "skill.tracker.2": "猎人之网",
  "skill.tracker.2.blurb": "向前方大范围射出网箭，长时间定住敌人",
  "skill.warder.0": "结界波动",
  "skill.warder.0.blurb": "展开结界冲击周围，并短暂将其束缚。",
  "skill.warder.1": "守护结界",
  "skill.warder.1.blurb": "大幅回复自己与附近伙伴的体力。",
  "skill.warder.2": "绝对结界",
  "skill.warder.2.blurb": "展开大范围结界，长时间定住周围并回复自己与队友",
  "skill.high_priest.0": "净化之光",
  "skill.high_priest.0.blurb": "以光束烧灼一个目标，并稍微回复自己与伙伴。",
  "skill.paladin.1": "审判之锤",
  "skill.paladin.1.blurb": "挥下光之重锤，使周围全数晕眩。",
  "skill.paladin.2": "天上审判",
  "skill.paladin.2.blurb": "降下天光，击晕周围敌人并回复队友",
  "skill.scout.0": "烟幕",
  "skill.scout.0.blurb": "施放烟幕，使周围怪物暂时停下。",
  "skill.scout.1": "飞刀连掷",
  "skill.scout.1.blurb": "将短剑呈扇形远远掷出。",
  "skill.scout.2": "刀刃风暴",
  "skill.scout.2.blurb": "向前方远处倾泻刀刃，使敌人短暂停顿",
  "skill.iron_monk.0": "铁山靠",
  "skill.iron_monk.0.blurb": "以肩撞击，使前方大范围晕眩。",
  "skill.iron_monk.1": "金刚不坏",
  "skill.iron_monk.1.blurb": "爆发气劲冲击周围，并回复自己与伙伴的体力。",
  "skill.iron_monk.2": "不动明王",
  "skill.iron_monk.2.blurb": "以不动之气定住周围，并大量回复自己与队友",
  "class.paths": "Lv{n} 转职・二选一",
  "skills.pathSlot": "转职技能 {n}",
  "skills.afterAdvance": "Lv{n} 转职后学会",

  "job.berserker": "狂战士",
  "job.guardian": "守护骑士",
  "job.sniper": "狙击手",
  "job.tracker": "森林追踪者",
  "job.elementalist": "元素术士",
  "job.warder": "结界术士",
  "job.high_priest": "大祭司",
  "job.paladin": "圣骑士",
  "job.assassin": "刺客",
  "job.scout": "斥候",
  "job.fist_master": "拳圣",
  "job.iron_monk": "铁壁修士",

  "item.heal": "回复体力 {n}",
  "item.potion_small": "小型药水",
  "item.potion_big": "大型药水",
  "item.weapon_1": "学徒的武器",
  "item.weapon_2": "林守的武器",
  "item.weapon_3": "蘑菇王的武器",
  "item.weapon_4": "钢制武器",
  "item.weapon_5": "岩心武器",
  "item.armor_1": "皮甲",
  "item.armor_2": "林守的护甲",
  "item.armor_3": "蘑菇王的护甲",
  "item.armor_4": "钢制护甲",
  "item.armor_5": "岩心护甲",
  "item.stone": "强化石",
  "item.stone.blurb": "强化装备的材料。所有狩猎场。",
  "item.jelly": "史莱姆凝胶",
  "item.jelly.blurb": "制作材料。森林原野 1。",
  "item.silk": "蜘蛛丝",
  "item.silk.blurb": "制作材料。森林原野 2。",
  "item.core": "岩心石",
  "item.core.blurb": "制作材料。深邃森林。",
  "item.spore": "蘑菇王的孢子",
  "item.spore.blurb": "制作材料。蘑菇王。",

  "monster.green_blob": "绿史莱姆",
  "monster.mushnub": "小蘑菇",
  "monster.rat": "野鼠",
  "monster.frog": "青蛙",
  "monster.spider": "森林蜘蛛",
  "monster.snake": "毒蛇",
  "monster.wasp": "黄蜂",
  "monster.bat": "蝙蝠",
  "monster.goleling": "魔像幼体",
  "monster.dire_spider": "巨型毒蛛",
  "monster.venom_snake": "剧毒蛇",
  "monster.hornet": "大虎头蜂",
  "monster.vampire_bat": "吸血蝙蝠",
  "monster.stone_golem": "岩石魔像",
  "monster.mushnub_guard": "蘑菇护卫",
  "monster.mushroom_king": "蘑菇王",
  "monster.grove_guardian": "净化守护者",
  "monster.guild_dragon": "远古巨龙",
  "monster.guild_yeti": "雪山雪怪",
  "monster.guild_glub": "长老咕噜",
  "monster.glub_brood": "小咕噜",

  "zone.village": "绿林村",
  "zone.forest1": "森林原野 1",
  "zone.forest2": "森林原野 2",
  "zone.forest3": "深邃森林",
  "zone.boss": "蘑菇王的空地",
  "zone.arena": "公会首领竞技场",
  "zone.outpost": "雪山前哨站",
  "zone.snow1": "雪山山麓",
  "zone.snow2": "冰之峡谷",
  "zone.snow3": "万年雪峰",
  "zone.snowboss": "冰河祭坛",
  "npc.frost_merchant": "商人艾瑞克",
  "npc.frost_merchant.role": "商店",
  "npc.captain": "队长布兰",
  "npc.captain.role": "任务",
  "npc.frost_smith": "铁匠英格",
  "npc.frost_smith.role": "强化·制作",
  "npc.frost_merchant.hello": "「这么冷还来啦。药水多带一些。」",
  "npc.frost_smith.hello": "「雪山的铁像冰一样硬。带霜之结晶来就行。」",
  "monster.frost_blob": "霜史莱姆",
  "monster.snow_hare": "雪兔",
  "monster.snow_wolf": "雪原狼",
  "monster.frost_spider": "霜蜘蛛",
  "monster.frost_bat": "霜蝙蝠",
  "monster.penguin_brute": "企鹅战士",
  "monster.frost_snake": "冰结蛇",
  "monster.ice_golem": "冰魔像",
  "monster.peak_yeti": "峰顶雪怪",
  "monster.frost_drake": "霜飞龙",
  "monster.glacier_alpaking": "冰河羊驼王",
  "monster.frost_emperor": "冰河皇帝",
  "item.weapon_6": "霜牙武器",
  "item.armor_6": "霜牙铠甲",
  "item.weapon_7": "冰河王武器",
  "item.armor_7": "冰河王铠甲",
  "item.frost_shard": "霜之结晶",
  "item.frost_shard.blurb": "制作材料。雪山狩猎场",
  "item.snow_fur": "雪原毛皮",
  "item.snow_fur.blurb": "制作材料。雪山山麓、冰之峡谷",
  "item.ever_ice": "万年冰",
  "item.ever_ice.blurb": "7级制作材料。万年雪峰",

  "npc.merchant": "商人汉斯",
  "npc.merchant.role": "商店",
  "npc.elder": "村长玛尔塔",
  "npc.elder.role": "任务",
  "npc.smith": "铁匠沃尔夫",
  "npc.smith.role": "强化・制作",

  "world.name": "绿林",

  "quest.0": "史莱姆讨伐",
  "quest.0.goal": "森林原野 1 的绿史莱姆 15 只",
  "quest.1": "清剿小蘑菇",
  "quest.1.goal": "森林原野 1 的小蘑菇 20 只",
  "quest.2": "原野的麻烦",
  "quest.2.goal": "野鼠或青蛙 40 只",
  "quest.3": "深林侦察",
  "quest.3.goal": "森林原野 2 的森林蜘蛛或毒蛇 50 只",
  "quest.4": "天空的狩猎",
  "quest.4.goal": "黄蜂或蝙蝠 60 只",
  "quest.5": "石之精灵",
  "quest.5.goal": "魔像幼体 60 只",
  "quest.6": "讨伐蘑菇王",
  "quest.6.goal": "蘑菇王空地的蘑菇王",
  "quest.7": "深邃森林的蛛穴",
  "quest.7.goal": "深邃森林的巨型毒蛛或剧毒蛇 60 只",
  "quest.8": "遮天之翼",
  "quest.8.goal": "大虎头蜂或吸血蝙蝠 80 只",
  "quest.9": "森林的守护石",
  "quest.9.goal": "岩石魔像 60 只",
  "quest.10": "魔像之心",
  "quest.10.goal": "岩石魔像 100 只",
  "quest.11": "再讨蘑菇王",
  "quest.11.goal": "击倒蘑菇王 3 次",
  "quest.12": "深邃森林之主",
  "quest.12.goal": "深邃森林的怪物 200 只",
  "quest.13": "雪中的第一步",
  "quest.13.goal": "霜史莱姆・雪兔60只",
  "quest.14": "雪原的猎手",
  "quest.14.goal": "雪原狼・霜蜘蛛80只",
  "quest.15": "守住峡谷入口",
  "quest.15.goal": "霜蝙蝠・企鹅战士80只",
  "quest.16": "峡谷深处",
  "quest.16.goal": "冰结蛇・冰魔像90只",
  "quest.17": "移动的冰墙",
  "quest.17.goal": "冰魔像100只",
  "quest.18": "峰顶的巨人",
  "quest.18.goal": "峰顶雪怪80只",
  "quest.19": "天空与冰之王",
  "quest.19.goal": "霜飞龙・冰河羊驼王100只",
  "quest.20": "冰河皇帝",
  "quest.20.goal": "在冰河祭坛击败冰河皇帝",
  "daily.forest1": "巡逻：森林原野 1",
  "daily.forest1.goal": "森林原野 1 的怪物 30 只",
  "daily.forest2": "巡逻：森林原野 2",
  "daily.forest2.goal": "森林原野 2 的怪物 40 只",
  "daily.forest3": "巡逻：深邃森林",
  "daily.forest3.goal": "深邃森林的怪物 50 只",
  "daily.snow1": "巡逻：雪山山麓",
  "daily.snow1.goal": "雪山山麓的怪物50只",
  "daily.snow2": "巡逻：冰之峡谷",
  "daily.snow2.goal": "冰之峡谷的怪物60只",
  "daily.snow3": "巡逻：万年雪峰",
  "daily.snow3.goal": "万年雪峰的怪物60只",

  "common.loading": "加载中…",
  "common.gold": "{n} 金币",
  "wallet.gold": "金币（点击打开背包）",
  "wallet.gems": "宝石（点击打开坐骑・宝石商店）",
  "common.nothing": "无",
  "problem.unavailable": "当前无法进行",
  "problem.max_plus": "已无法继续强化",
  "problem.not_near": "需要靠近铁匠才能进行",
  "problem.not_enough_gold": "金币不足",
  "problem.not_in_village": "商店在村子里",
  "problem.no_item": "背包里没有",
  "problem.bag_full": "背包放不下了（每格最多 99 个）",
  "problem.too_low_advance": "Lv{n} 起可以转职",

  "slot.weapon": "武器",
  "slot.armor": "护甲",

  "bag.title": "背包",
  "bag.power": "战斗力 {n}",
  "bag.job": "转职",
  "bag.advanceAt": "到 Lv{at} 就能转职（目前 Lv{level}）",
  "bag.pickPath": "请选择转职的道路。一旦选定就不能更改。",
  "bag.confirmPath": "确定转职为{name}吗？之后无法更改。",
  "bag.advanceGo": "转职",
  "bag.unequip": "卸下",
  "bag.empty": "背包是空的",
  "bag.pickHint": "点选物品，这里会显示说明与用法。",
  "bag.drink": "饮用",
  "bag.equip": "装备",
  "bag.sell": "卖出（{n}）",
  "bag.keys": "Q：喝药水 · I：背包",
  "item.trade": "可交易",
  "item.bound": "不可交易",
  "forge.tradeChance": "制作的装备有{pct}概率可交易。",

  "shop.title": "村庄商店",
  "shop.buy": "购买",
  "shop.buyTen": "10 个",
  "shop.note": "怪物会掉落金币与装备。卖出请从背包。",

  "forge.title": "铁匠铺",
  "forge.stones": "强化石 {n} 个",
  "forge.enhance": "强化",
  "forge.craft": "制作",
  "forge.noGear": "沒有装备任何東西",
  "forge.chance": "+{to} 成功 {pct}",
  "forge.breakRisk": "失败时损毁 {pct}",
  "forge.maxed": "已達最高强化（+{n}）",
  "forge.note": "从 +{n} 起，失败可能损毁装备。强化石由所有狩猎场的怪物掉落。",
  "forge.success": "强化成功！",
  "forge.fail": "强化失败… 装备没有损伤",
  "forge.broken": "强化失败… 装备损毁了",
  "forge.working": "强化中…",
  "forge.crafted": "{name} 制作完成！",

  "common.retry": "再试一次",
  "common.toMenu": "回到菜单",
  "common.menu": "菜单",
  "common.off2": "关闭",

  "problem.zone_full": "所有频道都满了。请稍后再试",
  "problem.not_near_portal": "请站到传送门旁",
  "problem.too_low": "等级不足",
  "problem.cannotTravel": "当前无法前往",
  "problem.enter": "无法进入世界",
  "problem.enterWith": "无法进入世界（{error}）",
  "problem.connect": "无法连上游戏服务器。请检查网络后再试一次。",
  "problem.tooFast": "请说慢一点",
  "problem.cannotSend": "无法发送",

  "world.entering": "正在进入世界…",
  "world.loading": "正在加载森林… {n}%",
  "world.travelling": "移动中…",
  "world.channel": "频道 {n}",
  "world.talk": "{name} — {role} · 对话 (E)",
  "world.portalLevel": "{zone} — Lv{n} 起可前往",
  "world.portalTo": "通往{zone}的路",
  "world.blocking": "格挡中",

  "menu.map": "地图",
  "menu.ranking": "排行",
  "menu.quests": "任务",
  "menu.skills": "技能",
  "menu.forge": "铁匠铺",
  "menu.bag": "背包",
  "menu.sleep": "省电",
  "menu.news": "公告",
  "news.title": "更新公告",
  "menu.mail": "邮件",
  "mail.title": "邮箱",
  "mail.empty": "没有邮件",
  "mail.failed": "无法打开邮箱",
  "mail.claim": "领取",
  "mail.claimAll": "全部领取",
  "mail.daysLeft": "剩余{n}天",
  "mail.gift": "礼物",
  "mail.gold": "{n} 金币",
  "problem.no_mail": "这封邮件已领取或已消失",
  "menu.market": "交易所",
  "market.title": "交易所",
  "market.buy": "购买",
  "market.sell": "出售",
  "market.mine": "我的上架",
  "market.weapon": "武器",
  "market.armor": "护甲",
  "market.material": "材料",
  "market.all": "全部",
  "market.minPlus": "+{n}以上",
  "market.empty": "没有商品",
  "market.failed": "无法打开交易所",
  "market.left": "剩余{h}小时{m}分",
  "market.leftMin": "剩余{m}分",
  "market.buyGo": "购买",
  "market.mineTag": "我的",
  "market.confirm": "要以{price}宝石购买{name}吗？购买的物品会以邮件送达。",
  "market.bought": "购买成功！请到邮箱领取。",
  "market.page": "{n} / {of}",
  "market.each": "每个",
  "market.nothingToSell": "没有可交易的装备或材料。怪物掉落的材料，以及部分掉落、制作的装备可交易。",
  "market.pick": "请选择要出售的物品",
  "market.price": "价格（宝石）",
  "market.count": "数量",
  "market.fee": "手续费 {fee} · 可得 {gets}",
  "market.list": "上架",
  "market.listed": "已上架",
  "market.limit": "上架 {n}/{max}",
  "market.cancel": "下架",
  "market.canceled": "已下架，会以邮件退回。",
  "market.none": "没有上架的商品",
  "market.ended": "已到期（即将以邮件退回）",
  "market.note": "售出所得会扣除5%手续费后以宝石邮寄。商品48小时后下架并以邮件退回。",
  "problem.listing_gone": "这件商品已售出或已下架",
  "problem.too_many": "剩下的没那么多，已被别人先买走。",
  "market.priceEach": "单价（宝石）",
  "market.total": "合计 {n}",
  "market.howMany": "要买几个？（剩 {n} 个）",
  "market.max": "最多",
  "problem.listing_limit": "最多只能上架{n}件",
  "problem.bad_price": "请再确认价格",
  "problem.not_tradable": "这件物品不可交易",
  "problem.own_listing": "不能购买自己的商品",
  "menu.guild": "公会",
  "guild.title": "公会",
  "guild.find": "寻找公会",
  "guild.search": "公会名称",
  "guild.searchGo": "搜索",
  "guild.none": "没有公会",
  "guild.count": "{n}/{max}人",
  "guild.apply": "申请加入",
  "guild.applied": "已申请",
  "guild.myApplications": "我的申请",
  "guild.withdraw": "取消",
  "guild.create": "创建公会",
  "guild.createCost": "{n} 金币",
  "guild.createGo": "创建",
  "guild.wait": "{time}起可以加入或创建公会",
  "guild.notice": "公告",
  "guild.noNotice": "没有公告",
  "guild.editNotice": "编辑",
  "guild.saveNotice": "保存",
  "guild.members": "成员 {n}/{max}",
  "guild.role.master": "会长",
  "guild.role.vice": "副会长",
  "guild.role.member": "成员",
  "guild.offline": "离线",
  "guild.applicants": "加入申请",
  "guild.accept": "接受",
  "guild.decline": "拒绝",
  "guild.kick": "踢出",
  "guild.makeVice": "设为副会长",
  "guild.makeMember": "设为成员",
  "guild.pass": "移交会长",
  "guild.confirmKick": "要踢出{name}吗？",
  "guild.confirmPass": "要把会长移交给{name}吗？你将成为成员。",
  "guild.leave": "退出",
  "guild.confirmLeave": "要退出公会吗？24小时内无法加入其他公会。",
  "guild.disband": "解散",
  "guild.confirmDisband": "要解散公会吗？无法恢复。",
  "guild.yes": "是",
  "guild.failed": "无法加载公会信息",
  "guild.rules": "公会由所有服务器共用。每个角色可以加入一个公会。",
  "chat.channel": "频道",
  "chat.guild": "公会",
  "problem.guild_name_invalid": "公会名称为2~12个字，可用韩文、英文、数字、_",
  "problem.guild_name_taken": "这个公会名称已被使用",
  "problem.in_guild": "你已经在公会里了",
  "problem.no_guild": "没有公会",
  "problem.guild_full": "公会已满",
  "problem.guild_wait": "离开公会后需经过24小时",
  "problem.applied_limit": "最多只能申请3个公会",
  "problem.applicants_full": "该公会无法再接受申请",
  "problem.no_applicant": "这个申请已处理，或对方已加入其他公会",
  "problem.not_allowed": "你没有这个权限",
  "problem.vice_limit": "副会长最多3人",
  "problem.master_must_pass": "会长必须先移交会长",
  "problem.guild_not_empty": "公会还有成员时无法解散",
  "guild.tab.members": "公会",
  "guild.tab.boss": "首领",
  "boss.guild_dragon": "远古巨龙",
  "boss.guild_yeti": "雪山雪怪",
  "boss.guild_glub": "长老咕噜",
  "boss.week": "本周首领",
  "boss.left": "剩余体力 {n}%",
  "boss.down": "已击败！等待下周的首领",
  "boss.endsAt": "至{time}",
  "boss.today": "今天已挑战（明天可以再进入）",
  "boss.ready": "今天可以挑战 · 3分钟 · Lv10以上",
  "boss.room": "{n}号房",
  "boss.seats": "{n}/{max}人",
  "boss.enter": "进入",
  "boss.ranking": "贡献度",
  "boss.mine": "我的累计伤害 {n}",
  "boss.noRanking": "还没有人挑战",
  "boss.stages": "达到25、50、75%与击败时，本周参与者全员以邮件获得奖励。击败时获得可交易装备（贡献前3名为最高级）。",
  "boss.hint": "地面出现红色标示时请往外闪避！",
  "boss.leave": "离开",
  "boss.timeUp": "3分钟结束了",
  "boss.fallen": "你倒下了",
  "boss.endNote": "造成的伤害已累积到公会首领。明天再来挑战吧！",
  "boss.slain": "击败首领了！",
  "mail.guildBoss": "公会首领第{stage}阶段奖励",
  "mail.guildBossBody": "{boss}已被削减{pct}%。感谢一起奋战！",
  "mail.guildBossSlain": "击败了{boss}！送上击败奖励。",
  "problem.boss_down": "本周首领已被击败",
  "problem.entered_today": "今天已经挑战过了",
  "problem.room_full": "该房间已满",
  "problem.arena_over": "挑战时间已结束",
  "mail.marketSold": "售出：{item}",
  "mail.marketSoldBody": "以{price}宝石售出。已扣除手续费{fee}宝石寄出。",
  "mail.marketBought": "购买：{item}",
  "mail.marketBoughtBody": "以{price}宝石购买。",
  "mail.marketReturned": "退回：{item}",
  "mail.marketReturnedBody": "未售出或已下架的商品退回给您。",
  "menu.settings": "设置",

  "death.fallen": "你倒下了",
  "death.lostXp": "失去了 {n} 经验值",
  "death.lostNone": "没有失去经验值",
  "death.lossNote": "倒下会失去本级经验值的 {n}%（等级不会下降）",
  "death.here": "原地复活 · {gold}",
  "death.hereNote": "以 {n}% 体力起身，怪物会暂时不攻击你",
  "death.short": " · 金币不足",
  "death.village": "在村庄复活 · 免费",

  "sleep.title": "省电模式",
  "sleep.elapsed": "经过时间",
  "sleep.xp": "获得经验值",
  "sleep.gold": "获得金币",
  "sleep.potions": "剩余药水",
  "sleep.potionCount": "{n} 个",
  "sleep.auto": "自动战斗",
  "sleep.hunting": "狩猎中",
  "sleep.dead": "你倒下了 — 点两下查看",
  "sleep.hint": "点两下画面即可返回",

  "chat.placeholder": "对频道说话",
  "chat.send": "发送",
  "chat.open": "聊天",
  "chat.enterHint": "开始聊天",
  "lobby.deleteCharacter": "删除 {name}",
  "delete.title": "删除角色",
  "delete.warning": "「{name}」的等级、装备与任务将全部消失，无法恢复。若要删除，请照样输入名称。",
  "delete.confirm": "永久删除",
  "problem.name_mismatch": "名称不符",

  "quest.allDone": "所有任务完成",
  "quest.reportHere": "点击向村长汇报",
  "quest.reportInVillage": "点一下前往村里的村长",
  "quest.seeking": "前往中…",
  "quest.goFind": "点击前往",

  "pad.attack": "攻击",
  "pad.block": "格挡",
  "pad.jump": "跳跃",
  "pad.auto": "自动",
  "pad.autoOn": "自动中",
  "pad.leftClick": "左键",
  "pad.rightClick": "右键",

  "map.tapToWalk": "点击即可走到那里",
  "map.portals": "区域出入口",
  "map.villagers": "村民",
  "map.you": "你",
  "map.close": "关闭 (N)",

  "bar.potion": "药水",
  "bar.emptySlot": "空格",
  "bar.autoPotion": "自动药水",
  "bar.autoPotionTitle": "自动药水设置",
  "bar.autoPotionAt": "生命低于 {n}% 时会喝药水",
  "bar.autoPotionOff": "（目前已关闭）",
  "bar.autoPotionTurnOn": "开启自动药水",
  "bar.autoPotionTurnOff": "关闭自动药水",

  "skills.title": "技能",
  "skills.dragNote": "把学会的技能拖到下方的格子。",
  "skills.learnAt": "Lv{n} 学会",
  "skills.fromElder": "向村长学习",
  "skills.inSlot": "第 {n} 格",
  "skills.dragIn": "拖曳放入格子",
  "skills.cooldown": "冷却 {n} 秒",
  "skills.remove": "取出",

  "common.next": "下一步",
  "common.accept": "接受",
  "common.decline": "拒绝",

  "lobby.newCharacter": "新角色",
  "lobby.needServer": "需要连上 Verse8 服务器才能开始游戏。",
  "lobby.accountFailed": "无法读取账号资料。请刷新。",
  "lobby.accountLoading": "正在读取账号资料…",
  "lobby.loading": "正在加载村庄… {n}%",
  "lobby.tapToStart": "点击画面开始",
  "lobby.friends": "好友",
  "lobby.characters": "{world} · 角色 {n}/{max}",
  "lobby.createCharacter": "+ 创建角色",
  "lobby.start": "开始游戏",
  "lobby.changeServer": "更换服务器",
  "lobby.noCharacter": "创建角色，开始冒险吧。",
  "lobby.guestNote": "你尚未登录。现在创建的角色下次无法读取。请先登录 Verse8 再开始。",


  "class.pick": "选择职业",
  "class.weapon": "武器",
  "class.ranged": "远程",
  "class.melee": "近战",
  "class.damage": "攻击力",
  "class.speed": "攻击速度",
  "class.perSecond": "{n} 次/秒",
  "class.reach": "射程",
  "class.block": "格挡",
  "class.skillLine": "技能 {n} · {name}",
  "class.confirm": "选定这个职业",
  "class.onceNote": "职业在创建角色时决定一次。",
  "class.pickHint": "点击角色来查看职业。",

  "look.title": "决定角色外观",
  "look.spin": "拖曳可旋转",
  "look.shape": "外观",
  "look.random": "随机",
  "look.making": "创建中…",
  "look.create": "创建角色",
  "look.onceNote": "外观在创建角色后就不能更改。",
  "look.previous": "{part} 上一个",
  "look.next": "{part} 下一个",

  "part.gear": "饰品",
  "part.clothColor": "衣服颜色",
  "part.skin": "肤色",
  "part.weaponColor": "武器颜色",
  "look.default": "默认",
  "look.on": "配戴",
  "look.off": "取下",
  "look.grey": "无彩色",
  "look.dye": "染色 {n}",
  "look.skinLight": "白皙",
  "look.skinTan": "小麦色",
  "look.skinDark": "深色",
  "look.mine": "自己的样子",
  "look.preset.light": "轻装",
  "look.preset.shadow": "暗影",

  "name.title": "角色名称",
  "name.note": "其他玩家与好友会以这个名字看到你。文字、数字或 _ 共 2～12 字，且不能与其他角色重复。",
  "name.placeholder": "名称",
  "name.checking": "确认中…",

  "server.pick": "选择服务器",
  "server.note": "选同一台服务器的玩家才会相遇。和朋友选同一台吧。",
  "server.entering": "进入中…",
  "server.recent": "最近游玩",
  "server.failed": "无法选择服务器。请稍后再试一次",

  "common.add": "添加",
  "common.cancel": "取消",
  "common.remove": "删除",
  "common.removeSure": "确定删除",
  "common.noName": "（没有名字）",
  "common.reward": "报酬：{what}",
  "common.xp": "{n} XP",

  "friends.title": "好友",
  "friends.needCharacter": "要添加好友，请先创建角色。",
  "friends.search": "以名称添加好友",
  "friends.needServer": "好友需连上 Verse8 后才能使用。",
  "friends.loading": "正在读取好友名单…",
  "friends.sent": "已发出好友邀请",
  "friends.bothWays": "双方都发出邀请，已成为好友",
  "friends.nowFriends": "你和 {name} 成为好友了",
  "friends.incoming": "收到的邀请 {n}",
  "friends.list": "好友名单",
  "friends.online": "· 在线 {on}/{all}",
  "friends.none": "还没有好友。试着用名称添加吧。",
  "friends.isOnline": "在线",
  "friends.isOffline": "离线",
  "friends.outgoing": "发出的邀请",
  "friends.waiting": "等待中",

  "problem.friend_not_found": "找不到这个名称",
  "problem.friend_self": "不能添加自己",
  "problem.already_friends": "已经是好友",
  "problem.friend_limit": "好友最多 {n} 位",
  "problem.request_limit": "对方收到的邀请太多了",
  "problem.no_request": "这个邀请已经处理过了",
  "problem.nickname_taken": "这个名称已被使用",
  "problem.nickname_invalid": "可用文字、数字或 _ 共 2～12 字",
  "problem.character_limit": "这台服务器无法再创建角色",
  "problem.retryLater": "当前无法进行。请稍后再试一次",
  "problem.saveFailed": "无法保存。请稍后再试一次",
  "problem.not_near_elder": "请站到村长旁边说话",
  "problem.quest_unfinished": "还没有完成",
  "problem.cannotClaim": "当前无法领取",

  "rank.title": "排行榜",
  "rank.needServer": "连上 Verse8 后即可查看。",
  "rank.failed": "无法读取排行榜。请稍后再打开。",
  "rank.none": "还没有累积经验值的冒险者。",
  "rank.unranked": "未上榜",
  "rank.place": "第 {n} 名",
  "rank.nickname": "名称",
  "rank.class": "职业",
  "rank.level": "等级",
  "rank.rank": "名次",
  "rank.server": "服务器",
  "rank.xp": "经验值",
  "rank.power": "战斗力",
  "rank.detailFailed": "无法读取资料。",
  "rank.toList": "回到名单",

  "quests.title": "任务",
  "quests.daily": "每日任务 · 每天 0 点重新开始",
  "quests.claim": "领取报酬",
  "quests.claimedToday": "今天的报酬已领取",
  "quests.goReport": "去向村长汇报",
  "quests.reportHint": "向村里的村长汇报即可领取报酬",
  "quests.goFind": "前往",
  "quests.allDone": "所有任务都完成了。",
  "quests.past": "已完成的任务",
  "quests.more": "还有 {n} 个任务。",
  "quests.complete": "任务完成！",
  "quests.reportHere": "向村长汇报并领取报酬",
  "quests.reportInVillage": "向村里的村长汇报并领取报酬",
  "npc.merchant.hello": "「欢迎光临！药水、装备应有尽有。」",
  "npc.smith.hello": "「打铁要趁热。强化还是制作，都交给我。」",
  "dialogue.shop": "查看商店",
  "dialogue.forge": "打开铁匠铺",
  "npc.elder.done": "「这座森林里已经没有能难倒你的了。谢谢你，猎人。」",
  "npc.elder.tutorial": "「你来了。学会这个技能，把药水也带上。打开技能窗口看看学到的技能，放在下方栏位里就能马上使用。」",
  "npc.elder.claim": "「{quest}，做得好！这是说好的报酬。」",
  "npc.elder.ask": "「{goal}，就拜托你了。」",

  "note.notHere": "这个区域没有",
  "note.questLevel": "{zone}：Lv{n} 起可前往",
  "note.cannotWalk": "那里去不了",
  "note.gotGold": "+{n} 金币",
  "note.gotItem": "获得 {name}",
  "portal.needsLevel": "（Lv{n}）",

  "error.startFailed": "无法启动游戏。",
  "error.reload": "重新加载",
  "rotate.hint": "把画面转成横向会更好玩",
  "channel.title": "频道",
  "channel.note": "同一频道就能在任何区域相遇。切换后仍在原地。",
  "channel.here": "目前所在",
  "channel.full": "已满",
  "channel.friends": "好友：{names}",
  "keys.channel": "切换频道",
  "problem.channel_full": "该频道已满。请选择其他频道",
  "friends.where": "{server} · {channel} · {zone}",
  "common.prevPage": "上一页",
  "common.nextPage": "下一页",
  "friends.noIncoming": "没有收到的邀请。",
  "friends.noOutgoing": "没有发出的邀请。",
  "quests.tabNow": "进行中",
  "quests.tabDaily": "每日",
  "quests.tabPast": "已完成",
  "quests.noPast": "还没有完成的任务。",

  "tutorial.title": "第一步",
  "tutorial.step0": "与村长交谈",
  "tutorial.step1": "打开技能窗口，把新技能拖到 1 号栏位",
  "tutorial.step1Placed": "打开技能窗口看看新技能，它已经在 1 号栏位了",
  "tutorial.step2": "把技能栏和药水栏往下拖，开启自动使用",
  "tutorial.step3": "按下自动战斗按钮",
  "tutorial.doneTitle": "准备完成！",
  "tutorial.doneHint": "看看村长的第一个请托",

  "menu.grove": "森林",
  "grove.title": "森林净化",
  "grove.kills": "本周 {n} / {goal} 只",
  "grove.daysLeft": "剩 {n} 天",
  "grove.stage.1": "30% 花开，金币 200",
  "grove.stage.2": "60% 天空放晴，开放建地",
  "grove.stage.3": "100% 净化守护者（频道 1），金币 500",
  "grove.hazeHint": "击败怪物可净化森林，\n达到60%时雾气散去（本周 {n}%）",
  "grove.village": "村庄重建",
  "grove.building.herbalist": "药草铺",
  "grove.building.training": "训练场",
  "grove.building.inn": "旅店",
  "grove.building.watchtower": "瞭望塔",
  "grove.perk.herbalist": "药水 -20%",
  "grove.perk.training": "狩猎经验 +5%",
  "grove.perk.inn": "倒下损失经验减半",
  "grove.perk.watchtower": "小地图显示首领",
  "grove.closed": "未开放",
  "grove.building": "建造中 {n}%",
  "grove.done": "完工",
  "grove.failed": "无法载入",
  "dialogue.donate": "捐献",
  "donate.title": "建造{building}",
  "donate.have": "持有 {n}",
  "donate.gold": "金币",
  "donate.done": "谢谢！会记住你的名字。",
  "problem.nothing": "请选择要捐的东西",
  "problem.no_building": "目前没有建造中的建筑",
  "keys.ride": "骑上 / 下坐骑",
  "menu.mounts": "坐骑",
  "pad.ride": "骑乘",
  "pad.dismount": "下坐骑",
  "problem.not_enough_gems": "宝石不足",
  "problem.no_mount": "没有这个坐骑",
  "mount.none": "没有可骑的坐骑。完整版附赠鹿，孵蛋可获得更多。",
  "mount.rideHint": "按 T 或骑乘按钮上下坐骑。攻击或被攻击时会下坐骑。",
  "mount.stats": "攻击 +{p}% · 生命 +{h}",
  "mount.statsNote": "选中的坐骑即使不骑也会提升攻击力和生命值。",
  "mount.speed": "速度 ×{n}",
  "mount.riding": "骑乘中",
  "mount.pick": "骑这个",
  "mount.notOwned": "未拥有",
  "mount.new": "新坐骑！{tier} {name}",
  "mount.newBadge": "新坐骑！",
  "mount.repeatBadge": "已拥有",
  "mount.nextStar": "下一颗★{n}：攻击 +{p}% · 体力 +{h}",
  "mount.star": "{name}突破到★{n}！加成提升了",
  "mount.starBadge": "突破！",
  "mount.repeat": "已拥有{name} · 返还宝石 {n} 个",
  "mount.odds": "抽取概率",
  "mount.repeatNote": "抽到已拥有的坐骑会突破，星级(★)提升、加成变大（最高★{max}，★{max}为2倍）。★{max}之后退还{n}颗宝石。",
  "mount.pack": "宝石 {n} 个",
  "mount.vipGift": "专属神话坐骑 {name}",
  "mount.name.celestial_dragon": "天上之龙",
  "mount.vipOnly": "VIP {n} 专属（抽不到）",
  "announce.mythic": "[{server}] {name} 获得了神话坐骑 {mount}！！",
  "announce.powerTop": "[{server}] {name} 以战斗力 {n} 登上战斗力第一！",
  "mount.hatch10": "{n}连孵化",
  "mount.hatch10Note": "9折 · 保底稀有以上1个",
  "mount.pity": "传说保底剩 {legendary} 次 · 神话保底剩 {mythic} 次",
  "mount.vipNeed": "所需宝石",
  "mount.vipPerks": "福利",
  "mount.vipAnnounced": "达成时全服公告",
  "mount.vipShow": "各级福利 ▾",
  "mount.vipHide": "收起 ▴",
  "rank.tabLevel": "等级",
  "rank.tabPower": "战斗力",
  "mount.tier.mythic": "神话",
  "mount.name.golden_dragon": "黄金龙",
  "mount.name.void_emperor": "深渊皇帝",
  "announce.vip": "[{server}] {name} 成为 VIP {n}！",
  "mail.pass": "月卡：今日宝石",
  "mail.passBody": "月卡期间内，每天首次登录都会收到宝石。",
  "forge.protect": "用宝石保护 +{n} 以上的强化不被破坏",
  "forge.protected": "防破坏 · 宝石 {n}",
  "mount.vipBonus": "狩猎经验与金币 +{n}%",
  "mount.vipNext": "{have} / {need}",
  "mount.first2x": "首购 2 倍",
  "mount.firstGets": "首购得 {n} 个",
  "mount.pass": "月卡",
  "mount.passWhat": "立得宝石 {now} · {days} 天每天 {daily} · 经验 +{xp}%",
  "mount.passLeft": "剩 {n} 天（购买可延长）",
  "mount.gemsComing": "正在确认购买…",
  "mount.stable": "马厩",
  "mount.tab.stable": "已有坐骑",
  "mount.tab.hatch": "孵蛋",
  "mount.tab.shop": "宝石商店",
  "mount.gemsTitle": "持有宝石",
  "mount.hatchLede": "一颗蛋孵出一只坐骑。等级越高跑得越快。",
  "mount.hatch": "孵化",
  "mount.needGems": "宝石不足 · 前往宝石商店",
  "mount.bonus": "+{n}% 赠送",
  "mount.shopNote": "使用 VX 支付。支付完成后宝石很快到账。",
  "mount.tier.base": "基础",
  "mount.tier.common": "普通",
  "mount.tier.rare": "稀有",
  "mount.tier.epic": "史诗",
  "mount.tier.legendary": "传说",
  "mount.name.deer": "鹿",
  "mount.name.pig": "猪",
  "mount.name.chicken": "鸡",
  "mount.name.penguin": "企鹅",
  "mount.name.panda": "熊猫",
  "mount.name.crab": "螃蟹",
  "mount.name.yeti": "雪人",
  "mount.name.drake": "幼龙",
  "mount.name.cat": "猫",
  "mount.name.dog": "狗",
  "mount.name.pigeon": "鸽子",
  "mount.name.armabee": "铠甲蜂",
  "mount.name.glub": "咕噜",
  "mount.name.squidle": "翼乌贼",
  "mount.name.hywirl": "旋风",
  "mount.name.alpaking": "羊驼王",
  "mount.name.queen_armabee": "铠甲蜂后",
  "mount.name.elder_glub": "远古咕噜",
  "mount.name.alpaking_emperor": "羊驼皇帝",
  "mount.name.dragon": "龙",
};
