import type { Bundle } from "./ko";

export const zhHans: Bundle = {
  "common.close": "关闭",
  "common.back": "返回",
  "common.on": "开启",
  "common.off": "关闭",
  "common.none": "关",

  "settings.title": "设置",
  "settings.sound": "声音",
  "settings.music": "背景音乐",
  "settings.effects": "音效",
  "settings.controls": "操作",
  "settings.sensitivity": "鼠标灵敏度",
  "settings.times": "{n}倍",
  "settings.screen": "画面",
  "settings.brightness": "亮度",
  "settings.quality": "画质",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "越低越省性能和电量。会改变树木与草地的完整绘制距离，以及画面分辨率。",
  "settings.shown": "显示",
  "settings.showNames": "其他玩家名称",
  "settings.damageNumbers": "伤害数字",
  "settings.language": "语言",
  "settings.keys.show": "显示快捷键",
  "settings.keys.hide": "隐藏快捷键",
  "settings.defaults": "默认值",
  "settings.exit": "回到菜单",

  "keys.move": "移动",
  "keys.jump": "跳跃",
  "keys.click": "左键 / 右键",
  "keys.attackGuard": "攻击 / 格挡",
  "keys.skills": "技能",
  "keys.potion": "药水",
  "keys.talk": "对话",
  "keys.auto": "自动战斗",
  "keys.quest": "前往任务・汇报",
  "keys.chat": "聊天",
  "keys.menu": "展开菜单",
  "keys.closeWindow": "关闭窗口",
  "keys.map": "地图",
  "keys.panels": "排行 / 任务 / 技能 / 铁匠铺 / 背包",
  "keys.powerSave": "省电模式",
  "keys.settings": "设置",

  "list.join": "、",
  "stat.power": "攻击力 +{n}%",
  "stat.hp": "体力 +{n}",
  "stat.guard": "受到伤害 -{n}%",
  "stat.heal": "治疗量 +{n}%",

  "class.warrior": "战士",
  "class.ranger": "弓箭手",
  "class.wizard": "法师",
  "class.cleric": "牧师",
  "class.rogue": "盗贼",
  "class.monk": "武斗家",
  "class.warrior.blurb": "长剑与盔甲。站稳脚步一路砍过去。",
  "class.ranger.blurb": "从远处射箭。被贴近就弱了。",
  "class.wizard.blurb": "以法杖射出魔弹。慢，但打得远。",
  "class.cleric.blurb": "治疗自己与身边的伙伴。",
  "class.rogue.blurb": "用短剑极快地刺击。",
  "class.monk.blurb": "赤手连打，还有让人晕眩的招式。",

  "weapon.warrior": "长剑",
  "weapon.ranger": "弓",
  "weapon.wizard": "魔法杖",
  "weapon.cleric": "圣职者之杖",
  "weapon.rogue": "短剑",
  "weapon.monk": "拳",

  "skill.warrior.0": "回旋斩",
  "skill.warrior.0.blurb": "旋转一圈，砍中周围所有怪物。",
  "skill.berserker.0": "突进斩",
  "skill.berserker.0.blurb": "向前大力挥砍，短暂击倒对手。",
  "skill.berserker.1": "大地强击",
  "skill.berserker.1.blurb": "重击地面，晕眩周围所有怪物。",
  "skill.ranger.0": "贯穿之箭",
  "skill.ranger.0.blurb": "笔直飞出，贯穿成列的怪物。",
  "skill.sniper.0": "瞄准射击",
  "skill.sniper.0.blurb": "锁定一个目标，造成大量伤害。",
  "skill.sniper.1": "箭雨",
  "skill.sniper.1.blurb": "向周围倾泻箭矢。",
  "skill.wizard.0": "烈焰爆发",
  "skill.wizard.0.blurb": "以火焰覆盖周围，烧灼怪物。",
  "skill.elementalist.0": "冰之枪",
  "skill.elementalist.0.blurb": "贯穿并冻结一个目标，使其无法移动。",
  "skill.elementalist.1": "陨石坠落",
  "skill.elementalist.1.blurb": "自天而降的火球，烧尽周围。",
  "skill.cleric.0": "治愈之光",
  "skill.cleric.0.blurb": "回复自己与附近伙伴的体力。",
  "skill.paladin.0": "神圣一击",
  "skill.paladin.0.blurb": "杖上凝光击向前方，并使其晕眩。",
  "skill.high_priest.1": "祝福",
  "skill.high_priest.1.blurb": "烧灼周围怪物，并大幅回复伙伴。",
  "skill.rogue.0": "暗影一击",
  "skill.rogue.0.blurb": "深深刺向前方的一个怪物。",
  "skill.assassin.0": "刃之扇",
  "skill.assassin.0.blurb": "向前方撒出短剑。",
  "skill.assassin.1": "暗影乱舞",
  "skill.assassin.1.blurb": "搅动周围，一并斩尽。",
  "skill.monk.0": "晕眩连打",
  "skill.monk.0.blurb": "痛击前方怪物，使其晕眩一段时间。",
  "skill.fist_master.0": "旋风踢",
  "skill.fist_master.0.blurb": "旋身踢击，打中周围所有目标。",
  "skill.fist_master.1": "白热拳",
  "skill.fist_master.1.blurb": "将全力的一拳灌入单一目标。",
  "skill.guardian.0": "盾击",
  "skill.guardian.0.blurb": "以盾牌重击前方的一个怪物，使其长时间晕眩。",
  "skill.guardian.1": "守护战吼",
  "skill.guardian.1.blurb": "以战吼冲击周围，并回复自己与伙伴的体力。",
  "skill.tracker.0": "陷阱之箭",
  "skill.tracker.0.blurb": "射中一个目标，将其定在原地。",
  "skill.tracker.1": "扇形射击",
  "skill.tracker.1.blurb": "向前方大范围倾泻箭矢。",
  "skill.warder.0": "结界波动",
  "skill.warder.0.blurb": "展开结界冲击周围，并短暂将其束缚。",
  "skill.warder.1": "守护结界",
  "skill.warder.1.blurb": "大幅回复自己与附近伙伴的体力。",
  "skill.high_priest.0": "净化之光",
  "skill.high_priest.0.blurb": "以光束烧灼一个目标，并稍微回复自己与伙伴。",
  "skill.paladin.1": "审判之锤",
  "skill.paladin.1.blurb": "挥下光之重锤，使周围全数晕眩。",
  "skill.scout.0": "烟幕",
  "skill.scout.0.blurb": "施放烟幕，使周围怪物暂时停下。",
  "skill.scout.1": "飞刀连掷",
  "skill.scout.1.blurb": "将短剑呈扇形远远掷出。",
  "skill.iron_monk.0": "铁山靠",
  "skill.iron_monk.0.blurb": "以肩撞击，使前方大范围晕眩。",
  "skill.iron_monk.1": "金刚不坏",
  "skill.iron_monk.1.blurb": "爆发气劲冲击周围，并回复自己与伙伴的体力。",
  "class.paths": "Lv{n} 转职・二选一",
  "skills.pathSlot": "转职技能 {n}",
  "skills.afterAdvance": "Lv{n} 转职后学会",

  "job.berserker": "狂战士",
  "job.guardian": "守护骑士",
  "job.sniper": "狙击手",
  "job.tracker": "森林追踪者",
  "job.elementalist": "元素术士",
  "job.warder": "结界术士",
  "job.high_priest": "大祭司",
  "job.paladin": "圣骑士",
  "job.assassin": "刺客",
  "job.scout": "斥候",
  "job.fist_master": "拳圣",
  "job.iron_monk": "铁壁修士",

  "item.heal": "回复体力 {n}",
  "item.potion_small": "小型药水",
  "item.potion_big": "大型药水",
  "item.weapon_1": "学徒的武器",
  "item.weapon_2": "林守的武器",
  "item.weapon_3": "蘑菇王的武器",
  "item.weapon_4": "钢制武器",
  "item.weapon_5": "岩心武器",
  "item.armor_1": "皮甲",
  "item.armor_2": "林守的护甲",
  "item.armor_3": "蘑菇王的护甲",
  "item.armor_4": "钢制护甲",
  "item.armor_5": "岩心护甲",
  "item.stone": "强化石",
  "item.stone.blurb": "强化装备的材料。所有狩猎场。",
  "item.jelly": "史莱姆凝胶",
  "item.jelly.blurb": "制作材料。森林原野 1。",
  "item.silk": "蜘蛛丝",
  "item.silk.blurb": "制作材料。森林原野 2。",
  "item.core": "岩心石",
  "item.core.blurb": "制作材料。深邃森林。",
  "item.spore": "蘑菇王的孢子",
  "item.spore.blurb": "制作材料。蘑菇王。",

  "monster.green_blob": "绿史莱姆",
  "monster.mushnub": "小蘑菇",
  "monster.rat": "野鼠",
  "monster.frog": "青蛙",
  "monster.spider": "森林蜘蛛",
  "monster.snake": "毒蛇",
  "monster.wasp": "黄蜂",
  "monster.bat": "蝙蝠",
  "monster.goleling": "魔像幼体",
  "monster.dire_spider": "巨型毒蛛",
  "monster.venom_snake": "剧毒蛇",
  "monster.hornet": "大虎头蜂",
  "monster.vampire_bat": "吸血蝙蝠",
  "monster.stone_golem": "岩石魔像",
  "monster.mushnub_guard": "蘑菇护卫",
  "monster.mushroom_king": "蘑菇王",

  "zone.village": "绿林村",
  "zone.forest1": "森林原野 1",
  "zone.forest2": "森林原野 2",
  "zone.forest3": "深邃森林",
  "zone.boss": "蘑菇王的空地",

  "npc.merchant": "商人汉斯",
  "npc.merchant.role": "商店",
  "npc.elder": "村长玛尔塔",
  "npc.elder.role": "任务",
  "npc.smith": "铁匠沃尔夫",
  "npc.smith.role": "强化・制作",

  "world.name": "绿林",

  "quest.0": "史莱姆讨伐",
  "quest.0.goal": "森林原野 1 的绿史莱姆 15 只",
  "quest.1": "清剿小蘑菇",
  "quest.1.goal": "森林原野 1 的小蘑菇 20 只",
  "quest.2": "原野的麻烦",
  "quest.2.goal": "野鼠或青蛙 40 只",
  "quest.3": "深林侦察",
  "quest.3.goal": "森林原野 2 的森林蜘蛛或毒蛇 50 只",
  "quest.4": "天空的狩猎",
  "quest.4.goal": "黄蜂或蝙蝠 60 只",
  "quest.5": "石之精灵",
  "quest.5.goal": "魔像幼体 60 只",
  "quest.6": "讨伐蘑菇王",
  "quest.6.goal": "蘑菇王空地的蘑菇王",
  "quest.7": "深邃森林的蛛穴",
  "quest.7.goal": "深邃森林的巨型毒蛛或剧毒蛇 60 只",
  "quest.8": "遮天之翼",
  "quest.8.goal": "大虎头蜂或吸血蝙蝠 80 只",
  "quest.9": "森林的守护石",
  "quest.9.goal": "岩石魔像 60 只",
  "quest.10": "魔像之心",
  "quest.10.goal": "岩石魔像 100 只",
  "quest.11": "再讨蘑菇王",
  "quest.11.goal": "击倒蘑菇王 3 次",
  "quest.12": "深邃森林之主",
  "quest.12.goal": "深邃森林的怪物 200 只",
  "daily.forest1": "巡逻：森林原野 1",
  "daily.forest1.goal": "森林原野 1 的怪物 30 只",
  "daily.forest2": "巡逻：森林原野 2",
  "daily.forest2.goal": "森林原野 2 的怪物 40 只",
  "daily.forest3": "巡逻：深邃森林",
  "daily.forest3.goal": "深邃森林的怪物 50 只",

  "common.loading": "加载中…",
  "common.gold": "{n} 金币",
  "common.nothing": "无",
  "problem.unavailable": "当前无法进行",
  "problem.max_plus": "已无法继续强化",
  "problem.not_near": "需要靠近铁匠才能进行",
  "problem.not_enough_gold": "金币不足",
  "problem.not_in_village": "商店在村子里",
  "problem.no_item": "背包里没有",
  "problem.too_low_advance": "Lv{n} 起可以转职",

  "slot.weapon": "武器",
  "slot.armor": "护甲",

  "bag.title": "背包",
  "bag.power": "战斗力 {n}",
  "bag.job": "转职",
  "bag.advanceAt": "到 Lv{at} 就能转职（目前 Lv{level}）",
  "bag.pickPath": "请选择转职的道路。一旦选定就不能更改。",
  "bag.unequip": "卸下",
  "bag.empty": "背包是空的",
  "bag.drink": "饮用",
  "bag.equip": "装备",
  "bag.sell": "卖出（{n}）",
  "bag.keys": "Q：喝药水 · I：背包",

  "shop.title": "村庄商店",
  "shop.buy": "购买",
  "shop.buyTen": "10 个",
  "shop.note": "怪物会掉落金币与装备。卖出请从背包。",

  "forge.title": "铁匠铺",
  "forge.stones": "强化石 {n} 个",
  "forge.enhance": "强化",
  "forge.craft": "制作",
  "forge.noGear": "沒有装备任何東西",
  "forge.chance": "+{to} 成功 {pct}",
  "forge.breakRisk": "失败时损毁 {pct}",
  "forge.maxed": "已達最高强化（+{n}）",
  "forge.note": "从 +{n} 起，失败可能损毁装备。强化石由所有狩猎场的怪物掉落。",
  "forge.success": "强化成功！",
  "forge.fail": "强化失败… 装备没有损伤",
  "forge.broken": "强化失败… 装备损毁了",
  "forge.crafted": "{name} 制作完成！",

  "common.retry": "再试一次",
  "common.toMenu": "回到菜单",
  "common.menu": "菜单",
  "common.off2": "关闭",

  "problem.not_owned": "这片狩猎场需要正式版",
  "problem.zone_full": "所有频道都满了。请稍后再试",
  "problem.not_near_portal": "请站到传送门旁",
  "problem.too_low": "等级不足",
  "problem.cannotTravel": "当前无法前往",
  "problem.enter": "无法进入世界",
  "problem.enterWith": "无法进入世界（{error}）",
  "problem.connect": "无法连上游戏服务器。请检查网络后再试一次。",
  "problem.tooFast": "请说慢一点",
  "problem.cannotSend": "无法发送",

  "world.entering": "正在进入世界…",
  "world.loading": "正在加载森林… {n}%",
  "world.travelling": "移动中…",
  "world.channel": "频道 {n}",
  "world.talk": "{name} — {role} · 对话 (E)",
  "world.portalLocked": "{zone} — 正式版可进入 {how}",
  "world.portalLocked.tap": "· 点击查看",
  "world.portalLevel": "{zone} — Lv{n} 起可前往",
  "world.portalTo": "通往{zone}的路",
  "world.blocking": "格挡中",

  "menu.map": "地图",
  "menu.upgrade": "正式版",
  "menu.ranking": "排行",
  "menu.quests": "任务",
  "menu.skills": "技能",
  "menu.forge": "铁匠铺",
  "menu.bag": "背包",
  "menu.sleep": "省电",
  "menu.settings": "设置",

  "death.fallen": "你倒下了",
  "death.lostXp": "失去了 {n} 经验值",
  "death.lostNone": "没有失去经验值",
  "death.lossNote": "倒下会失去本级经验值的 {n}%（等级不会下降）",
  "death.here": "原地复活 · {gold}",
  "death.hereNote": "以 {n}% 体力起身，怪物会暂时不攻击你",
  "death.short": " · 金币不足",
  "death.village": "在村庄复活 · 免费",

  "sleep.title": "省电模式",
  "sleep.elapsed": "经过时间",
  "sleep.xp": "获得经验值",
  "sleep.gold": "获得金币",
  "sleep.potions": "剩余药水",
  "sleep.potionCount": "{n} 个",
  "sleep.auto": "自动战斗",
  "sleep.hunting": "狩猎中",
  "sleep.dead": "你倒下了 — 点两下查看",
  "sleep.hint": "点两下画面即可返回",

  "chat.placeholder": "对频道说话",
  "chat.open": "聊天",

  "quest.allDone": "所有任务完成",
  "quest.reportHere": "点击向村长汇报",
  "quest.reportInVillage": "请向村里的村长汇报",
  "quest.seeking": "前往中…",
  "quest.goFind": "点击前往",

  "pad.attack": "攻击",
  "pad.block": "格挡",
  "pad.jump": "跳跃",
  "pad.auto": "自动",
  "pad.autoOn": "自动中",
  "pad.talk": "对话",
  "pad.leftClick": "左键",
  "pad.rightClick": "右键",

  "map.tapToWalk": "点击即可走到那里",
  "map.portals": "区域出入口",
  "map.villagers": "村民",
  "map.you": "你",
  "map.close": "关闭 (N)",

  "bar.potion": "药水",
  "bar.emptySlot": "空格",
  "bar.autoPotion": "自动药水",
  "bar.autoPotionTitle": "自动药水设置",
  "bar.autoPotionAt": "生命低于 {n}% 时会喝药水",
  "bar.autoPotionOff": "（目前已关闭）",
  "bar.autoPotionTurnOn": "开启自动药水",
  "bar.autoPotionTurnOff": "关闭自动药水",

  "skills.title": "技能",
  "skills.dragNote": "把学会的技能拖到下方的格子。",
  "skills.learnAt": "Lv{n} 学会",
  "skills.inSlot": "第 {n} 格",
  "skills.dragIn": "拖曳放入格子",
  "skills.cooldown": "冷却 {n} 秒",
  "skills.remove": "取出",

  "common.next": "下一步",
  "common.accept": "接受",
  "common.decline": "拒绝",

  "lobby.newCharacter": "新角色",
  "lobby.needServer": "需要连上 Verse8 服务器才能开始游戏。",
  "lobby.accountFailed": "无法读取账号资料。请刷新。",
  "lobby.accountLoading": "正在读取账号资料…",
  "lobby.loading": "正在加载村庄… {n}%",
  "lobby.tapToStart": "点击画面开始",
  "lobby.friends": "好友",
  "lobby.characters": "{world} · 角色 {n}/{max}",
  "lobby.createCharacter": "+ 创建角色",
  "lobby.start": "开始游戏",
  "lobby.changeServer": "更换服务器",
  "lobby.noCharacter": "创建角色，开始冒险吧。",
  "lobby.freeNote": "村庄与森林原野 1 可以免费游玩。",
  "lobby.guestNote": "你尚未登录。现在创建的角色下次无法读取。请先登录 Verse8 再开始。",

  "buy.buy": "购买正式版（{price} VX）",
  "buy.confirming": "正在确认付款…",
  "buy.late": "付款确认较久。请稍后刷新。",
  "buy.title": "正式版",
  "buy.short": "购买正式版",
  "buy.checking": "确认付款中…",
  "buy.noServer": "目前无法购买。连接后请再试一次。",
  "buy.reason.portal": "通往{zone}的路需要正式版。",
  "buy.reason.level": "Lv {n} 达成！免费能去的就到这里。",
  "buy.reason.menu": "免费可游玩村庄与森林原野 1，直到 Lv {n}。",
  "buy.fields": "{n} 处新狩猎场",
  "buy.noCap": "解除等级上限",
  "buy.noCapNote": "不停在 Lv {n}，一路到两个转职技能（Lv {third}）",
  "buy.bossNote": "会重击并召唤手下的首领，以及它的专属装备",
  "buy.classes": "{n} 种职业",
  "buy.off": "{n}% 折扣",

  "class.pick": "选择职业",
  "class.weapon": "武器",
  "class.ranged": "远程",
  "class.melee": "近战",
  "class.damage": "攻击力",
  "class.speed": "攻击速度",
  "class.perSecond": "{n} 次/秒",
  "class.reach": "射程",
  "class.block": "格挡",
  "class.skillLine": "技能 {n} · {name}",
  "class.lockedNote": "正式版职业。免费可选战士与弓箭手。",
  "class.confirm": "选定这个职业",
  "class.onceNote": "职业在创建角色时决定一次。",
  "class.pickHint": "点击角色来查看职业。",

  "look.title": "决定角色外观",
  "look.spin": "拖曳可旋转",
  "look.shape": "外观",
  "look.random": "随机",
  "look.making": "创建中…",
  "look.create": "创建角色",
  "look.onceNote": "外观在创建角色后就不能更改。",
  "look.previous": "{part} 上一个",
  "look.next": "{part} 下一个",

  "part.gear": "饰品",
  "part.clothColor": "衣服颜色",
  "part.skin": "肤色",
  "part.weaponColor": "武器颜色",
  "look.default": "默认",
  "look.on": "配戴",
  "look.off": "取下",
  "look.grey": "无彩色",
  "look.dye": "染色 {n}",
  "look.skinLight": "白皙",
  "look.skinTan": "小麦色",
  "look.skinDark": "深色",
  "look.mine": "自己的样子",
  "look.preset.light": "轻装",
  "look.preset.shadow": "暗影",

  "name.title": "角色名称",
  "name.note": "其他玩家与好友会以这个名字看到你。文字、数字或 _ 共 2～12 字，且不能与其他角色重复。",
  "name.placeholder": "名称",
  "name.checking": "确认中…",

  "server.pick": "选择服务器",
  "server.note": "选同一台服务器的玩家才会相遇。和朋友选同一台吧。",
  "server.entering": "进入中…",
  "server.recent": "最近游玩",
  "server.failed": "无法选择服务器。请稍后再试一次",

  "common.add": "添加",
  "common.cancel": "取消",
  "common.remove": "删除",
  "common.removeSure": "确定删除",
  "common.noName": "（没有名字）",
  "common.reward": "报酬：{what}",
  "common.xp": "{n} XP",

  "friends.title": "好友",
  "friends.needCharacter": "要添加好友，请先创建角色。",
  "friends.search": "以名称添加好友",
  "friends.needServer": "好友需连上 Verse8 后才能使用。",
  "friends.loading": "正在读取好友名单…",
  "friends.sent": "已发出好友邀请",
  "friends.bothWays": "双方都发出邀请，已成为好友",
  "friends.nowFriends": "你和 {name} 成为好友了",
  "friends.incoming": "收到的邀请 {n}",
  "friends.list": "好友名单",
  "friends.online": "· 在线 {on}/{all}",
  "friends.none": "还没有好友。试着用名称添加吧。",
  "friends.isOnline": "在线",
  "friends.isOffline": "离线",
  "friends.outgoing": "发出的邀请",
  "friends.waiting": "等待中",

  "problem.friend_not_found": "找不到这个名称",
  "problem.friend_self": "不能添加自己",
  "problem.already_friends": "已经是好友",
  "problem.friend_limit": "好友最多 {n} 位",
  "problem.request_limit": "对方收到的邀请太多了",
  "problem.no_request": "这个邀请已经处理过了",
  "problem.nickname_taken": "这个名称已被使用",
  "problem.nickname_invalid": "可用文字、数字或 _ 共 2～12 字",
  "problem.character_limit": "这台服务器无法再创建角色",
  "problem.retryLater": "当前无法进行。请稍后再试一次",
  "problem.saveFailed": "无法保存。请稍后再试一次",
  "problem.not_near_elder": "请站到村长旁边说话",
  "problem.quest_unfinished": "还没有完成",
  "problem.cannotClaim": "当前无法领取",

  "rank.title": "排行榜",
  "rank.needServer": "连上 Verse8 后即可查看。",
  "rank.failed": "无法读取排行榜。请稍后再打开。",
  "rank.none": "还没有累积经验值的冒险者。",
  "rank.unranked": "未上榜",
  "rank.place": "第 {n} 名",
  "rank.nickname": "名称",
  "rank.class": "职业",
  "rank.level": "等级",
  "rank.rank": "名次",
  "rank.server": "服务器",
  "rank.xp": "经验值",
  "rank.power": "战斗力",
  "rank.detailFailed": "无法读取资料。",
  "rank.toList": "回到名单",

  "quests.title": "任务",
  "quests.daily": "每日任务 · 每天 0 点重新开始",
  "quests.claim": "领取报酬",
  "quests.claimedToday": "今天的报酬已领取",
  "quests.goReport": "去向村长汇报",
  "quests.reportHint": "向村里的村长汇报即可领取报酬",
  "quests.goFind": "前往",
  "quests.allDone": "所有任务都完成了。",
  "quests.past": "已完成的任务",
  "quests.more": "还有 {n} 个任务。",
  "quests.complete": "任务完成！",
  "quests.reportHere": "向村长汇报并领取报酬",
  "quests.reportInVillage": "向村里的村长汇报并领取报酬",
  "npc.elder.done": "「这座森林里已经没有能难倒你的了。谢谢你，猎人。」",
  "npc.elder.claim": "「{quest}，做得好！这是说好的报酬。」",
  "npc.elder.ask": "「{goal}，就拜托你了。」",

  "note.notHere": "这个区域没有",
  "note.notHereBut": "这个区域没有（{zones}）",
  "note.cannotWalk": "那里去不了",
  "note.gotGold": "+{n} 金币",
  "note.gotItem": "获得 {name}",
  "portal.needsFull": "（正式版）",
  "portal.needsLevel": "（Lv{n}）",

  "error.startFailed": "无法启动游戏。",
  "error.reload": "重新加载",
  "rotate.hint": "把画面转成横向会更好玩",
};
