import type { Bundle } from "./ko";

export const zhHans: Bundle = {
  "common.close": "关闭",
  "common.back": "返回",
  "common.on": "开启",
  "common.off": "关闭",
  "common.none": "关",

  "settings.title": "设置",
  "settings.sound": "声音",
  "settings.music": "背景音乐",
  "settings.effects": "音效",
  "settings.controls": "操作",
  "settings.sensitivity": "鼠标灵敏度",
  "settings.times": "{n}倍",
  "settings.screen": "画面",
  "settings.brightness": "亮度",
  "settings.quality": "画质",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "越低越省性能和电量。会改变树木与草地的完整绘制距离，以及画面分辨率。",
  "settings.shown": "显示",
  "settings.showNames": "其他玩家名称",
  "settings.damageNumbers": "伤害数字",
  "settings.language": "语言",
  "settings.keys.show": "显示快捷键",
  "settings.keys.hide": "隐藏快捷键",
  "settings.defaults": "默认值",
  "settings.exit": "回到菜单",

  "keys.move": "移动",
  "keys.jump": "跳跃",
  "keys.click": "左键 / 右键",
  "keys.attackGuard": "攻击 / 格挡",
  "keys.skills": "技能",
  "keys.potion": "药水",
  "keys.talk": "对话",
  "keys.auto": "自动战斗",
  "keys.quest": "前往任务・汇报",
  "keys.chat": "聊天",
  "keys.menu": "展开菜单",
  "keys.closeWindow": "关闭窗口",
  "keys.map": "地图",
  "keys.panels": "排行 / 任务 / 技能 / 铁匠铺 / 背包",
  "keys.powerSave": "省电模式",
  "keys.settings": "设置",
};
