import type { Bundle } from "./ko";

export const zhHant: Bundle = {
  "common.close": "關閉",
  "common.back": "返回",
  "common.on": "開啟",
  "common.off": "關閉",
  "common.none": "關",

  "settings.title": "設定",
  "settings.sound": "音效",
  "settings.music": "背景音樂",
  "settings.effects": "音效",
  "settings.controls": "操作",
  "settings.sensitivity": "滑鼠靈敏度",
  "settings.times": "{n}倍",
  "settings.screen": "畫面",
  "settings.brightness": "亮度",
  "settings.quality": "畫質",
  "settings.quality.low": "低",
  "settings.quality.mid": "中",
  "settings.quality.high": "高",
  "settings.quality.note": "越低越省效能與電量。會改變樹木與草地的完整繪製距離，以及畫面解析度。",
  "settings.shown": "顯示",
  "settings.showNames": "其他玩家名稱",
  "settings.damageNumbers": "傷害數字",
  "settings.language": "語言",
  "settings.keys.show": "顯示快捷鍵",
  "settings.keys.hide": "隱藏快捷鍵",
  "settings.defaults": "預設值",
  "settings.exit": "回到選單",

  "keys.move": "移動",
  "keys.jump": "跳躍",
  "keys.click": "左鍵 / 右鍵",
  "keys.attackGuard": "攻擊 / 格擋",
  "keys.skills": "技能",
  "keys.potion": "藥水",
  "keys.talk": "對話",
  "keys.auto": "自動戰鬥",
  "keys.quest": "前往任務・回報",
  "keys.chat": "聊天",
  "keys.menu": "展開選單",
  "keys.closeWindow": "關閉視窗",
  "keys.map": "地圖",
  "keys.panels": "排行 / 任務 / 技能 / 鐵匠鋪 / 背包",
  "keys.powerSave": "省電模式",
  "keys.settings": "設定",

  "list.join": "、",
  "stat.power": "攻擊力 +{n}%",
  "stat.hp": "體力 +{n}",
  "stat.guard": "受到傷害 -{n}%",
  "stat.heal": "治療量 +{n}%",

  "class.warrior": "戰士",
  "class.ranger": "弓箭手",
  "class.wizard": "法師",
  "class.cleric": "牧師",
  "class.rogue": "盜賊",
  "class.monk": "武鬥家",
  "class.warrior.blurb": "長劍與盔甲。站穩腳步一路砍過去。",
  "class.ranger.blurb": "從遠處射箭。被貼近就弱了。",
  "class.wizard.blurb": "以法杖射出魔彈。慢，但打得遠。",
  "class.cleric.blurb": "治療自己與身邊的夥伴。",
  "class.rogue.blurb": "用短劍極快地刺擊。",
  "class.monk.blurb": "赤手連打，還有讓人暈眩的招式。",

  "weapon.warrior": "長劍",
  "weapon.ranger": "弓",
  "weapon.wizard": "魔法杖",
  "weapon.cleric": "聖職者之杖",
  "weapon.rogue": "短劍",
  "weapon.monk": "拳",

  "skill.warrior.0": "迴旋斬",
  "skill.warrior.0.blurb": "旋轉一圈，砍中周圍所有怪物。",
  "skill.warrior.1": "突進斬",
  "skill.warrior.1.blurb": "向前大力揮砍，短暫擊倒對手。",
  "skill.warrior.2": "大地強擊",
  "skill.warrior.2.blurb": "重擊地面，暈眩周圍所有怪物。",
  "skill.ranger.0": "貫穿之箭",
  "skill.ranger.0.blurb": "筆直飛出，貫穿成列的怪物。",
  "skill.ranger.1": "瞄準射擊",
  "skill.ranger.1.blurb": "鎖定一個目標，造成大量傷害。",
  "skill.ranger.2": "箭雨",
  "skill.ranger.2.blurb": "向周圍傾瀉箭矢。",
  "skill.wizard.0": "烈焰爆發",
  "skill.wizard.0.blurb": "以火焰覆蓋周圍，燒灼怪物。",
  "skill.wizard.1": "冰之槍",
  "skill.wizard.1.blurb": "貫穿並凍結一個目標，使其無法移動。",
  "skill.wizard.2": "隕石墜落",
  "skill.wizard.2.blurb": "自天而降的火球，燒盡周圍。",
  "skill.cleric.0": "治癒之光",
  "skill.cleric.0.blurb": "回復自己與附近夥伴的體力。",
  "skill.cleric.1": "神聖一擊",
  "skill.cleric.1.blurb": "杖上凝光擊向前方，並使其暈眩。",
  "skill.cleric.2": "祝福",
  "skill.cleric.2.blurb": "燒灼周圍怪物，並大幅回復夥伴。",
  "skill.rogue.0": "暗影一擊",
  "skill.rogue.0.blurb": "深深刺向前方的一個怪物。",
  "skill.rogue.1": "刃之扇",
  "skill.rogue.1.blurb": "向前方撒出短劍。",
  "skill.rogue.2": "暗影亂舞",
  "skill.rogue.2.blurb": "攪動周圍，一併斬盡。",
  "skill.monk.0": "暈眩連打",
  "skill.monk.0.blurb": "痛擊前方怪物，使其暈眩一段時間。",
  "skill.monk.1": "旋風踢",
  "skill.monk.1.blurb": "旋身踢擊，打中周圍所有目標。",
  "skill.monk.2": "白熱拳",
  "skill.monk.2.blurb": "將全力的一拳灌入單一目標。",

  "job.berserker": "狂戰士",
  "job.guardian": "守護騎士",
  "job.sniper": "狙擊手",
  "job.tracker": "森林追蹤者",
  "job.elementalist": "元素術士",
  "job.warder": "結界術士",
  "job.high_priest": "大祭司",
  "job.paladin": "聖騎士",
  "job.assassin": "刺客",
  "job.scout": "斥候",
  "job.fist_master": "拳聖",
  "job.iron_monk": "鐵壁修士",

  "item.heal": "回復體力 {n}",
  "item.potion_small": "小型藥水",
  "item.potion_big": "大型藥水",
  "item.weapon_1": "學徒的武器",
  "item.weapon_2": "林守的武器",
  "item.weapon_3": "蘑菇王的武器",
  "item.weapon_4": "鋼製武器",
  "item.weapon_5": "岩心武器",
  "item.armor_1": "皮甲",
  "item.armor_2": "林守的護甲",
  "item.armor_3": "蘑菇王的護甲",
  "item.armor_4": "鋼製護甲",
  "item.armor_5": "岩心護甲",
  "item.stone": "強化石",
  "item.stone.blurb": "強化裝備的材料。所有狩獵場。",
  "item.jelly": "史萊姆凝膠",
  "item.jelly.blurb": "製作材料。森林原野 1。",
  "item.silk": "蜘蛛絲",
  "item.silk.blurb": "製作材料。森林原野 2。",
  "item.core": "岩心石",
  "item.core.blurb": "製作材料。深邃森林。",
  "item.spore": "蘑菇王的孢子",
  "item.spore.blurb": "製作材料。蘑菇王。",

  "monster.green_blob": "綠史萊姆",
  "monster.mushnub": "小蘑菇",
  "monster.rat": "野鼠",
  "monster.frog": "青蛙",
  "monster.spider": "森林蜘蛛",
  "monster.snake": "毒蛇",
  "monster.wasp": "黃蜂",
  "monster.bat": "蝙蝠",
  "monster.goleling": "魔像幼體",
  "monster.dire_spider": "巨型毒蛛",
  "monster.venom_snake": "劇毒蛇",
  "monster.hornet": "大虎頭蜂",
  "monster.vampire_bat": "吸血蝙蝠",
  "monster.stone_golem": "岩石魔像",
  "monster.mushnub_guard": "蘑菇護衛",
  "monster.mushroom_king": "蘑菇王",

  "zone.village": "綠林村",
  "zone.forest1": "森林原野 1",
  "zone.forest2": "森林原野 2",
  "zone.forest3": "深邃森林",
  "zone.boss": "蘑菇王的空地",

  "npc.merchant": "商人漢斯",
  "npc.merchant.role": "商店",
  "npc.elder": "村長瑪爾塔",
  "npc.elder.role": "任務",
  "npc.smith": "鐵匠沃爾夫",
  "npc.smith.role": "強化・製作",

  "world.name": "綠林",

  "quest.0": "史萊姆討伐",
  "quest.0.goal": "森林原野 1 的綠史萊姆 15 隻",
  "quest.1": "清剿小蘑菇",
  "quest.1.goal": "森林原野 1 的小蘑菇 20 隻",
  "quest.2": "原野的麻煩",
  "quest.2.goal": "野鼠或青蛙 40 隻",
  "quest.3": "深林偵察",
  "quest.3.goal": "森林原野 2 的森林蜘蛛或毒蛇 50 隻",
  "quest.4": "天空的狩獵",
  "quest.4.goal": "黃蜂或蝙蝠 60 隻",
  "quest.5": "石之精靈",
  "quest.5.goal": "魔像幼體 60 隻",
  "quest.6": "討伐蘑菇王",
  "quest.6.goal": "蘑菇王空地的蘑菇王",
  "quest.7": "深邃森林的蛛穴",
  "quest.7.goal": "深邃森林的巨型毒蛛或劇毒蛇 60 隻",
  "quest.8": "遮天之翼",
  "quest.8.goal": "大虎頭蜂或吸血蝙蝠 80 隻",
  "quest.9": "森林的守護石",
  "quest.9.goal": "岩石魔像 60 隻",
  "quest.10": "魔像之心",
  "quest.10.goal": "岩石魔像 100 隻",
  "quest.11": "再討蘑菇王",
  "quest.11.goal": "擊倒蘑菇王 3 次",
  "quest.12": "深邃森林之主",
  "quest.12.goal": "深邃森林的怪物 200 隻",
  "daily.forest1": "巡邏：森林原野 1",
  "daily.forest1.goal": "森林原野 1 的怪物 30 隻",
  "daily.forest2": "巡邏：森林原野 2",
  "daily.forest2.goal": "森林原野 2 的怪物 40 隻",
  "daily.forest3": "巡邏：深邃森林",
  "daily.forest3.goal": "深邃森林的怪物 50 隻",

  "common.loading": "載入中…",
  "common.gold": "{n} 金幣",
  "common.nothing": "無",
  "problem.unavailable": "現在無法進行",
  "problem.max_plus": "已無法再強化",
  "problem.not_near": "要靠近鐵匠才能進行",
  "problem.not_enough_gold": "金幣不足",
  "problem.not_in_village": "商店在村子裡",
  "problem.no_item": "背包裡沒有",
  "problem.too_low_advance": "Lv{n} 起可以轉職",

  "slot.weapon": "武器",
  "slot.armor": "護甲",

  "bag.title": "背包",
  "bag.power": "戰鬥力 {n}",
  "bag.job": "轉職",
  "bag.advanceAt": "到 Lv{at} 就能轉職（目前 Lv{level}）",
  "bag.pickPath": "請選擇轉職的道路。一旦選定就不能更改。",
  "bag.unequip": "卸下",
  "bag.empty": "背包是空的",
  "bag.drink": "飲用",
  "bag.equip": "裝備",
  "bag.sell": "賣出（{n}）",
  "bag.keys": "Q：喝藥水 · I：背包",

  "shop.title": "村莊商店",
  "shop.buy": "購買",
  "shop.buyTen": "10 個",
  "shop.note": "怪物會掉落金幣與裝備。賣出請從背包。",

  "forge.title": "鐵匠鋪",
  "forge.stones": "強化石 {n} 個",
  "forge.enhance": "強化",
  "forge.craft": "製作",
  "forge.noGear": "沒有裝備任何東西",
  "forge.chance": "+{to} 成功 {pct}",
  "forge.breakRisk": "失敗時損毀 {pct}",
  "forge.maxed": "已達最高強化（+{n}）",
  "forge.note": "從 +{n} 起，失敗可能損毀裝備。強化石由所有狩獵場的怪物掉落。",
  "forge.success": "強化成功！",
  "forge.fail": "強化失敗… 裝備沒有損傷",
  "forge.broken": "強化失敗… 裝備損毀了",
  "forge.crafted": "{name} 製作完成！",

  "common.retry": "再試一次",
  "common.toMenu": "回到選單",
  "common.menu": "選單",
  "common.off2": "關閉",

  "problem.not_owned": "這片狩獵場需要正式版",
  "problem.zone_full": "所有頻道都滿了。請稍後再試",
  "problem.not_near_portal": "請站到傳送門旁",
  "problem.too_low": "等級不足",
  "problem.cannotTravel": "現在無法前往",
  "problem.enter": "無法進入世界",
  "problem.enterWith": "無法進入世界（{error}）",
  "problem.connect": "無法連上遊戲伺服器。請檢查網路後再試一次。",
  "problem.tooFast": "請說慢一點",
  "problem.cannotSend": "無法送出",

  "world.entering": "正在進入世界…",
  "world.loading": "正在載入森林… {n}%",
  "world.travelling": "移動中…",
  "world.channel": "頻道 {n}",
  "world.talk": "{name} — {role} · 對話 (E)",
  "world.portalLocked": "{zone} — 正式版可進入 {how}",
  "world.portalLocked.tap": "· 點擊查看",
  "world.portalLevel": "{zone} — Lv{n} 起可前往",
  "world.portalTo": "通往{zone}的路",
  "world.blocking": "格擋中",

  "menu.map": "地圖",
  "menu.upgrade": "正式版",
  "menu.ranking": "排行",
  "menu.quests": "任務",
  "menu.skills": "技能",
  "menu.forge": "鐵匠鋪",
  "menu.bag": "背包",
  "menu.sleep": "省電",
  "menu.settings": "設定",

  "death.fallen": "你倒下了",
  "death.lostXp": "失去了 {n} 經驗值",
  "death.lostNone": "沒有失去經驗值",
  "death.lossNote": "倒下會失去本級經驗值的 {n}%（等級不會下降）",
  "death.here": "原地復活 · {gold}",
  "death.hereNote": "以 {n}% 體力起身，怪物會暫時不攻擊你",
  "death.short": " · 金幣不足",
  "death.village": "在村莊復活 · 免費",

  "sleep.title": "省電模式",
  "sleep.elapsed": "經過時間",
  "sleep.xp": "獲得經驗值",
  "sleep.gold": "獲得金幣",
  "sleep.potions": "剩餘藥水",
  "sleep.potionCount": "{n} 個",
  "sleep.auto": "自動戰鬥",
  "sleep.hunting": "狩獵中",
  "sleep.dead": "你倒下了 — 點兩下查看",
  "sleep.hint": "點兩下畫面即可返回",

  "chat.placeholder": "對頻道說話",
  "chat.open": "聊天",

  "quest.allDone": "所有任務完成",
  "quest.reportHere": "點擊向村長回報",
  "quest.reportInVillage": "請向村裡的村長回報",
  "quest.seeking": "前往中…",
  "quest.goFind": "點擊前往",

  "pad.attack": "攻擊",
  "pad.block": "格擋",
  "pad.jump": "跳躍",
  "pad.auto": "自動",
  "pad.autoOn": "自動中",
  "pad.talk": "對話",
  "pad.leftClick": "左鍵",
  "pad.rightClick": "右鍵",

  "map.tapToWalk": "點擊即可走到那裡",
  "map.portals": "區域出入口",
  "map.villagers": "村民",
  "map.you": "你",
  "map.close": "關閉 (N)",

  "bar.potion": "藥水",
  "bar.emptySlot": "空格",
  "bar.autoPotion": "自動藥水",
  "bar.autoPotionTitle": "自動藥水設定",
  "bar.autoPotionAt": "生命低於 {n}% 時會喝藥水",
  "bar.autoPotionOff": "（目前已關閉）",
  "bar.autoPotionTurnOn": "開啟自動藥水",
  "bar.autoPotionTurnOff": "關閉自動藥水",

  "skills.title": "技能",
  "skills.dragNote": "把學會的技能拖到下方的格子。",
  "skills.learnAt": "Lv{n} 學會",
  "skills.inSlot": "第 {n} 格",
  "skills.dragIn": "拖曳放入格子",
  "skills.cooldown": "冷卻 {n} 秒",
  "skills.remove": "取出",
};
